# generated by protocol_gen.py from vivid_display_v1.toml — do not edit

import struct

CONTROL_HEADER_STRUCT = "<HHI"

def pack_control_header(opcode, flags, json_length):
    return struct.pack(CONTROL_HEADER_STRUCT, opcode, flags, json_length)

def unpack_control_header(body):
    return struct.unpack(CONTROL_HEADER_STRUCT, body)

POINTER_MOTION_STRUCT = "<IddQ"

def pack_pointer_motion(output_id, x, y, time_usec):
    return struct.pack(POINTER_MOTION_STRUCT, output_id, x, y, time_usec)

def unpack_pointer_motion(body):
    return struct.unpack(POINTER_MOTION_STRUCT, body)

POINTER_BUTTON_STRUCT = "<IddIIQ"

def pack_pointer_button(output_id, x, y, button, state, time_usec):
    return struct.pack(POINTER_BUTTON_STRUCT, output_id, x, y, button, state, time_usec)

def unpack_pointer_button(body):
    return struct.unpack(POINTER_BUTTON_STRUCT, body)

POINTER_AXIS_STRUCT = "<IddddIQ"

def pack_pointer_axis(output_id, x, y, delta_x, delta_y, source, time_usec):
    return struct.pack(POINTER_AXIS_STRUCT, output_id, x, y, delta_x, delta_y, source, time_usec)

def unpack_pointer_axis(body):
    return struct.unpack(POINTER_AXIS_STRUCT, body)

FRAME_READY_STRUCT = "<IQIQQI"

def pack_frame_ready(output_id, generation, buffer_index, sequence, target_time_usec, flags):
    return struct.pack(FRAME_READY_STRUCT, output_id, generation, buffer_index, sequence, target_time_usec, flags)

def unpack_frame_ready(body):
    return struct.unpack(FRAME_READY_STRUCT, body)

UNBIND_STRUCT = "<IQ"

def pack_unbind(output_id, generation):
    return struct.pack(UNBIND_STRUCT, output_id, generation)

def unpack_unbind(body):
    return struct.unpack(UNBIND_STRUCT, body)

def pack_audio_samples_bin(count, time_usec, samples):
    return struct.pack('<IQ', count, time_usec) + struct.pack('<' + ('f' * count), *samples)

def unpack_audio_samples_bin(body):
    count, time_usec = struct.unpack_from('<IQ', body, 0)
    samples = struct.unpack_from('<' + ('f' * count), body, 12)
    return count, time_usec, samples
