# generated by protocol_gen.py from vivid_display_v1.toml — do not edit

RESET_DEFAULTS = "reset-defaults"
RESET_DEFAULTS_CAMEL = "resetDefaults"

MUTE = "mute"

VOLUME = "volume"

CHANGE_WALLPAPER = "change-wallpaper"
CHANGE_WALLPAPER_CAMEL = "changeWallpaper"

CHANGE_WALLPAPER_DIRECTORY_PATH = "change-wallpaper-directory-path"
CHANGE_WALLPAPER_DIRECTORY_PATH_CAMEL = "changeWallpaperDirectoryPath"

CHANGE_WALLPAPER_INTERVAL = "change-wallpaper-interval"
CHANGE_WALLPAPER_INTERVAL_CAMEL = "changeWallpaperInterval"

CHANGE_WALLPAPER_MODE = "change-wallpaper-mode"
CHANGE_WALLPAPER_MODE_CAMEL = "changeWallpaperMode"

PLAYBACK_ON_FOCUS = "playback-on-focus"
PLAYBACK_ON_FOCUS_CAMEL = "playbackOnFocus"

PLAYBACK_ON_MAXIMIZE_OR_FULLSCREEN = "playback-on-maximize-or-fullscreen"
PLAYBACK_ON_MAXIMIZE_OR_FULLSCREEN_CAMEL = "playbackOnMaximizeOrFullscreen"

PLAYBACK_ON_AUDIO = "playback-on-audio"
PLAYBACK_ON_AUDIO_CAMEL = "playbackOnAudio"

PLAYBACK_ON_BATTERY = "playback-on-battery"
PLAYBACK_ON_BATTERY_CAMEL = "playbackOnBattery"

APPLICATION_RULES = "application-rules"
APPLICATION_RULES_CAMEL = "applicationRules"

DEBUG_MODE = "debug-mode"
DEBUG_MODE_CAMEL = "debugMode"

RENDER_DEVICE = "render-device"
RENDER_DEVICE_CAMEL = "renderDevice"

CONTENT_FIT = "content-fit"
CONTENT_FIT_CAMEL = "contentFit"

SCENE_FPS = "scene-fps"
SCENE_FPS_CAMEL = "sceneFps"

GFX_REFLECTIONS = "gfx-reflections"
GFX_REFLECTIONS_CAMEL = "gfxReflections"

GFX_VOLUMETRICS = "gfx-volumetrics"
GFX_VOLUMETRICS_CAMEL = "gfxVolumetrics"

GFX_SHADOWS = "gfx-shadows"
GFX_SHADOWS_CAMEL = "gfxShadows"

GFX_POSTPROCESSING = "gfx-postprocessing"
GFX_POSTPROCESSING_CAMEL = "gfxPostprocessing"

GFX_ANTIALIASING = "gfx-antialiasing"
GFX_ANTIALIASING_CAMEL = "gfxAntialiasing"

GFX_TEXTURE_RESOLUTION = "gfx-texture-resolution"
GFX_TEXTURE_RESOLUTION_CAMEL = "gfxTextureResolution"

STARTUP_DELAY = "startup-delay"
STARTUP_DELAY_CAMEL = "startupDelay"

SHOW_PANEL_MENU = "show-panel-menu"
SHOW_PANEL_MENU_CAMEL = "showPanelMenu"

PROJECT_BROWSER_FILTER_STATE = "project-browser-filter-state"
PROJECT_BROWSER_FILTER_STATE_CAMEL = "projectBrowserFilterState"

PROJECT_BROWSER_SORT_KEY = "project-browser-sort-key"
PROJECT_BROWSER_SORT_KEY_CAMEL = "projectBrowserSortKey"

MULTI_DISPLAY_MODE = "multi-display-mode"
MULTI_DISPLAY_MODE_CAMEL = "multiDisplayMode"

PRIMARY_DISPLAY_KEY = "primary-display-key"
PRIMARY_DISPLAY_KEY_CAMEL = "primaryDisplayKey"

CURRENT_CONFIG_DISPLAY_KEY = "current-config-display-key"
CURRENT_CONFIG_DISPLAY_KEY_CAMEL = "currentConfigDisplayKey"

PER_OUTPUT_PROJECTS = "per-output-projects"
PER_OUTPUT_PROJECTS_CAMEL = "perOutputProjects"
