# generated by protocol_gen.py from vivid_display_v1.toml — do not edit

ERROR_NAMES = {
    1: "PROTO_NAME_MISMATCH",
    2: "VERSION_UNSUPPORTED",
    3: "HELLO_REQUIRED",
    4: "DUPLICATE_HELLO",
    100: "CAPS_INVALID",
    101: "CAPS_REQUIRED",
    102: "NO_DMABUF_SCHEME",
    200: "OUTPUT_REJECTED",
    201: "BUFFER_ALLOC_FAILED",
    202: "WINDOW_STATE_INVALID",
    203: "BIND_FAILED_INVALID",
    204: "UPDATE_OUTPUT_INVALID",
    300: "CONTROL_MALFORMED",
    301: "CONTROL_INVALID",
    302: "CONTROL_RENDERER_START_FAILED",
    303: "CONTROL_SUPERSEDED",
}

ERROR_DOMAINS = {
    1: "handshake",
    2: "handshake",
    3: "handshake",
    4: "handshake",
    100: "caps",
    101: "caps",
    102: "caps",
    200: "output",
    201: "output",
    202: "output",
    203: "output",
    204: "output",
    300: "control",
    301: "control",
    302: "control",
    303: "control",
}

ERROR_TERMINAL = {
    1: True,
    2: True,
    3: True,
    4: True,
    100: False,
    101: False,
    102: False,
    200: False,
    201: False,
    202: False,
    203: False,
    204: False,
    300: False,
    301: False,
    302: False,
    303: False,
}

BIND_FAILED_REASON_NAMES = {
    1: "IMPORT_FAILED",
    2: "FRAME_REFRESH_FAILED",
    3: "OOM",
    4: "OTHER",
}

WINDOW_FLAG_NAMES = {
    1: "NON_MINIMIZED",
    2: "FOCUSED",
    4: "MAXIMIZED",
    8: "FULLSCREEN",
}

CLIENT_ROLE_NAMES = {
    1: "CONSUMER",
    2: "CONTROLLER",
    3: "CONSUMER_AND_CONTROLLER",
    4: "PRODUCER",
}

MESSAGE_MIN_VERSION = {
    "AUDIO_SAMPLES_BIN": 2,
}


def error_name(code):
    return ERROR_NAMES.get(code, f"UNKNOWN({code})")

def error_domain(code):
    return ERROR_DOMAINS.get(code, "unknown")

def error_is_terminal(code):
    return ERROR_TERMINAL.get(code, False)

def bind_failed_reason_name(reason):
    return BIND_FAILED_REASON_NAMES.get(reason, f"UNKNOWN({reason})")

def window_flag_name(flag):
    return WINDOW_FLAG_NAMES.get(flag, f"UNKNOWN({flag})")

def client_role_name(role):
    return CLIENT_ROLE_NAMES.get(role, f"UNKNOWN({role})")
