#!/usr/bin/env python3
"""Derive COVERAGE-MATRIX.md: every official scene documentation page and what covers it.

Sources:
  - fixtures/fixtures.json (+ the effects family expanded against the assets directory): each
    fixture lists the docs/en/ pages it exercises
  - .build/golden/config.json: per-workshop-wallpaper mechanism markers from `golden.py init`
  - MARKER_DOCS below: which documentation pages a renderer mechanism marker stands for

A page is "covered" when at least one fixture names it; "workshop-only" when only a workshop
wallpaper marker implies it; otherwise "uncovered". Uncovered pages are coverage candidates;
WORKLIST's active schedule selects behavior work. The matrix is regenerated, never hand-edited.
"""

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE / "fixtures"))
import generate  # noqa: E402

CONFIG_PATH = HERE.parents[2] / ".build/golden/config.json"

# Workshop mechanism markers -> documentation pages they exercise (integration-level only).
MARKER_DOCS = {
    "effect": ["scene/effects/introduction.md", "scene/effects/overview.md"],
    "puppet": ["scene/puppet-warp/introduction.md", "scene/puppet-warp/attachments.md",
               "scene/puppet-warp/animationmixing.md"],
    "text": ["scene/first/assets.md"],
    "dynamic-layers": ["scene/scenescript/reference/class/IScene.md"],
    "video": ["scene/scenescript/reference/class/IVideoTexture.md", "scene/userproperties/texture.md"],
    "camera-layer": ["scene/models/camera.md"],
    "light": ["scene/lighting/introduction.md", "scene/lighting/lights.md"],
    "model": ["scene/models/introduction.md", "scene/models/animation.md"],
    "particle": ["scene/particles/introduction.md"],
    "bloom": ["scene/effects/bloom.md"],
    "volumetrics": ["scene/lighting/lights.md"],
    "script": ["scene/scenescript/introduction.md", "scene/scenescript/reference.md"],
}

# Pages that describe editor or publishing workflow rather than runtime behavior.
NON_RUNTIME_PREFIXES = ("scene/first/publishing.md", "scene/first/gettingstarted.md",
                        "scene/first/effects.md", "scene/first/properties.md", "scene/assets/",
                        "scene/image-preparation/", "scene/performance/", "scene/rgb/",
                        "scene/shader/tutorials/", "scene/shader/mobile.md",
                        "scene/scenescript/tutorial", "scene/particles/tutorial",
                        "scene/puppet-warp/charactersheet.md", "scene/puppet-warp/extending.md")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--docs", required=True, help="Wallpaper Engine documentation language directory")
    parser.add_argument("--assets", required=True)
    parser.add_argument("--output", default=str(HERE / "COVERAGE-MATRIX.md"))
    args = parser.parse_args()

    docs_root = Path(args.docs)
    pages = sorted(str(p.relative_to(docs_root)) for p in (docs_root / "scene").rglob("*.md"))
    spec = json.loads(generate.SPEC_PATH.read_text())
    fixtures = generate.expand_spec(spec, args.assets)
    config = json.loads(CONFIG_PATH.read_text()) if CONFIG_PATH.exists() else {"wallpapers": {}}

    fixture_pages = {}
    for name, entry in fixtures.items():
        for page in entry.get("docs", []):
            fixture_pages.setdefault(page, []).append(name)
    marker_wallpapers = {}
    for wallpaper_id, entry in config.get("wallpapers", {}).items():
        for marker in entry.get("markers", {}):
            marker_wallpapers.setdefault(marker, []).append(wallpaper_id)
    workshop_pages = {}
    for marker, ids in marker_wallpapers.items():
        for page in MARKER_DOCS.get(marker, []):
            workshop_pages.setdefault(page, set()).update(ids)

    covered, workshop_only, uncovered, non_runtime = [], [], [], []
    for page in pages:
        if page in fixture_pages:
            covered.append(page)
        elif page in workshop_pages:
            workshop_only.append(page)
        elif page.startswith(NON_RUNTIME_PREFIXES):
            non_runtime.append(page)
        else:
            uncovered.append(page)

    lines = ["# Scene renderer golden coverage matrix", "",
             "Generated by `tools/producer/golden/coverage_matrix.py`; do not edit by hand.", "",
             "Uncovered pages are candidates, not an execution queue. Select concrete behavior work "
             "through [WORKLIST](../../../we-official/catalog/mismatch/WORKLIST.md#active-schedule).", "",
             f"Official scene documentation pages: {len(pages)}. Fixture-covered: {len(covered)}. "
             f"Workshop-only: {len(workshop_only)}. Uncovered runtime pages: {len(uncovered)}. "
             f"Editor/publishing pages (out of scope): {len(non_runtime)}.", "",
             "## Fixture-covered pages", ""]
    for page in covered:
        lines.append(f"- `{page}` ← " + ", ".join(f"`fixture:{n}`" for n in sorted(fixture_pages[page])))
    lines += ["", "## Pages covered only through workshop wallpapers (integration level)", ""]
    for page in workshop_only:
        ids = sorted(workshop_pages[page])
        lines.append(f"- `{page}` ← {len(ids)} wallpaper(s): " + ", ".join(ids[:6]) + (" …" if len(ids) > 6 else ""))
    lines += ["", "## Uncovered runtime pages (coverage candidates)", ""]
    for page in uncovered:
        lines.append(f"- `{page}`")
    lines += ["", "## Editor / publishing pages (not renderer behavior)", ""]
    for page in non_runtime:
        lines.append(f"- `{page}`")
    lines += ["", "## Fixtures", ""]
    for name, entry in sorted(fixtures.items()):
        lines.append(f"- `fixture:{name}`: {entry.get('description', '')}")
    lines += ["", "## Workshop mechanism markers (from `golden.py init`)", ""]
    for marker in sorted(MARKER_DOCS):
        ids = sorted(marker_wallpapers.get(marker, []))
        lines.append(f"- `{marker}`: {len(ids)} wallpaper(s)")
    Path(args.output).write_text("\n".join(lines) + "\n")
    print(f"pages={len(pages)} covered={len(covered)} workshop-only={len(workshop_only)} "
          f"uncovered={len(uncovered)} non-runtime={len(non_runtime)} -> {args.output}")


if __name__ == "__main__":
    main()
