/* generated by protocol_gen.py from vivid_display_v1.toml — do not edit */

#ifndef VIVID_DISPLAY_PROTOCOL_IDS_H
#define VIVID_DISPLAY_PROTOCOL_IDS_H

#include <stddef.h>
#include <stdint.h>

#define VIVID_DISPLAY_PROTOCOL_NAME "vivid-display-v1"
#define VIVID_DISPLAY_PROTOCOL_VERSION 2u
#define VIVID_DISPLAY_PROTOCOL_MIN_SUPPORTED 1u

/*
 * Protocol version history (negotiatedVersion = min(client, producer)):
 * v1  Initial version: JSON HELLO/caps/bind + binary pointer/frame/unbind.
 * v2  Structured error codes, control requestId, caps top-level field removal, BIND JSON field convergence, display-window-state-v2, audio binary opcode.
 */

#define VIVID_DISPLAY_WINDOW_STATE_SCHEMA_V2 "display-window-state-v2"

/* per-display window flags, display-window-state-v2 */
#define VIVID_WINDOW_FLAG_NON_MINIMIZED 1u /* mapped window on display, not minimized */
#define VIVID_WINDOW_FLAG_FOCUSED 2u /* keyboard focus on this display */
#define VIVID_WINDOW_FLAG_MAXIMIZED 4u /* H+V maximized, not fullscreen */
#define VIVID_WINDOW_FLAG_FULLSCREEN 8u /* fullscreen; mutually exclusive with MAXIMIZED */
/* bits 4..31 reserved: senders must zero them; receivers must ignore them */

#define VIVID_DISPLAY_BIND_FAILED_IMPORT_FAILED        1u
#define VIVID_DISPLAY_BIND_FAILED_FRAME_REFRESH_FAILED 2u
#define VIVID_DISPLAY_BIND_FAILED_OOM                  3u
#define VIVID_DISPLAY_BIND_FAILED_OTHER                4u

#define VIVID_DISPLAY_CODEC_MAX_BODY_BYTES ((size_t)65531u)
#define VIVID_DISPLAY_CODEC_MAX_FDS_PER_MESSAGE ((size_t)64u)
#define VIVID_DISPLAY_FRAME_HEADER_BYTES 4u
#define VIVID_DISPLAY_DMABUF_MAX_PLANES 4u
#define VIVID_DISPLAY_FRAME_READY_FD_COUNT 2u
#define VIVID_DISPLAY_AUDIO_SAMPLES_BIN_MAX_COUNT 512u
#define VIVID_DISPLAY_CODEC_FRAME_DONE 1
#define VIVID_DISPLAY_CODEC_FRAME_NEED_IO 2
#define VIVID_DISPLAY_CONTROL_HEADER_BYTES 8u
#define VIVID_DISPLAY_POINTER_MOTION_BODY_BYTES 28u
#define VIVID_DISPLAY_POINTER_BUTTON_BODY_BYTES 36u
#define VIVID_DISPLAY_POINTER_AXIS_BODY_BYTES 48u
#define VIVID_DISPLAY_FRAME_READY_BODY_BYTES 36u
#define VIVID_DISPLAY_UNBIND_BODY_BYTES 12u

typedef enum
{
    VIVID_DISPLAY_OK = 0,
    VIVID_DISPLAY_ERR_INVAL = -1,
    VIVID_DISPLAY_ERR_IO = -2,
    VIVID_DISPLAY_ERR_PROTOCOL = -3,
    VIVID_DISPLAY_ERR_NO_SPACE = -4,
} VividDisplayResult;

typedef enum
{
    /* 1-99 handshake/connection, terminal (producer disconnects afterward) */
    VIVID_DISPLAY_ERR_PROTO_NAME_MISMATCH = 1,
    VIVID_DISPLAY_ERR_VERSION_UNSUPPORTED = 2,
    VIVID_DISPLAY_ERR_HELLO_REQUIRED = 3,
    VIVID_DISPLAY_ERR_DUPLICATE_HELLO = 4,
    /* 100-199 caps/negotiation, non-terminal */
    VIVID_DISPLAY_ERR_CAPS_INVALID = 100,
    VIVID_DISPLAY_ERR_CAPS_REQUIRED = 101,
    VIVID_DISPLAY_ERR_NO_DMABUF_SCHEME = 102,
    /* 200-299 output lifecycle, non-terminal */
    VIVID_DISPLAY_ERR_OUTPUT_REJECTED = 200,
    VIVID_DISPLAY_ERR_BUFFER_ALLOC_FAILED = 201,
    VIVID_DISPLAY_ERR_WINDOW_STATE_INVALID = 202,
    VIVID_DISPLAY_ERR_BIND_FAILED_INVALID = 203,
    VIVID_DISPLAY_ERR_UPDATE_OUTPUT_INVALID = 204,
    /* 300-399 control, non-terminal */
    VIVID_DISPLAY_ERR_CONTROL_MALFORMED = 300,
    VIVID_DISPLAY_ERR_CONTROL_INVALID = 301,
} VividDisplayErrorCode;

typedef enum
{
    VIVID_DISPLAY_CLIENT_CONSUMER = 1,
    VIVID_DISPLAY_CLIENT_CONTROLLER = 2,
    VIVID_DISPLAY_CLIENT_CONSUMER_AND_CONTROLLER = 3,
    VIVID_DISPLAY_CLIENT_PRODUCER = 4,
    VIVID_DISPLAY_CLIENT_DISPLAY = VIVID_DISPLAY_CLIENT_CONSUMER,
    VIVID_DISPLAY_CLIENT_DISPLAY_AND_CONTROLLER = VIVID_DISPLAY_CLIENT_CONSUMER_AND_CONTROLLER,
} VividDisplayClientRole;

typedef enum
{
    VIVID_DISPLAY_REQ_HELLO = 1,
    VIVID_DISPLAY_REQ_REGISTER_OUTPUT = 2,
    VIVID_DISPLAY_REQ_UPDATE_OUTPUT = 3,
    VIVID_DISPLAY_REQ_CONSUMER_CAPS = 4,
    VIVID_DISPLAY_REQ_BYE = 5,
    VIVID_DISPLAY_REQ_POINTER_MOTION = 7,
    VIVID_DISPLAY_REQ_POINTER_BUTTON = 8,
    VIVID_DISPLAY_REQ_POINTER_AXIS = 9,
    /*
     * REQ_WINDOW_STATE carries schema "display-window-state-v2".
     *
     * Payload: { "schema", "source", "displays": { "<displayKey>": { "flags" } },
     *            "session": { ... } }
     *
     * displayKey is the persistent identity registered via REGISTER_OUTPUT.
     * flags use VIVID_WINDOW_FLAG_*; MAXIMIZED and FULLSCREEN are mutually exclusive.
     *
     * session carries global facts (onBattery, mprisPlaying, windows[], ...) used
     * by application rules. Identity model: displayKey = persistence key;
     * outputId = daemon session key; monitorIndex = per-connection transport coordinate.
     */
    VIVID_DISPLAY_REQ_WINDOW_STATE = 10,
    VIVID_DISPLAY_REQ_CONTROL = 11,
    VIVID_DISPLAY_REQ_MEDIA_STATE = 12,
    VIVID_DISPLAY_REQ_AUDIO_SAMPLES = 13, /* reserved; v2 uses AUDIO_SAMPLES_BIN */
    VIVID_DISPLAY_REQ_BIND_FAILED = 14,
    VIVID_DISPLAY_REQ_UNBIND_DONE = 15,
    /*
     * v2 binary audio samples (negotiatedVersion >= 2):
     * body: u32le count (<=512) + u64le timeUsec + count * f32le sample in [0,1]
     */
    VIVID_DISPLAY_REQ_AUDIO_SAMPLES_BIN = 16,
} VividDisplayRequestOpcode;

typedef enum
{
    VIVID_DISPLAY_EVT_WELCOME = 1,
    VIVID_DISPLAY_EVT_OUTPUT_ACCEPTED = 2,
    VIVID_DISPLAY_EVT_BIND_BUFFERS = 3,
    VIVID_DISPLAY_EVT_SET_CONFIG = 4,
    VIVID_DISPLAY_EVT_FRAME_READY = 5,
    VIVID_DISPLAY_EVT_UNBIND = 6,
    VIVID_DISPLAY_EVT_CONTROL = 7,
    VIVID_DISPLAY_EVT_AUDIO_FRAME = 8,
    VIVID_DISPLAY_EVT_ERROR = 9,
} VividDisplayEventOpcode;

typedef enum
{
    VIVID_DISPLAY_CONTROL_GET_STATE = 1,
    VIVID_DISPLAY_CONTROL_STATE_SNAPSHOT = 2,
    VIVID_DISPLAY_CONTROL_SET_PLAYING = 4,
    VIVID_DISPLAY_CONTROL_SET_MUTED = 5,
    VIVID_DISPLAY_CONTROL_SET_VOLUME = 6,
    VIVID_DISPLAY_CONTROL_SET_CONTENT_FIT = 7,
    VIVID_DISPLAY_CONTROL_SET_SCENE_FPS = 8,
    VIVID_DISPLAY_CONTROL_OPEN_SETTINGS = 10,
    VIVID_DISPLAY_CONTROL_ACK = 11,
    VIVID_DISPLAY_CONTROL_ERROR = 12,
    VIVID_DISPLAY_CONTROL_SET_STATE = 13,
} VividDisplayControlOpcode;

typedef enum
{
    VIVID_DISPLAY_BUTTON_RELEASED = 0,
    VIVID_DISPLAY_BUTTON_PRESSED = 1,
} VividDisplayButtonState;

typedef enum
{
    VIVID_DISPLAY_AXIS_WHEEL = 0,
    VIVID_DISPLAY_AXIS_FINGER = 1,
    VIVID_DISPLAY_AXIS_CONTINUOUS = 2,
} VividDisplayAxisSource;

#include <string.h>

static inline void vivid_display_codec_write_u16(uint8_t* out, uint16_t value)
{
    out[0] = (uint8_t)(value & 0xffu);
    out[1] = (uint8_t)((value >> 8) & 0xffu);
}

static inline uint16_t vivid_display_codec_read_u16(const uint8_t* in)
{
    return (uint16_t)in[0] | ((uint16_t)in[1] << 8);
}

static inline void vivid_display_codec_write_u32(uint8_t* out, uint32_t value)
{
    out[0] = (uint8_t)(value & 0xffu);
    out[1] = (uint8_t)((value >> 8) & 0xffu);
    out[2] = (uint8_t)((value >> 16) & 0xffu);
    out[3] = (uint8_t)((value >> 24) & 0xffu);
}

static inline uint32_t vivid_display_codec_read_u32(const uint8_t* in)
{
    return (uint32_t)in[0] | ((uint32_t)in[1] << 8) | ((uint32_t)in[2] << 16) |
           ((uint32_t)in[3] << 24);
}

static inline void vivid_display_codec_write_u64(uint8_t* out, uint64_t value)
{
    vivid_display_codec_write_u32(out, (uint32_t)(value & 0xffffffffu));
    vivid_display_codec_write_u32(out + 4, (uint32_t)(value >> 32));
}

static inline uint64_t vivid_display_codec_read_u64(const uint8_t* in)
{
    return (uint64_t)vivid_display_codec_read_u32(in) |
           ((uint64_t)vivid_display_codec_read_u32(in + 4) << 32);
}

static inline void vivid_display_codec_write_f32(uint8_t* out, float value)
{
    uint32_t bits = 0;
    memcpy(&bits, &value, sizeof(bits));
    vivid_display_codec_write_u32(out, bits);
}

static inline float vivid_display_codec_read_f32(const uint8_t* in)
{
    float value = 0.f;
    uint32_t bits = vivid_display_codec_read_u32(in);
    memcpy(&value, &bits, sizeof(value));
    return value;
}

static inline void vivid_display_codec_write_f64(uint8_t* out, double value)
{
    uint64_t bits = 0;
    memcpy(&bits, &value, sizeof(bits));
    vivid_display_codec_write_u64(out, bits);
}

static inline double vivid_display_codec_read_f64(const uint8_t* in)
{
    double value = 0.0;
    uint64_t bits = vivid_display_codec_read_u64(in);
    memcpy(&value, &bits, sizeof(value));
    return value;
}

static inline void vivid_display_control_header_body_write(uint8_t out[VIVID_DISPLAY_CONTROL_HEADER_BYTES], uint16_t opcode, uint16_t flags, uint32_t json_length)
{
    vivid_display_codec_write_u16(out + 0, opcode);
    vivid_display_codec_write_u16(out + 2, flags);
    vivid_display_codec_write_u32(out + 4, json_length);
}

static inline int vivid_display_control_header_body_read(const uint8_t* data, size_t len, uint16_t* opcode, uint16_t* flags, uint32_t* json_length)
{
    if (!data || len < VIVID_DISPLAY_CONTROL_HEADER_BYTES)
        return -1;
    *(opcode) = vivid_display_codec_read_u16(data + 0);
    *(flags) = vivid_display_codec_read_u16(data + 2);
    *(json_length) = vivid_display_codec_read_u32(data + 4);
    return 0;
}

static inline void vivid_display_pointer_motion_body_write(uint8_t out[VIVID_DISPLAY_POINTER_MOTION_BODY_BYTES], uint32_t output_id, double x, double y, uint64_t time_usec)
{
    vivid_display_codec_write_u32(out + 0, output_id);
    vivid_display_codec_write_f64(out + 4, x);
    vivid_display_codec_write_f64(out + 12, y);
    vivid_display_codec_write_u64(out + 20, time_usec);
}

static inline int vivid_display_pointer_motion_body_read(const uint8_t* data, size_t len, uint32_t* output_id, double* x, double* y, uint64_t* time_usec)
{
    if (!data || len < VIVID_DISPLAY_POINTER_MOTION_BODY_BYTES)
        return -1;
    *(output_id) = vivid_display_codec_read_u32(data + 0);
    *(x) = vivid_display_codec_read_f64(data + 4);
    *(y) = vivid_display_codec_read_f64(data + 12);
    *(time_usec) = vivid_display_codec_read_u64(data + 20);
    return 0;
}

static inline void vivid_display_pointer_button_body_write(uint8_t out[VIVID_DISPLAY_POINTER_BUTTON_BODY_BYTES], uint32_t output_id, double x, double y, uint32_t button, uint32_t state, uint64_t time_usec)
{
    vivid_display_codec_write_u32(out + 0, output_id);
    vivid_display_codec_write_f64(out + 4, x);
    vivid_display_codec_write_f64(out + 12, y);
    vivid_display_codec_write_u32(out + 20, button);
    vivid_display_codec_write_u32(out + 24, state);
    vivid_display_codec_write_u64(out + 28, time_usec);
}

static inline int vivid_display_pointer_button_body_read(const uint8_t* data, size_t len, uint32_t* output_id, double* x, double* y, uint32_t* button, uint32_t* state, uint64_t* time_usec)
{
    if (!data || len < VIVID_DISPLAY_POINTER_BUTTON_BODY_BYTES)
        return -1;
    *(output_id) = vivid_display_codec_read_u32(data + 0);
    *(x) = vivid_display_codec_read_f64(data + 4);
    *(y) = vivid_display_codec_read_f64(data + 12);
    *(button) = vivid_display_codec_read_u32(data + 20);
    *(state) = vivid_display_codec_read_u32(data + 24);
    *(time_usec) = vivid_display_codec_read_u64(data + 28);
    return 0;
}

static inline void vivid_display_pointer_axis_body_write(uint8_t out[VIVID_DISPLAY_POINTER_AXIS_BODY_BYTES], uint32_t output_id, double x, double y, double delta_x, double delta_y, uint32_t source, uint64_t time_usec)
{
    vivid_display_codec_write_u32(out + 0, output_id);
    vivid_display_codec_write_f64(out + 4, x);
    vivid_display_codec_write_f64(out + 12, y);
    vivid_display_codec_write_f64(out + 20, delta_x);
    vivid_display_codec_write_f64(out + 28, delta_y);
    vivid_display_codec_write_u32(out + 36, source);
    vivid_display_codec_write_u64(out + 40, time_usec);
}

static inline int vivid_display_pointer_axis_body_read(const uint8_t* data, size_t len, uint32_t* output_id, double* x, double* y, double* delta_x, double* delta_y, uint32_t* source, uint64_t* time_usec)
{
    if (!data || len < VIVID_DISPLAY_POINTER_AXIS_BODY_BYTES)
        return -1;
    *(output_id) = vivid_display_codec_read_u32(data + 0);
    *(x) = vivid_display_codec_read_f64(data + 4);
    *(y) = vivid_display_codec_read_f64(data + 12);
    *(delta_x) = vivid_display_codec_read_f64(data + 20);
    *(delta_y) = vivid_display_codec_read_f64(data + 28);
    *(source) = vivid_display_codec_read_u32(data + 36);
    *(time_usec) = vivid_display_codec_read_u64(data + 40);
    return 0;
}

static inline void vivid_display_frame_ready_body_write(uint8_t out[VIVID_DISPLAY_FRAME_READY_BODY_BYTES], uint32_t output_id, uint64_t generation, uint32_t buffer_index, uint64_t sequence, uint64_t target_time_usec, uint32_t flags)
{
    vivid_display_codec_write_u32(out + 0, output_id);
    vivid_display_codec_write_u64(out + 4, generation);
    vivid_display_codec_write_u32(out + 12, buffer_index);
    vivid_display_codec_write_u64(out + 16, sequence);
    vivid_display_codec_write_u64(out + 24, target_time_usec);
    vivid_display_codec_write_u32(out + 32, flags);
}

static inline int vivid_display_frame_ready_body_read(const uint8_t* data, size_t len, uint32_t* output_id, uint64_t* generation, uint32_t* buffer_index, uint64_t* sequence, uint64_t* target_time_usec, uint32_t* flags)
{
    if (!data || len < VIVID_DISPLAY_FRAME_READY_BODY_BYTES)
        return -1;
    *(output_id) = vivid_display_codec_read_u32(data + 0);
    *(generation) = vivid_display_codec_read_u64(data + 4);
    *(buffer_index) = vivid_display_codec_read_u32(data + 12);
    *(sequence) = vivid_display_codec_read_u64(data + 16);
    *(target_time_usec) = vivid_display_codec_read_u64(data + 24);
    *(flags) = vivid_display_codec_read_u32(data + 32);
    return 0;
}

static inline void vivid_display_unbind_body_write(uint8_t out[VIVID_DISPLAY_UNBIND_BODY_BYTES], uint32_t output_id, uint64_t generation)
{
    vivid_display_codec_write_u32(out + 0, output_id);
    vivid_display_codec_write_u64(out + 4, generation);
}

static inline int vivid_display_unbind_body_read(const uint8_t* data, size_t len, uint32_t* output_id, uint64_t* generation)
{
    if (!data || len < VIVID_DISPLAY_UNBIND_BODY_BYTES)
        return -1;
    *(output_id) = vivid_display_codec_read_u32(data + 0);
    *(generation) = vivid_display_codec_read_u64(data + 4);
    return 0;
}

static inline size_t vivid_display_audio_samples_bin_body_bytes(uint32_t count)
{
    return 12u + (size_t)count * sizeof(float);
}

static inline int vivid_display_audio_samples_bin_body_write(
    uint8_t* out,
    size_t out_cap,
    uint32_t count,
    uint64_t time_usec,
    const float* samples)
{
    if (!out || !samples || count == 0 || count > VIVID_DISPLAY_AUDIO_SAMPLES_BIN_MAX_COUNT)
        return -1;
    const size_t need = vivid_display_audio_samples_bin_body_bytes(count);
    if (out_cap < need)
        return -1;
    vivid_display_codec_write_u32(out, count);
    vivid_display_codec_write_u64(out + 4, time_usec);
    for (uint32_t i = 0; i < count; i++)
        vivid_display_codec_write_f32(out + 12 + (size_t)i * sizeof(float), samples[i]);
    return (int)need;
}

static inline int vivid_display_audio_samples_bin_body_read(
    const uint8_t* data,
    size_t len,
    uint32_t* count,
    uint64_t* time_usec,
    float* samples,
    size_t samples_cap)
{
    if (!data || !count || !time_usec || !samples || len < 12)
        return -1;
    *count = vivid_display_codec_read_u32(data);
    if (*count == 0 || *count > VIVID_DISPLAY_AUDIO_SAMPLES_BIN_MAX_COUNT)
        return -1;
    const size_t need = vivid_display_audio_samples_bin_body_bytes(*count);
    if (len < need || samples_cap < *count)
        return -1;
    *time_usec = vivid_display_codec_read_u64(data + 4);
    for (uint32_t i = 0; i < *count; i++)
        samples[i] = vivid_display_codec_read_f32(data + 12 + (size_t)i * sizeof(float));
    return (int)need;
}


#include <stdbool.h>

static inline const char* vivid_display_error_name(int code)
{
    switch (code) {
    case VIVID_DISPLAY_ERR_PROTO_NAME_MISMATCH: return "PROTO_NAME_MISMATCH";
    case VIVID_DISPLAY_ERR_VERSION_UNSUPPORTED: return "VERSION_UNSUPPORTED";
    case VIVID_DISPLAY_ERR_HELLO_REQUIRED: return "HELLO_REQUIRED";
    case VIVID_DISPLAY_ERR_DUPLICATE_HELLO: return "DUPLICATE_HELLO";
    case VIVID_DISPLAY_ERR_CAPS_INVALID: return "CAPS_INVALID";
    case VIVID_DISPLAY_ERR_CAPS_REQUIRED: return "CAPS_REQUIRED";
    case VIVID_DISPLAY_ERR_NO_DMABUF_SCHEME: return "NO_DMABUF_SCHEME";
    case VIVID_DISPLAY_ERR_OUTPUT_REJECTED: return "OUTPUT_REJECTED";
    case VIVID_DISPLAY_ERR_BUFFER_ALLOC_FAILED: return "BUFFER_ALLOC_FAILED";
    case VIVID_DISPLAY_ERR_WINDOW_STATE_INVALID: return "WINDOW_STATE_INVALID";
    case VIVID_DISPLAY_ERR_BIND_FAILED_INVALID: return "BIND_FAILED_INVALID";
    case VIVID_DISPLAY_ERR_UPDATE_OUTPUT_INVALID: return "UPDATE_OUTPUT_INVALID";
    case VIVID_DISPLAY_ERR_CONTROL_MALFORMED: return "CONTROL_MALFORMED";
    case VIVID_DISPLAY_ERR_CONTROL_INVALID: return "CONTROL_INVALID";
    default: return NULL;
    }
}

static inline bool vivid_display_error_terminal(int code)
{
    switch (code) {
    case VIVID_DISPLAY_ERR_PROTO_NAME_MISMATCH: return true;
    case VIVID_DISPLAY_ERR_VERSION_UNSUPPORTED: return true;
    case VIVID_DISPLAY_ERR_HELLO_REQUIRED: return true;
    case VIVID_DISPLAY_ERR_DUPLICATE_HELLO: return true;
    default: return false;
    }
}

static inline const char* vivid_display_error_domain(int code)
{
    switch (code) {
    case VIVID_DISPLAY_ERR_PROTO_NAME_MISMATCH: return "handshake";
    case VIVID_DISPLAY_ERR_VERSION_UNSUPPORTED: return "handshake";
    case VIVID_DISPLAY_ERR_HELLO_REQUIRED: return "handshake";
    case VIVID_DISPLAY_ERR_DUPLICATE_HELLO: return "handshake";
    case VIVID_DISPLAY_ERR_CAPS_INVALID: return "caps";
    case VIVID_DISPLAY_ERR_CAPS_REQUIRED: return "caps";
    case VIVID_DISPLAY_ERR_NO_DMABUF_SCHEME: return "caps";
    case VIVID_DISPLAY_ERR_OUTPUT_REJECTED: return "output";
    case VIVID_DISPLAY_ERR_BUFFER_ALLOC_FAILED: return "output";
    case VIVID_DISPLAY_ERR_WINDOW_STATE_INVALID: return "output";
    case VIVID_DISPLAY_ERR_BIND_FAILED_INVALID: return "output";
    case VIVID_DISPLAY_ERR_UPDATE_OUTPUT_INVALID: return "output";
    case VIVID_DISPLAY_ERR_CONTROL_MALFORMED: return "control";
    case VIVID_DISPLAY_ERR_CONTROL_INVALID: return "control";
    default: return "unknown";
    }
}

static inline const char* vivid_display_bind_failed_reason_name(uint32_t reason)
{
    switch (reason) {
    case VIVID_DISPLAY_BIND_FAILED_IMPORT_FAILED: return "IMPORT_FAILED";
    case VIVID_DISPLAY_BIND_FAILED_FRAME_REFRESH_FAILED: return "FRAME_REFRESH_FAILED";
    case VIVID_DISPLAY_BIND_FAILED_OOM: return "OOM";
    case VIVID_DISPLAY_BIND_FAILED_OTHER: return "OTHER";
    default: return NULL;
    }
}

static inline const char* vivid_display_window_flag_name(uint32_t flag)
{
    switch (flag) {
    case VIVID_WINDOW_FLAG_NON_MINIMIZED: return "NON_MINIMIZED";
    case VIVID_WINDOW_FLAG_FOCUSED: return "FOCUSED";
    case VIVID_WINDOW_FLAG_MAXIMIZED: return "MAXIMIZED";
    case VIVID_WINDOW_FLAG_FULLSCREEN: return "FULLSCREEN";
    default: return NULL;
    }
}

static inline const char* vivid_display_client_role_name(uint32_t role)
{
    switch (role) {
    case VIVID_DISPLAY_CLIENT_CONSUMER: return "CONSUMER";
    case VIVID_DISPLAY_CLIENT_CONTROLLER: return "CONTROLLER";
    case VIVID_DISPLAY_CLIENT_CONSUMER_AND_CONTROLLER: return "CONSUMER_AND_CONTROLLER";
    case VIVID_DISPLAY_CLIENT_PRODUCER: return "PRODUCER";
    default: return NULL;
    }
}

static inline uint32_t vivid_display_request_min_version(uint16_t opcode)
{
    switch (opcode) {
    case VIVID_DISPLAY_REQ_AUDIO_SAMPLES_BIN: return 2u;
    default: return VIVID_DISPLAY_PROTOCOL_MIN_SUPPORTED;
    }
}


#endif
