/* generated by protocol_gen.py from vivid_display_v1.toml — do not edit */

#pragma once

#include "vivid_protocol_constants.hpp"

#include <string_view>

namespace vivid::protocol {

inline constexpr std::string_view error_name(int code) noexcept
{
    switch (code) {
    case VIVID_DISPLAY_ERR_PROTO_NAME_MISMATCH: return "PROTO_NAME_MISMATCH";
    case VIVID_DISPLAY_ERR_VERSION_UNSUPPORTED: return "VERSION_UNSUPPORTED";
    case VIVID_DISPLAY_ERR_HELLO_REQUIRED: return "HELLO_REQUIRED";
    case VIVID_DISPLAY_ERR_DUPLICATE_HELLO: return "DUPLICATE_HELLO";
    case VIVID_DISPLAY_ERR_CAPS_INVALID: return "CAPS_INVALID";
    case VIVID_DISPLAY_ERR_CAPS_REQUIRED: return "CAPS_REQUIRED";
    case VIVID_DISPLAY_ERR_NO_DMABUF_SCHEME: return "NO_DMABUF_SCHEME";
    case VIVID_DISPLAY_ERR_OUTPUT_REJECTED: return "OUTPUT_REJECTED";
    case VIVID_DISPLAY_ERR_BUFFER_ALLOC_FAILED: return "BUFFER_ALLOC_FAILED";
    case VIVID_DISPLAY_ERR_WINDOW_STATE_INVALID: return "WINDOW_STATE_INVALID";
    case VIVID_DISPLAY_ERR_BIND_FAILED_INVALID: return "BIND_FAILED_INVALID";
    case VIVID_DISPLAY_ERR_UPDATE_OUTPUT_INVALID: return "UPDATE_OUTPUT_INVALID";
    case VIVID_DISPLAY_ERR_CONTROL_MALFORMED: return "CONTROL_MALFORMED";
    case VIVID_DISPLAY_ERR_CONTROL_INVALID: return "CONTROL_INVALID";
    default: return "UNKNOWN";
    }
}

inline constexpr bool error_is_terminal(int code) noexcept
{
    switch (code) {
    case VIVID_DISPLAY_ERR_PROTO_NAME_MISMATCH: return true;
    case VIVID_DISPLAY_ERR_VERSION_UNSUPPORTED: return true;
    case VIVID_DISPLAY_ERR_HELLO_REQUIRED: return true;
    case VIVID_DISPLAY_ERR_DUPLICATE_HELLO: return true;
    default: return false;
    }
}

inline constexpr std::string_view error_domain(int code) noexcept
{
    switch (code) {
    case VIVID_DISPLAY_ERR_PROTO_NAME_MISMATCH: return "handshake";
    case VIVID_DISPLAY_ERR_VERSION_UNSUPPORTED: return "handshake";
    case VIVID_DISPLAY_ERR_HELLO_REQUIRED: return "handshake";
    case VIVID_DISPLAY_ERR_DUPLICATE_HELLO: return "handshake";
    case VIVID_DISPLAY_ERR_CAPS_INVALID: return "caps";
    case VIVID_DISPLAY_ERR_CAPS_REQUIRED: return "caps";
    case VIVID_DISPLAY_ERR_NO_DMABUF_SCHEME: return "caps";
    case VIVID_DISPLAY_ERR_OUTPUT_REJECTED: return "output";
    case VIVID_DISPLAY_ERR_BUFFER_ALLOC_FAILED: return "output";
    case VIVID_DISPLAY_ERR_WINDOW_STATE_INVALID: return "output";
    case VIVID_DISPLAY_ERR_BIND_FAILED_INVALID: return "output";
    case VIVID_DISPLAY_ERR_UPDATE_OUTPUT_INVALID: return "output";
    case VIVID_DISPLAY_ERR_CONTROL_MALFORMED: return "control";
    case VIVID_DISPLAY_ERR_CONTROL_INVALID: return "control";
    default: return "unknown";
    }
}

inline constexpr std::string_view bind_failed_reason_name(std::uint32_t reason) noexcept
{
    switch (reason) {
    case VIVID_DISPLAY_BIND_FAILED_IMPORT_FAILED: return "IMPORT_FAILED";
    case VIVID_DISPLAY_BIND_FAILED_FRAME_REFRESH_FAILED: return "FRAME_REFRESH_FAILED";
    case VIVID_DISPLAY_BIND_FAILED_OOM: return "OOM";
    case VIVID_DISPLAY_BIND_FAILED_OTHER: return "OTHER";
    default: return "UNKNOWN";
    }
}

inline constexpr std::string_view window_flag_name(std::uint32_t flag) noexcept
{
    switch (flag) {
    case VIVID_WINDOW_FLAG_NON_MINIMIZED: return "NON_MINIMIZED";
    case VIVID_WINDOW_FLAG_FOCUSED: return "FOCUSED";
    case VIVID_WINDOW_FLAG_MAXIMIZED: return "MAXIMIZED";
    case VIVID_WINDOW_FLAG_FULLSCREEN: return "FULLSCREEN";
    default: return "UNKNOWN";
    }
}

inline constexpr std::string_view client_role_name(std::uint32_t role) noexcept
{
    switch (role) {
    case VIVID_DISPLAY_CLIENT_CONSUMER: return "CONSUMER";
    case VIVID_DISPLAY_CLIENT_CONTROLLER: return "CONTROLLER";
    case VIVID_DISPLAY_CLIENT_CONSUMER_AND_CONTROLLER: return "CONSUMER_AND_CONTROLLER";
    case VIVID_DISPLAY_CLIENT_PRODUCER: return "PRODUCER";
    default: return "UNKNOWN";
    }
}

inline constexpr std::uint32_t message_min_version(std::string_view key) noexcept
{
    if (key == "AUDIO_SAMPLES_BIN") return 2u;
    return VIVID_DISPLAY_PROTOCOL_MIN_SUPPORTED;
}

}  // namespace vivid::protocol
