/* generated by protocol_gen.py from vivid_display_v1.toml — do not edit */

#pragma once

#include <cstdint>

namespace vivid::protocol {

inline constexpr std::uint32_t VIVID_DISPLAY_AUDIO_SAMPLES_BIN_MAX_COUNT = 128u;
inline constexpr std::uint32_t VIVID_DISPLAY_AXIS_CONTINUOUS = 2u;
inline constexpr std::uint32_t VIVID_DISPLAY_AXIS_FINGER = 1u;
inline constexpr std::uint32_t VIVID_DISPLAY_AXIS_WHEEL = 0u;
inline constexpr std::uint32_t VIVID_DISPLAY_BIND_FAILED_FRAME_REFRESH_FAILED = 2u;
inline constexpr std::uint32_t VIVID_DISPLAY_BIND_FAILED_IMPORT_FAILED = 1u;
inline constexpr std::uint32_t VIVID_DISPLAY_BIND_FAILED_OOM = 3u;
inline constexpr std::uint32_t VIVID_DISPLAY_BIND_FAILED_OTHER = 4u;
inline constexpr std::uint32_t VIVID_DISPLAY_BUTTON_PRESSED = 1u;
inline constexpr std::uint32_t VIVID_DISPLAY_BUTTON_RELEASED = 0u;
inline constexpr std::uint32_t VIVID_DISPLAY_CLIENT_CONSUMER = 1u;
inline constexpr std::uint32_t VIVID_DISPLAY_CLIENT_CONSUMER_AND_CONTROLLER = 3u;
inline constexpr std::uint32_t VIVID_DISPLAY_CLIENT_CONTROLLER = 2u;
inline constexpr std::uint32_t VIVID_DISPLAY_CLIENT_DISPLAY = 1u;
inline constexpr std::uint32_t VIVID_DISPLAY_CLIENT_DISPLAY_AND_CONTROLLER = 3u;
inline constexpr std::uint32_t VIVID_DISPLAY_CLIENT_PRODUCER = 4u;
inline constexpr std::uint32_t VIVID_DISPLAY_CODEC_FRAME_DONE = 1u;
inline constexpr std::uint32_t VIVID_DISPLAY_CODEC_FRAME_NEED_IO = 2u;
inline constexpr std::uint32_t VIVID_DISPLAY_CODEC_MAX_BODY_BYTES = 65531u;
inline constexpr std::uint32_t VIVID_DISPLAY_CODEC_MAX_FDS_PER_MESSAGE = 64u;
inline constexpr std::uint32_t VIVID_DISPLAY_CONTROL_ACK = 11u;
inline constexpr std::uint32_t VIVID_DISPLAY_CONTROL_ERROR = 12u;
inline constexpr std::uint32_t VIVID_DISPLAY_CONTROL_GET_STATE = 1u;
inline constexpr std::uint32_t VIVID_DISPLAY_CONTROL_HEADER_BYTES = 8u;
inline constexpr std::uint32_t VIVID_DISPLAY_CONTROL_OPEN_SETTINGS = 10u;
inline constexpr std::uint32_t VIVID_DISPLAY_CONTROL_SET_CONTENT_FIT = 7u;
inline constexpr std::uint32_t VIVID_DISPLAY_CONTROL_SET_MUTED = 5u;
inline constexpr std::uint32_t VIVID_DISPLAY_CONTROL_SET_PLAYING = 4u;
inline constexpr std::uint32_t VIVID_DISPLAY_CONTROL_SET_SCENE_FPS = 8u;
inline constexpr std::uint32_t VIVID_DISPLAY_CONTROL_SET_STATE = 13u;
inline constexpr std::uint32_t VIVID_DISPLAY_CONTROL_SET_VOLUME = 6u;
inline constexpr std::uint32_t VIVID_DISPLAY_CONTROL_STATE_SNAPSHOT = 2u;
inline constexpr std::uint32_t VIVID_DISPLAY_DMABUF_MAX_PLANES = 4u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_BIND_FAILED_INVALID = 203u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_BUFFER_ALLOC_FAILED = 201u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_CAPS_INVALID = 100u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_CAPS_REQUIRED = 101u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_CONTROL_INVALID = 301u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_CONTROL_MALFORMED = 300u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_DUPLICATE_HELLO = 4u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_HELLO_REQUIRED = 3u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_INVAL = -1u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_IO = -2u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_NO_DMABUF_SCHEME = 102u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_NO_SPACE = -4u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_OUTPUT_REJECTED = 200u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_PROTOCOL = -3u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_PROTO_NAME_MISMATCH = 1u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_UPDATE_OUTPUT_INVALID = 204u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_VERSION_UNSUPPORTED = 2u;
inline constexpr std::uint32_t VIVID_DISPLAY_ERR_WINDOW_STATE_INVALID = 202u;
inline constexpr std::uint32_t VIVID_DISPLAY_EVT_AUDIO_FRAME = 8u;
inline constexpr std::uint32_t VIVID_DISPLAY_EVT_BIND_BUFFERS = 3u;
inline constexpr std::uint32_t VIVID_DISPLAY_EVT_CONTROL = 7u;
inline constexpr std::uint32_t VIVID_DISPLAY_EVT_ERROR = 9u;
inline constexpr std::uint32_t VIVID_DISPLAY_EVT_FRAME_READY = 5u;
inline constexpr std::uint32_t VIVID_DISPLAY_EVT_OUTPUT_ACCEPTED = 2u;
inline constexpr std::uint32_t VIVID_DISPLAY_EVT_SET_CONFIG = 4u;
inline constexpr std::uint32_t VIVID_DISPLAY_EVT_UNBIND = 6u;
inline constexpr std::uint32_t VIVID_DISPLAY_EVT_WELCOME = 1u;
inline constexpr std::uint32_t VIVID_DISPLAY_FRAME_HEADER_BYTES = 4u;
inline constexpr std::uint32_t VIVID_DISPLAY_FRAME_READY_BODY_BYTES = 36u;
inline constexpr std::uint32_t VIVID_DISPLAY_FRAME_READY_FD_COUNT = 2u;
inline constexpr std::uint32_t VIVID_DISPLAY_OK = 0u;
inline constexpr std::uint32_t VIVID_DISPLAY_POINTER_AXIS_BODY_BYTES = 48u;
inline constexpr std::uint32_t VIVID_DISPLAY_POINTER_BUTTON_BODY_BYTES = 36u;
inline constexpr std::uint32_t VIVID_DISPLAY_POINTER_MOTION_BODY_BYTES = 28u;
inline constexpr std::uint32_t VIVID_DISPLAY_PROTOCOL_MIN_SUPPORTED = 1u;
inline constexpr char VIVID_DISPLAY_PROTOCOL_NAME[] = "vivid-display-v1";
inline constexpr std::uint32_t VIVID_DISPLAY_PROTOCOL_VERSION = 2u;
inline constexpr std::uint32_t VIVID_DISPLAY_REQ_AUDIO_SAMPLES = 13u;
inline constexpr std::uint32_t VIVID_DISPLAY_REQ_AUDIO_SAMPLES_BIN = 16u;
inline constexpr std::uint32_t VIVID_DISPLAY_REQ_BIND_FAILED = 14u;
inline constexpr std::uint32_t VIVID_DISPLAY_REQ_BYE = 5u;
inline constexpr std::uint32_t VIVID_DISPLAY_REQ_CONSUMER_CAPS = 4u;
inline constexpr std::uint32_t VIVID_DISPLAY_REQ_CONTROL = 11u;
inline constexpr std::uint32_t VIVID_DISPLAY_REQ_HELLO = 1u;
inline constexpr std::uint32_t VIVID_DISPLAY_REQ_MEDIA_STATE = 12u;
inline constexpr std::uint32_t VIVID_DISPLAY_REQ_POINTER_AXIS = 9u;
inline constexpr std::uint32_t VIVID_DISPLAY_REQ_POINTER_BUTTON = 8u;
inline constexpr std::uint32_t VIVID_DISPLAY_REQ_POINTER_MOTION = 7u;
inline constexpr std::uint32_t VIVID_DISPLAY_REQ_REGISTER_OUTPUT = 2u;
inline constexpr std::uint32_t VIVID_DISPLAY_REQ_UNBIND_DONE = 15u;
inline constexpr std::uint32_t VIVID_DISPLAY_REQ_UPDATE_OUTPUT = 3u;
inline constexpr std::uint32_t VIVID_DISPLAY_REQ_WINDOW_STATE = 10u;
inline constexpr std::uint32_t VIVID_DISPLAY_UNBIND_BODY_BYTES = 12u;
inline constexpr char VIVID_DISPLAY_WINDOW_STATE_SCHEMA_V2[] = "display-window-state-v2";
inline constexpr std::uint32_t VIVID_WINDOW_FLAG_FOCUSED = 2u;
inline constexpr std::uint32_t VIVID_WINDOW_FLAG_FULLSCREEN = 8u;
inline constexpr std::uint32_t VIVID_WINDOW_FLAG_MAXIMIZED = 4u;
inline constexpr std::uint32_t VIVID_WINDOW_FLAG_NON_MINIMIZED = 1u;

}  // namespace vivid::protocol
