/* generated by protocol_gen.py from vivid_display_v1.toml — do not edit */

#pragma once

#include <QString>

namespace vivid::protocol {

struct BIND_BUFFERS {
    static inline const QString buffers{QStringLiteral("buffers")};
    static inline const QString consumerBackend{QStringLiteral("consumerBackend")};
    static inline const QString consumerDeviceUuid{QStringLiteral("consumerDeviceUuid")};
    static inline const QString consumerDriverUuid{QStringLiteral("consumerDriverUuid")};
    static inline const QString consumerDrmRenderMajor{QStringLiteral("consumerDrmRenderMajor")};
    static inline const QString consumerDrmRenderMinor{QStringLiteral("consumerDrmRenderMinor")};
    static inline const QString consumerIdentityMode{QStringLiteral("consumerIdentityMode")};
    static inline const QString consumerRenderNode{QStringLiteral("consumerRenderNode")};
    static inline const QString format{QStringLiteral("format")};
    static inline const QString fourcc{QStringLiteral("fourcc")};
    static inline const QString generation{QStringLiteral("generation")};
    static inline const QString height{QStringLiteral("height")};
    static inline const QString logicalHeight{QStringLiteral("logicalHeight")};
    static inline const QString logicalWidth{QStringLiteral("logicalWidth")};
    static inline const QString memoryHint{QStringLiteral("memoryHint")};
    static inline const QString memorySource{QStringLiteral("memorySource")};
    static inline const QString memoryType{QStringLiteral("memoryType")};
    static inline const QString modifier{QStringLiteral("modifier")};
    static inline const QString negotiatedPath{QStringLiteral("negotiatedPath")};
    static inline const QString outputId{QStringLiteral("outputId")};
    static inline const QString planesPerBuffer{QStringLiteral("planesPerBuffer")};
    static inline const QString premultiplied{QStringLiteral("premultiplied")};
    static inline const QString presentationPath{QStringLiteral("presentationPath")};
    static inline const QString producerDeviceUuid{QStringLiteral("producerDeviceUuid")};
    static inline const QString producerDriverUuid{QStringLiteral("producerDriverUuid")};
    static inline const QString producerDrmRenderMajor{QStringLiteral("producerDrmRenderMajor")};
    static inline const QString producerDrmRenderMinor{QStringLiteral("producerDrmRenderMinor")};
    static inline const QString producerPciAddress{QStringLiteral("producerPciAddress")};
    static inline const QString producerRenderNode{QStringLiteral("producerRenderNode")};
    static inline const QString producerVendor{QStringLiteral("producerVendor")};
    static inline const QString refreshRateMhz{QStringLiteral("refreshRateMhz")};
    static inline const QString renderNode{QStringLiteral("render-node")};
    static inline const QString scale{QStringLiteral("scale")};
    static inline const QString syncMode{QStringLiteral("syncMode")};
    static inline const QString width{QStringLiteral("width")};
};

struct BIND_BUFFERS_BUFFER {
    static inline const QString index{QStringLiteral("index")};
    static inline const QString planes{QStringLiteral("planes")};
    static inline const QString size{QStringLiteral("size")};
};

struct BIND_BUFFERS_PLANE {
    static inline const QString fdIndex{QStringLiteral("fdIndex")};
    static inline const QString offset{QStringLiteral("offset")};
    static inline const QString stride{QStringLiteral("stride")};
};

struct BIND_FAILED {
    static inline const QString fourcc{QStringLiteral("fourcc")};
    static inline const QString generation{QStringLiteral("generation")};
    static inline const QString message{QStringLiteral("message")};
    static inline const QString modifier{QStringLiteral("modifier")};
    static inline const QString outputId{QStringLiteral("outputId")};
    static inline const QString reason{QStringLiteral("reason")};
};

struct CONSUMER_CAPS {
    static inline const QString dmabufCaps{QStringLiteral("dmabufCaps")};
};

struct CONTROL_ENVELOPE {
    static inline const QString code{QStringLiteral("code")};
    static inline const QString configSaved{QStringLiteral("configSaved")};
    static inline const QString message{QStringLiteral("message")};
    static inline const QString ok{QStringLiteral("ok")};
    static inline const QString requestId{QStringLiteral("requestId")};
    static inline const QString requestOpcode{QStringLiteral("requestOpcode")};
};

struct DMABUF_CAPS {
    static inline const QString backend{QStringLiteral("backend")};
    static inline const QString colorCaps{QStringLiteral("colorCaps")};
    static inline const QString deviceUuid{QStringLiteral("deviceUuid")};
    static inline const QString diagnostics{QStringLiteral("diagnostics")};
    static inline const QString driverUuid{QStringLiteral("driverUuid")};
    static inline const QString extentMax{QStringLiteral("extentMax")};
    static inline const QString fourcc{QStringLiteral("fourcc")};
    static inline const QString fourccs{QStringLiteral("fourccs")};
    static inline const QString implicitLinearFourccs{QStringLiteral("implicitLinearFourccs")};
    static inline const QString memoryHints{QStringLiteral("memoryHints")};
    static inline const QString modifier{QStringLiteral("modifier")};
    static inline const QString modifiers{QStringLiteral("modifiers")};
    static inline const QString pciAddress{QStringLiteral("pciAddress")};
    static inline const QString planeCount{QStringLiteral("planeCount")};
    static inline const QString probe{QStringLiteral("probe")};
    static inline const QString relayModes{QStringLiteral("relayModes")};
    static inline const QString renderNode{QStringLiteral("renderNode")};
    static inline const QString skipsExternalOnlyModifiers{QStringLiteral("skipsExternalOnlyModifiers")};
    static inline const QString syncCaps{QStringLiteral("syncCaps")};
    static inline const QString textureTarget{QStringLiteral("textureTarget")};
    static inline const QString vendor{QStringLiteral("vendor")};
    static inline const QString version{QStringLiteral("version")};
};

struct EVT_ERROR {
    static inline const QString code{QStringLiteral("code")};
    static inline const QString fatal{QStringLiteral("fatal")};
    static inline const QString message{QStringLiteral("message")};
};

struct EXTENT_MAX {
    static inline const QString height{QStringLiteral("height")};
    static inline const QString width{QStringLiteral("width")};
};

struct HELLO {
    static inline const QString clientName{QStringLiteral("clientName")};
    static inline const QString features{QStringLiteral("features")};
    static inline const QString protocol{QStringLiteral("protocol")};
    static inline const QString role{QStringLiteral("role")};
    static inline const QString version{QStringLiteral("version")};
};

struct OUTPUT_ACCEPTED {
    static inline const QString active{QStringLiteral("active")};
    static inline const QString consumerOutputId{QStringLiteral("consumerOutputId")};
    static inline const QString height{QStringLiteral("height")};
    static inline const QString logicalHeight{QStringLiteral("logicalHeight")};
    static inline const QString logicalWidth{QStringLiteral("logicalWidth")};
    static inline const QString monitorIndex{QStringLiteral("monitorIndex")};
    static inline const QString outputId{QStringLiteral("outputId")};
    static inline const QString scale{QStringLiteral("scale")};
    static inline const QString width{QStringLiteral("width")};
};

struct RECT {
    static inline const QString height{QStringLiteral("height")};
    static inline const QString width{QStringLiteral("width")};
    static inline const QString x{QStringLiteral("x")};
    static inline const QString y{QStringLiteral("y")};
};

struct REGISTER_OUTPUT {
    static inline const QString consumerOutputId{QStringLiteral("consumerOutputId")};
    static inline const QString desktop{QStringLiteral("desktop")};
    static inline const QString displayKey{QStringLiteral("displayKey")};
    static inline const QString displayName{QStringLiteral("displayName")};
    static inline const QString height{QStringLiteral("height")};
    static inline const QString layoutOutputCount{QStringLiteral("layoutOutputCount")};
    static inline const QString monitorIndex{QStringLiteral("monitorIndex")};
    static inline const QString physicalHeight{QStringLiteral("physicalHeight")};
    static inline const QString physicalWidth{QStringLiteral("physicalWidth")};
    static inline const QString refreshRateMhz{QStringLiteral("refreshRateMhz")};
    static inline const QString scale{QStringLiteral("scale")};
    static inline const QString transform{QStringLiteral("transform")};
    static inline const QString width{QStringLiteral("width")};
    static inline const QString x{QStringLiteral("x")};
    static inline const QString y{QStringLiteral("y")};
};

struct SET_CONFIG {
    static inline const QString clearColor{QStringLiteral("clearColor")};
    static inline const QString configGeneration{QStringLiteral("configGeneration")};
    static inline const QString destination{QStringLiteral("destination")};
    static inline const QString generation{QStringLiteral("generation")};
    static inline const QString outputId{QStringLiteral("outputId")};
    static inline const QString source{QStringLiteral("source")};
    static inline const QString transform{QStringLiteral("transform")};
};

struct UNBIND_DONE {
    static inline const QString generation{QStringLiteral("generation")};
    static inline const QString outputId{QStringLiteral("outputId")};
};

struct UPDATE_OUTPUT {
    static inline const QString consumerOutputId{QStringLiteral("consumerOutputId")};
    static inline const QString desktop{QStringLiteral("desktop")};
    static inline const QString displayKey{QStringLiteral("displayKey")};
    static inline const QString displayName{QStringLiteral("displayName")};
    static inline const QString height{QStringLiteral("height")};
    static inline const QString layoutOutputCount{QStringLiteral("layoutOutputCount")};
    static inline const QString monitorIndex{QStringLiteral("monitorIndex")};
    static inline const QString outputId{QStringLiteral("outputId")};
    static inline const QString physicalHeight{QStringLiteral("physicalHeight")};
    static inline const QString physicalWidth{QStringLiteral("physicalWidth")};
    static inline const QString refreshRateMhz{QStringLiteral("refreshRateMhz")};
    static inline const QString scale{QStringLiteral("scale")};
    static inline const QString transform{QStringLiteral("transform")};
    static inline const QString width{QStringLiteral("width")};
    static inline const QString x{QStringLiteral("x")};
    static inline const QString y{QStringLiteral("y")};
};

struct WELCOME {
    static inline const QString features{QStringLiteral("features")};
    static inline const QString negotiatedVersion{QStringLiteral("negotiatedVersion")};
    static inline const QString protocol{QStringLiteral("protocol")};
    static inline const QString version{QStringLiteral("version")};
};

struct WINDOW_STATE {
    static inline const QString displays{QStringLiteral("displays")};
    static inline const QString flags{QStringLiteral("flags")};
    static inline const QString reasons{QStringLiteral("reasons")};
    static inline const QString schema{QStringLiteral("schema")};
    static inline const QString session{QStringLiteral("session")};
    static inline const QString source{QStringLiteral("source")};
    static inline const QString timeUsec{QStringLiteral("timeUsec")};
};

}  // namespace vivid::protocol
