#!/usr/bin/env python3
"""Generate protocol bindings from vivid_display_v1.toml."""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any

SPEC = Path(__file__).with_name("vivid_display_v1.toml")
PROTO_DIR = Path(__file__).parent
REPO_ROOT = PROTO_DIR.parent.parent.parent

GENERATED_BANNER = (
    "/* generated by protocol_gen.py from vivid_display_v1.toml — do not edit */"
)
PY_GENERATED_BANNER = (
    "# generated by protocol_gen.py from vivid_display_v1.toml — do not edit"
)
JS_GENERATED_BANNER = (
    "// generated by protocol_gen.py from vivid_display_v1.toml — do not edit"
)

TYPE_SIZE = {
    "u16": 2,
    "u32": 4,
    "i32": 4,
    "u64": 8,
    "i64": 8,
    "f32": 4,
    "f64": 8,
}

MESSAGE_BYTES_KEYS = {
    "control-header": "CONTROL_HEADER_BYTES",
    "pointer-motion": "POINTER_MOTION_BODY_BYTES",
    "pointer-button": "POINTER_BUTTON_BODY_BYTES",
    "pointer-axis": "POINTER_AXIS_BODY_BYTES",
    "frame-ready": "FRAME_READY_BODY_BYTES",
    "unbind": "UNBIND_BODY_BYTES",
}

SIZE_T_CONSTANTS = frozenset({"CODEC_MAX_BODY_BYTES", "CODEC_MAX_FDS_PER_MESSAGE"})
INT_CONSTANTS = frozenset({"CODEC_FRAME_DONE", "CODEC_FRAME_NEED_IO"})
ENUM_ORDER = (
    "result",
    "error-code",
    "client-role",
    "request-opcode",
    "event-opcode",
    "control-opcode",
    "button-state",
    "axis-source",
)

ERROR_SEGMENT_COMMENTS = {
    (1, 99): "/* 1-99 handshake/connection, terminal (producer disconnects afterward) */",
    (100, 199): "/* 100-199 caps/negotiation, non-terminal */",
    (200, 299): "/* 200-299 output lifecycle, non-terminal */",
    (300, 399): "/* 300-399 control, non-terminal */",
}


@dataclass(frozen=True)
class LayoutField:
    name: str
    type: str
    offset: int
    size: int | None
    count_field: str | None = None
    max_count: int | None = None


@dataclass(frozen=True)
class MessageLayout:
    slug: str
    kind: str
    fields: tuple[LayoutField, ...]
    fixed_size: int | None
    bytes_key: str | None
    c_base: str
    js_base: str


def _slug_to_c_base(slug: str) -> str:
    return slug.replace("-", "_")


def _slug_to_js_base(slug: str) -> str:
    parts = slug.split("-")
    return "".join(part[:1].upper() + part[1:] for part in parts)


def parse_message_layouts(spec: dict[str, Any]) -> list[MessageLayout]:
    layouts: list[MessageLayout] = []
    for slug, message in spec.get("messages", {}).items():
        if message.get("encoding") != "binary":
            continue
        offset = 0
        fields: list[LayoutField] = []
        for raw in message["fields"]:
            field_type = raw["type"]
            if field_type.endswith("[]"):
                element_type = field_type[:-2]
                if element_type not in TYPE_SIZE:
                    raise ValueError(f"unsupported array element type {element_type}")
                fields.append(
                    LayoutField(
                        name=raw["name"],
                        type=field_type,
                        offset=offset,
                        size=None,
                        count_field=raw.get("count-field"),
                        max_count=raw.get("max"),
                    )
                )
                offset = None
                break
            size = TYPE_SIZE[field_type]
            fields.append(
                LayoutField(
                    name=raw["name"],
                    type=field_type,
                    offset=offset,
                    size=size,
                    max_count=raw.get("max"),
                )
            )
            offset += size
        layouts.append(
            MessageLayout(
                slug=slug,
                kind=message.get("kind", ""),
                fields=tuple(fields),
                fixed_size=offset,
                bytes_key=MESSAGE_BYTES_KEYS.get(slug),
                c_base=_slug_to_c_base(slug),
                js_base=_slug_to_js_base(slug),
            )
        )
    return layouts


def _bytes_define_name(layout: MessageLayout) -> str | None:
    if layout.bytes_key is None:
        return None
    return f"VIVID_DISPLAY_{layout.bytes_key}"


def _struct_format_field(field_type: str) -> str:
    return {
        "u16": "H",
        "u32": "I",
        "i32": "i",
        "u64": "Q",
        "i64": "q",
        "f32": "f",
        "f64": "d",
    }[field_type]


def _c_param_type(field_type: str) -> str:
    return {
        "u16": "uint16_t",
        "u32": "uint32_t",
        "i32": "int32_t",
        "u64": "uint64_t",
        "i64": "int64_t",
        "f32": "float",
        "f64": "double",
    }[field_type]


def _js_param_type(field_type: str) -> str:
    return "number"


def _emit_c_codec_helpers() -> list[str]:
    return [
        "static inline void vivid_display_codec_write_u16(uint8_t* out, uint16_t value)",
        "{",
        "    out[0] = (uint8_t)(value & 0xffu);",
        "    out[1] = (uint8_t)((value >> 8) & 0xffu);",
        "}",
        "",
        "static inline uint16_t vivid_display_codec_read_u16(const uint8_t* in)",
        "{",
        "    return (uint16_t)in[0] | ((uint16_t)in[1] << 8);",
        "}",
        "",
        "static inline void vivid_display_codec_write_u32(uint8_t* out, uint32_t value)",
        "{",
        "    out[0] = (uint8_t)(value & 0xffu);",
        "    out[1] = (uint8_t)((value >> 8) & 0xffu);",
        "    out[2] = (uint8_t)((value >> 16) & 0xffu);",
        "    out[3] = (uint8_t)((value >> 24) & 0xffu);",
        "}",
        "",
        "static inline uint32_t vivid_display_codec_read_u32(const uint8_t* in)",
        "{",
        "    return (uint32_t)in[0] | ((uint32_t)in[1] << 8) | ((uint32_t)in[2] << 16) |",
        "           ((uint32_t)in[3] << 24);",
        "}",
        "",
        "static inline void vivid_display_codec_write_u64(uint8_t* out, uint64_t value)",
        "{",
        "    vivid_display_codec_write_u32(out, (uint32_t)(value & 0xffffffffu));",
        "    vivid_display_codec_write_u32(out + 4, (uint32_t)(value >> 32));",
        "}",
        "",
        "static inline uint64_t vivid_display_codec_read_u64(const uint8_t* in)",
        "{",
        "    return (uint64_t)vivid_display_codec_read_u32(in) |",
        "           ((uint64_t)vivid_display_codec_read_u32(in + 4) << 32);",
        "}",
        "",
        "static inline void vivid_display_codec_write_f32(uint8_t* out, float value)",
        "{",
        "    uint32_t bits = 0;",
        "    memcpy(&bits, &value, sizeof(bits));",
        "    vivid_display_codec_write_u32(out, bits);",
        "}",
        "",
        "static inline float vivid_display_codec_read_f32(const uint8_t* in)",
        "{",
        "    float value = 0.f;",
        "    uint32_t bits = vivid_display_codec_read_u32(in);",
        "    memcpy(&value, &bits, sizeof(value));",
        "    return value;",
        "}",
        "",
        "static inline void vivid_display_codec_write_f64(uint8_t* out, double value)",
        "{",
        "    uint64_t bits = 0;",
        "    memcpy(&bits, &value, sizeof(bits));",
        "    vivid_display_codec_write_u64(out, bits);",
        "}",
        "",
        "static inline double vivid_display_codec_read_f64(const uint8_t* in)",
        "{",
        "    double value = 0.0;",
        "    uint64_t bits = vivid_display_codec_read_u64(in);",
        "    memcpy(&value, &bits, sizeof(value));",
        "    return value;",
        "}",
        "",
    ]


def _c_write_field(field: LayoutField, value_expr: str) -> str:
    if field.type == "u16":
        return f"vivid_display_codec_write_u16(out + {field.offset}, {value_expr});"
    if field.type == "u32":
        return f"vivid_display_codec_write_u32(out + {field.offset}, {value_expr});"
    if field.type == "u64":
        return f"vivid_display_codec_write_u64(out + {field.offset}, {value_expr});"
    if field.type == "f32":
        return f"vivid_display_codec_write_f32(out + {field.offset}, {value_expr});"
    if field.type == "f64":
        return f"vivid_display_codec_write_f64(out + {field.offset}, {value_expr});"
    raise ValueError(f"unsupported write type {field.type}")


def _c_read_field(field: LayoutField, dest_expr: str) -> str:
    if field.type == "u16":
        return f"*({dest_expr}) = vivid_display_codec_read_u16(data + {field.offset});"
    if field.type == "u32":
        return f"*({dest_expr}) = vivid_display_codec_read_u32(data + {field.offset});"
    if field.type == "u64":
        return f"*({dest_expr}) = vivid_display_codec_read_u64(data + {field.offset});"
    if field.type == "f32":
        return f"*({dest_expr}) = vivid_display_codec_read_f32(data + {field.offset});"
    if field.type == "f64":
        return f"*({dest_expr}) = vivid_display_codec_read_f64(data + {field.offset});"
    raise ValueError(f"unsupported read type {field.type}")


def _emit_c_message_codec(layout: MessageLayout) -> list[str]:
    lines: list[str] = []
    scalar_fields = [field for field in layout.fields if not field.type.endswith("[]")]
    array_field = next((field for field in layout.fields if field.type.endswith("[]")), None)

    if layout.fixed_size is not None:
        params = ", ".join(
            f"{_c_param_type(field.type)} {field.name}" for field in scalar_fields
        )
        lines.append(
            f"static inline void vivid_display_{layout.c_base}_body_write("
            f"uint8_t out[{_bytes_define_name(layout)}], {params})"
        )
        lines.append("{")
        for field in scalar_fields:
            lines.append(f"    {_c_write_field(field, field.name)}")
        lines.append("}")
        lines.append("")

        out_params = ", ".join(
            f"{_c_param_type(field.type)}* {field.name}" for field in scalar_fields
        )
        lines.append(
            f"static inline int vivid_display_{layout.c_base}_body_read("
            f"const uint8_t* data, size_t len, {out_params})"
        )
        lines.append("{")
        lines.append(f"    if (!data || len < {_bytes_define_name(layout)})")
        lines.append("        return -1;")
        for field in scalar_fields:
            lines.append(f"    {_c_read_field(field, field.name)}")
        lines.append("    return 0;")
        lines.append("}")
        lines.append("")
        return lines

    if array_field is None:
        raise ValueError(f"message {layout.slug} has no fixed size and no array tail")

    lines.extend(
        [
            "static inline size_t vivid_display_audio_samples_bin_body_bytes(uint32_t count)",
            "{",
            "    return 12u + (size_t)count * sizeof(float);",
            "}",
            "",
            "static inline int vivid_display_audio_samples_bin_body_write(",
            "    uint8_t* out,",
            "    size_t out_cap,",
            "    uint32_t count,",
            "    uint64_t time_usec,",
            "    const float* samples)",
            "{",
            "    if (!out || !samples || count == 0 || count > VIVID_DISPLAY_AUDIO_SAMPLES_BIN_MAX_COUNT)",
            "        return -1;",
            "    const size_t need = vivid_display_audio_samples_bin_body_bytes(count);",
            "    if (out_cap < need)",
            "        return -1;",
            "    vivid_display_codec_write_u32(out, count);",
            "    vivid_display_codec_write_u64(out + 4, time_usec);",
            "    for (uint32_t i = 0; i < count; i++)",
            "        vivid_display_codec_write_f32(out + 12 + (size_t)i * sizeof(float), samples[i]);",
            "    return (int)need;",
            "}",
            "",
            "static inline int vivid_display_audio_samples_bin_body_read(",
            "    const uint8_t* data,",
            "    size_t len,",
            "    uint32_t* count,",
            "    uint64_t* time_usec,",
            "    float* samples,",
            "    size_t samples_cap)",
            "{",
            "    if (!data || !count || !time_usec || !samples || len < 12)",
            "        return -1;",
            "    *count = vivid_display_codec_read_u32(data);",
            "    if (*count == 0 || *count > VIVID_DISPLAY_AUDIO_SAMPLES_BIN_MAX_COUNT)",
            "        return -1;",
            "    const size_t need = vivid_display_audio_samples_bin_body_bytes(*count);",
            "    if (len < need || samples_cap < *count)",
            "        return -1;",
            "    *time_usec = vivid_display_codec_read_u64(data + 4);",
            "    for (uint32_t i = 0; i < *count; i++)",
            "        samples[i] = vivid_display_codec_read_f32(data + 12 + (size_t)i * sizeof(float));",
            "    return (int)need;",
            "}",
            "",
        ]
    )
    return lines


def emit_c_codec_section(layouts: list[MessageLayout]) -> list[str]:
    lines = ["", "#include <string.h>", ""]
    lines.extend(_emit_c_codec_helpers())
    for layout in layouts:
        lines.extend(_emit_c_message_codec(layout))
    return lines


def _js_write_field(field: LayoutField, value_expr: str) -> str:
    mapping = {
        "u16": f"view.setUint16({field.offset}, {value_expr}, true);",
        "u32": f"view.setUint32({field.offset}, {value_expr}, true);",
        "u64": f"view.setBigUint64({field.offset}, BigInt({value_expr}), true);",
        "f32": f"view.setFloat32({field.offset}, {value_expr}, true);",
        "f64": f"view.setFloat64({field.offset}, {value_expr}, true);",
    }
    return mapping[field.type]


def _js_read_field(field: LayoutField) -> str:
    mapping = {
        "u16": f"view.getUint16({field.offset}, true)",
        "u32": f"view.getUint32({field.offset}, true)",
        "u64": f"Number(view.getBigUint64({field.offset}, true))",
        "f32": f"view.getFloat32({field.offset}, true)",
        "f64": f"view.getFloat64({field.offset}, true)",
    }
    key = re.sub(r"_([a-z])", lambda match: match.group(1).upper(), field.name)
    if field.name == "output_id":
        key = "outputId"
    elif field.name == "time_usec":
        key = "timeUsec"
    elif field.name == "buffer_index":
        key = "bufferIndex"
    elif field.name == "target_time_usec":
        key = "targetTimeUsec"
    elif field.name == "delta_x":
        key = "deltaX"
    elif field.name == "delta_y":
        key = "deltaY"
    return f"        {key}: {_js_read_field_expr(field)},"


def _js_read_field_expr(field: LayoutField) -> str:
    mapping = {
        "u16": f"view.getUint16({field.offset}, true)",
        "u32": f"view.getUint32({field.offset}, true)",
        "u64": f"Number(view.getBigUint64({field.offset}, true))",
        "f32": f"view.getFloat32({field.offset}, true)",
        "f64": f"view.getFloat64({field.offset}, true)",
    }
    return mapping[field.type]


def emit_js_codec(layouts: list[MessageLayout], defines: dict[str, int | str]) -> str:
    imports = sorted(
        name
        for layout in layouts
        if layout.bytes_key and (define := f"VIVID_DISPLAY_{layout.bytes_key}") in defines
        for name in [define]
    )
    if "VIVID_DISPLAY_AUDIO_SAMPLES_BIN_MAX_COUNT" in defines:
        imports.append("VIVID_DISPLAY_AUDIO_SAMPLES_BIN_MAX_COUNT")
    import_lines = "\n".join(f"    {name}," for name in imports)
    lines = [
        JS_GENERATED_BANNER,
        "",
        "import {",
        import_lines,
        "} from './protocol-constants.js';",
        "",
    ]

    for layout in layouts:
        scalar_fields = [field for field in layout.fields if not field.type.endswith("[]")]
        if layout.fixed_size is not None:
            define_name = f"VIVID_DISPLAY_{layout.bytes_key}"
            params = ", ".join(field.name for field in scalar_fields)
            lines.append(f"export function encode{layout.js_base}({params}) {{")
            lines.append(f"    const body = new Uint8Array({define_name});")
            lines.append("    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);")
            for field in scalar_fields:
                lines.append(f"    {_js_write_field(field, field.name)}")
            lines.append("    return body;")
            lines.append("}")
            lines.append("")
            lines.append(f"export function decode{layout.js_base}(body) {{")
            lines.append(f"    if (body.length !== {define_name})")
            lines.append(
                f'        throw new Error(`invalid {layout.slug.upper()} body length ${{body.length}}`);'
            )
            lines.append("    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);")
            lines.append("    return {")
            for field in scalar_fields:
                lines.append(_js_read_field(field))
            lines.append("    };")
            lines.append("}")
            lines.append("")
            continue

        lines.extend(
            [
                "export function encodeAudioSamplesBin(count, timeUsec, samples) {",
                "    const body = new Uint8Array(12 + count * 4);",
                "    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);",
                "    view.setUint32(0, count, true);",
                "    view.setBigUint64(4, BigInt(timeUsec), true);",
                "    for (let index = 0; index < count; index++)",
                "        view.setFloat32(12 + index * 4, samples[index], true);",
                "    return body;",
                "}",
                "",
                "export function decodeAudioSamplesBin(body) {",
                "    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);",
                "    const count = view.getUint32(0, true);",
                "    const timeUsec = Number(view.getBigUint64(4, true));",
                "    const samples = new Array(count);",
                "    for (let index = 0; index < count; index++)",
                "        samples[index] = view.getFloat32(12 + index * 4, true);",
                "    return { count, timeUsec, samples };",
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def emit_py_codec(layouts: list[MessageLayout]) -> str:
    lines = [
        PY_GENERATED_BANNER,
        "",
        "import struct",
        "",
    ]
    for layout in layouts:
        scalar_fields = [field for field in layout.fields if not field.type.endswith("[]")]
        func_base = layout.c_base
        if layout.fixed_size is not None:
            fmt = "<" + "".join(_struct_format_field(field.type) for field in scalar_fields)
            arglist = ", ".join(field.name for field in scalar_fields)
            lines.append(f"{func_base.upper()}_STRUCT = \"{fmt}\"")
            lines.append("")
            lines.append(f"def pack_{func_base}({arglist}):")
            lines.append(f"    return struct.pack({func_base.upper()}_STRUCT, {arglist})")
            lines.append("")
            lines.append(f"def unpack_{func_base}(body):")
            lines.append(f"    return struct.unpack({func_base.upper()}_STRUCT, body)")
            lines.append("")
            continue
        lines.extend(
            [
                "def pack_audio_samples_bin(count, time_usec, samples):",
                "    return struct.pack('<IQ', count, time_usec) + struct.pack('<' + ('f' * count), *samples)",
                "",
                "def unpack_audio_samples_bin(body):",
                "    count, time_usec = struct.unpack_from('<IQ', body, 0)",
                "    samples = struct.unpack_from('<' + ('f' * count), body, 12)",
                "    return count, time_usec, samples",
                "",
            ]
        )
    return "\n".join(lines)


def _segment_for_code(code: int, segments: list[dict[str, Any]]) -> dict[str, Any] | None:
    for segment in segments:
        low, high = segment["range"]
        if low <= code <= high:
            return segment
    return None


def _error_entries(spec: dict[str, Any]) -> list[tuple[str, int, str, bool]]:
    segments = spec.get("errors", {}).get("segments", [])
    prefix = spec["enums"]["error-code"]["prefix"]
    entries: list[tuple[str, int, str, bool]] = []
    for member in spec["enums"]["error-code"]["members"]:
        if "name" not in member:
            continue
        code = member["value"]
        segment = _segment_for_code(code, segments)
        domain = segment["domain"] if segment else "unknown"
        terminal = bool(segment["terminal"]) if segment else False
        entries.append((member["name"], code, domain, terminal))
    entries.sort(key=lambda item: item[1])
    return entries


def _named_value_entries(section: dict[str, Any]) -> list[tuple[str, int]]:
    prefix = section.get("prefix", "")
    entries: list[tuple[str, int]] = []
    for member in section.get("members", []):
        if "name" not in member:
            continue
        if "alias-of" in member:
            continue
        entries.append((member["name"], member["value"]))
    entries.sort(key=lambda item: item[1])
    return entries


def _client_role_entries(spec: dict[str, Any]) -> list[tuple[str, int]]:
    section = spec["enums"]["client-role"]
    entries: list[tuple[str, int]] = []
    for member in section["members"]:
        if "alias-of" in member:
            continue
        if "name" in member:
            entries.append((member["name"], member["value"]))
    entries.sort(key=lambda item: item[1])
    return entries


def _message_min_versions(spec: dict[str, Any]) -> list[tuple[str, int, str]]:
    entries: dict[str, tuple[int, str]] = {}
    for slug, message in spec.get("messages", {}).items():
        since = message.get("since")
        if since is None:
            continue
        key = message.get("opcode", slug.upper().replace("-", "_"))
        entries[key] = (since, message.get("kind", "message"))

    req_enum = spec.get("enums", {}).get("request-opcode", {})
    prefix = req_enum.get("prefix", "VIVID_DISPLAY_REQ_")
    for member in req_enum.get("members", []):
        since = member.get("since")
        if since is None or "name" not in member:
            continue
        entries[member["name"]] = (since, "request-opcode")

    return sorted((key, since, kind) for key, (since, kind) in entries.items())


def emit_c_metadata(spec: dict[str, Any]) -> list[str]:
    lines = ["", "#include <stdbool.h>", ""]
    error_entries = _error_entries(spec)

    lines.append("static inline const char* vivid_display_error_name(int code)")
    lines.append("{")
    lines.append("    switch (code) {")
    for name, code, _domain, _terminal in error_entries:
        lines.append(f'    case VIVID_DISPLAY_ERR_{name}: return "{name}";')
    lines.append("    default: return NULL;")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    lines.append("static inline bool vivid_display_error_terminal(int code)")
    lines.append("{")
    lines.append("    switch (code) {")
    for name, code, _domain, terminal in error_entries:
        if terminal:
            lines.append(f"    case VIVID_DISPLAY_ERR_{name}: return true;")
    lines.append("    default: return false;")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    lines.append("static inline const char* vivid_display_error_domain(int code)")
    lines.append("{")
    lines.append("    switch (code) {")
    for name, code, domain, _terminal in error_entries:
        lines.append(f'    case VIVID_DISPLAY_ERR_{name}: return "{domain}";')
    lines.append('    default: return "unknown";')
    lines.append("    }")
    lines.append("}")
    lines.append("")

    bind_failed = spec["bind-failed-reasons"]
    prefix = bind_failed["prefix"]
    lines.append("static inline const char* vivid_display_bind_failed_reason_name(uint32_t reason)")
    lines.append("{")
    lines.append("    switch (reason) {")
    for name, value in _named_value_entries(bind_failed):
        lines.append(f'    case {prefix}{name}: return "{name}";')
    lines.append("    default: return NULL;")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    flag_group = spec["flags"]["window"]
    flag_prefix = flag_group["prefix"]
    lines.append("static inline const char* vivid_display_window_flag_name(uint32_t flag)")
    lines.append("{")
    lines.append("    switch (flag) {")
    for name, value in _named_value_entries(flag_group):
        lines.append(f'    case {flag_prefix}{name}: return "{name}";')
    lines.append("    default: return NULL;")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    role_prefix = spec["enums"]["client-role"]["prefix"]
    lines.append("static inline const char* vivid_display_client_role_name(uint32_t role)")
    lines.append("{")
    lines.append("    switch (role) {")
    for name, value in _client_role_entries(spec):
        lines.append(f'    case {role_prefix}{name}: return "{name}";')
    lines.append("    default: return NULL;")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    min_versions = _message_min_versions(spec)
    req_enum = spec.get("enums", {}).get("request-opcode", {})
    req_with_since = [
        (member["name"], member["since"])
        for member in req_enum.get("members", [])
        if "name" in member and member.get("since") is not None
    ]
    if req_with_since:
        lines.append("static inline uint32_t vivid_display_request_min_version(uint16_t opcode)")
        lines.append("{")
        lines.append("    switch (opcode) {")
        for name, since in req_with_since:
            lines.append(f"    case VIVID_DISPLAY_REQ_{name}: return {since}u;")
        lines.append("    default: return VIVID_DISPLAY_PROTOCOL_MIN_SUPPORTED;")
        lines.append("    }")
        lines.append("}")
        lines.append("")

    return lines


def emit_js_meta(spec: dict[str, Any]) -> str:
    error_entries = _error_entries(spec)
    lines = [
        JS_GENERATED_BANNER,
        "",
        "import {",
    ]
    const_names = sorted(
        {
            f"VIVID_DISPLAY_ERR_{name}"
            for name, _code, _domain, _terminal in error_entries
        }
        | {
            f"{spec['bind-failed-reasons']['prefix']}{name}"
            for name, _value in _named_value_entries(spec["bind-failed-reasons"])
        }
        | {
            f"{spec['flags']['window']['prefix']}{name}"
            for name, _value in _named_value_entries(spec["flags"]["window"])
        }
        | {
            f"{spec['enums']['client-role']['prefix']}{name}"
            for name, _value in _client_role_entries(spec)
        }
    )
    lines.extend(f"    {name}," for name in const_names)
    lines.extend(
        [
            "} from './protocol-constants.js';",
            "",
            "export const ERROR_NAMES = {",
        ]
    )
    for name, code, _domain, _terminal in error_entries:
        lines.append(f'    [VIVID_DISPLAY_ERR_{name}]: "{name}",')
    lines.extend(["};", ""])

    lines.extend(
        [
            "export const ERROR_DOMAINS = {",
        ]
    )
    for name, code, domain, _terminal in error_entries:
        lines.append(f'    [VIVID_DISPLAY_ERR_{name}]: "{domain}",')
    lines.extend(["};", ""])

    lines.extend(
        [
            "export const ERROR_TERMINAL = {",
        ]
    )
    for name, code, _domain, terminal in error_entries:
        lines.append(f"    [VIVID_DISPLAY_ERR_{name}]: {'true' if terminal else 'false'},")
    lines.extend(["};", ""])

    bind_prefix = spec["bind-failed-reasons"]["prefix"]
    lines.extend(["export const BIND_FAILED_REASON_NAMES = {"])
    for name, value in _named_value_entries(spec["bind-failed-reasons"]):
        lines.append(f'    [{bind_prefix}{name}]: "{name}",')
    lines.extend(["};", ""])

    flag_prefix = spec["flags"]["window"]["prefix"]
    lines.extend(["export const WINDOW_FLAG_NAMES = {"])
    for name, value in _named_value_entries(spec["flags"]["window"]):
        lines.append(f'    [{flag_prefix}{name}]: "{name}",')
    lines.extend(["};", ""])

    role_prefix = spec["enums"]["client-role"]["prefix"]
    lines.extend(["export const CLIENT_ROLE_NAMES = {"])
    for name, value in _client_role_entries(spec):
        lines.append(f'    [{role_prefix}{name}]: "{name}",')
    lines.extend(["};", ""])

    min_versions = _message_min_versions(spec)
    lines.extend(["export const MESSAGE_MIN_VERSION = {"])
    for key, since, _kind in min_versions:
        lines.append(f'    {key}: {since},')
    lines.extend(["};", ""])

    lines.extend(
        [
            "export function errorName(code) {",
            "    return ERROR_NAMES[code] ?? `UNKNOWN(${code})`;",
            "}",
            "",
            "export function errorDomain(code) {",
            '    return ERROR_DOMAINS[code] ?? "unknown";',
            "}",
            "",
            "export function errorIsTerminal(code) {",
            "    return ERROR_TERMINAL[code] === true;",
            "}",
            "",
            "export function bindFailedReasonName(reason) {",
            "    return BIND_FAILED_REASON_NAMES[reason] ?? `UNKNOWN(${reason})`;",
            "}",
            "",
            "export function windowFlagName(flag) {",
            "    return WINDOW_FLAG_NAMES[flag] ?? `UNKNOWN(${flag})`;",
            "}",
            "",
            "export function clientRoleName(role) {",
            "    return CLIENT_ROLE_NAMES[role] ?? `UNKNOWN(${role})`;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def emit_hpp_meta(spec: dict[str, Any]) -> str:
    error_entries = _error_entries(spec)
    lines = [
        GENERATED_BANNER,
        "",
        "#pragma once",
        "",
        '#include "vivid_protocol_constants.hpp"',
        "",
        "#include <string_view>",
        "",
        'namespace vivid::protocol {',
        "",
        "inline constexpr std::string_view error_name(int code) noexcept",
        "{",
        "    switch (code) {",
    ]
    for name, code, _domain, _terminal in error_entries:
        lines.append(f'    case VIVID_DISPLAY_ERR_{name}: return "{name}";')
    lines.append('    default: return "UNKNOWN";')
    lines.extend(["    }", "}", ""])

    lines.append("inline constexpr bool error_is_terminal(int code) noexcept")
    lines.append("{")
    lines.append("    switch (code) {")
    for name, code, _domain, terminal in error_entries:
        if terminal:
            lines.append(f"    case VIVID_DISPLAY_ERR_{name}: return true;")
    lines.extend(["    default: return false;", "    }", "}", ""])

    lines.append("inline constexpr std::string_view error_domain(int code) noexcept")
    lines.append("{")
    lines.append("    switch (code) {")
    for name, code, domain, _terminal in error_entries:
        lines.append(f'    case VIVID_DISPLAY_ERR_{name}: return "{domain}";')
    lines.extend(['    default: return "unknown";', "    }", "}", ""])

    bind_prefix = spec["bind-failed-reasons"]["prefix"]
    lines.append("inline constexpr std::string_view bind_failed_reason_name(std::uint32_t reason) noexcept")
    lines.append("{")
    lines.append("    switch (reason) {")
    for name, value in _named_value_entries(spec["bind-failed-reasons"]):
        lines.append(f'    case {bind_prefix}{name}: return "{name}";')
    lines.extend(['    default: return "UNKNOWN";', "    }", "}", ""])

    flag_prefix = spec["flags"]["window"]["prefix"]
    lines.append("inline constexpr std::string_view window_flag_name(std::uint32_t flag) noexcept")
    lines.append("{")
    lines.append("    switch (flag) {")
    for name, value in _named_value_entries(spec["flags"]["window"]):
        lines.append(f'    case {flag_prefix}{name}: return "{name}";')
    lines.extend(['    default: return "UNKNOWN";', "    }", "}", ""])

    role_prefix = spec["enums"]["client-role"]["prefix"]
    lines.append("inline constexpr std::string_view client_role_name(std::uint32_t role) noexcept")
    lines.append("{")
    lines.append("    switch (role) {")
    for name, value in _client_role_entries(spec):
        lines.append(f'    case {role_prefix}{name}: return "{name}";')
    lines.extend(['    default: return "UNKNOWN";', "    }", "}", ""])

    min_versions = _message_min_versions(spec)
    if min_versions:
        lines.append("inline constexpr std::uint32_t message_min_version(std::string_view key) noexcept")
        lines.append("{")
        for key, since, _kind in min_versions:
            lines.append(f'    if (key == "{key}") return {since}u;')
        lines.append("    return VIVID_DISPLAY_PROTOCOL_MIN_SUPPORTED;")
        lines.append("}")
        lines.append("")

    lines.extend(["}  // namespace vivid::protocol", ""])
    return "\n".join(lines)


def emit_py_meta(spec: dict[str, Any]) -> str:
    error_entries = _error_entries(spec)
    lines = [PY_GENERATED_BANNER, "", "ERROR_NAMES = {"]
    for name, code, _domain, _terminal in error_entries:
        lines.append(f'    {code}: "{name}",')
    lines.extend(["}", "", "ERROR_DOMAINS = {"])
    for name, code, domain, _terminal in error_entries:
        lines.append(f'    {code}: "{domain}",')
    lines.extend(["}", "", "ERROR_TERMINAL = {"])
    for name, code, _domain, terminal in error_entries:
        lines.append(f"    {code}: {'True' if terminal else 'False'},")
    lines.extend(["}", ""])

    lines.extend(["BIND_FAILED_REASON_NAMES = {"])
    for name, value in _named_value_entries(spec["bind-failed-reasons"]):
        lines.append(f'    {value}: "{name}",')
    lines.extend(["}", ""])

    lines.extend(["WINDOW_FLAG_NAMES = {"])
    for name, value in _named_value_entries(spec["flags"]["window"]):
        lines.append(f'    {value}: "{name}",')
    lines.extend(["}", ""])

    role_prefix = spec["enums"]["client-role"]["prefix"]
    lines.extend(["CLIENT_ROLE_NAMES = {"])
    for name, value in _client_role_entries(spec):
        lines.append(f"    {value}: \"{name}\",")
    lines.extend(["}", ""])

    min_versions = _message_min_versions(spec)
    lines.extend(["MESSAGE_MIN_VERSION = {"])
    for key, since, _kind in min_versions:
        lines.append(f'    "{key}": {since},')
    lines.extend(["}", ""])

    lines.extend(
        [
            "",
            "def error_name(code):",
            '    return ERROR_NAMES.get(code, f"UNKNOWN({code})")',
            "",
            "def error_domain(code):",
            '    return ERROR_DOMAINS.get(code, "unknown")',
            "",
            "def error_is_terminal(code):",
            "    return ERROR_TERMINAL.get(code, False)",
            "",
            "def bind_failed_reason_name(reason):",
            '    return BIND_FAILED_REASON_NAMES.get(reason, f"UNKNOWN({reason})")',
            "",
            "def window_flag_name(flag):",
            '    return WINDOW_FLAG_NAMES.get(flag, f"UNKNOWN({flag})")',
            "",
            "def client_role_name(role):",
            '    return CLIENT_ROLE_NAMES.get(role, f"UNKNOWN({role})")',
            "",
        ]
    )
    return "\n".join(lines)


def _field_macro_suffix(field: str) -> str:
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", field).upper()


def _json_field_macro(message: str, field: str) -> str:
    message_token = message.upper().replace("-", "_")
    return f"VIVID_JSON_{message_token}_{_field_macro_suffix(field)}"


def parse_json_field_groups(spec: dict[str, Any]) -> dict[str, dict[str, str]]:
    raw = spec.get("json-fields", {})
    groups: dict[str, dict[str, str]] = {}
    for message, fields in raw.items():
        if not isinstance(fields, dict):
            continue
        groups[message.upper()] = {key: str(value) for key, value in fields.items()}
    return groups


def parse_config_key_members(spec: dict[str, Any]) -> list[dict[str, Any]]:
    return list(spec.get("config-keys", {}).get("members", []))


CONFIG_SCHEMA_TYPE_C = {
    "bool": "VIVID_CONFIG_SCHEMA_BOOL",
    "int": "VIVID_CONFIG_SCHEMA_INT",
    "string": "VIVID_CONFIG_SCHEMA_STRING",
    "array": "VIVID_CONFIG_SCHEMA_ARRAY",
    "object": "VIVID_CONFIG_SCHEMA_OBJECT",
}


def emit_c_json_fields(groups: dict[str, dict[str, str]]) -> str:
    lines = [
        GENERATED_BANNER,
        "",
        "#ifndef VIVID_DISPLAY_PROTOCOL_JSON_H",
        "#define VIVID_DISPLAY_PROTOCOL_JSON_H",
        "",
    ]
    for message in sorted(groups):
        for field in sorted(groups[message]):
            wire = groups[message][field]
            lines.append(f'#define {_json_field_macro(message, field)} "{wire}"')
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def emit_js_json_fields(groups: dict[str, dict[str, str]]) -> str:
    banner = GENERATED_BANNER.replace("/* ", "// ").replace(" */", "")
    lines = [banner, "", "export const J = {"]
    for index, message in enumerate(sorted(groups)):
        if index:
            lines.append("")
        lines.append(f"    {message}: {{")
        for field in sorted(groups[message]):
            wire = groups[message][field]
            lines.append(f'        {field}: "{wire}",')
        lines.append("    },")
    lines.extend(["};", ""])
    return "\n".join(lines)


def emit_hpp_json_fields(groups: dict[str, dict[str, str]]) -> str:
    lines = [
        GENERATED_BANNER,
        "",
        "#pragma once",
        "",
        "#include <QString>",
        "",
        "namespace vivid::protocol {",
        "",
    ]
    for message in sorted(groups):
        lines.append(f"struct {message} {{")
        for field in sorted(groups[message]):
            wire = groups[message][field]
            lines.append(f'    static inline const QString {field}{{QStringLiteral("{wire}")}};')
        lines.append("};")
        lines.append("")
    lines.extend(["}  // namespace vivid::protocol", ""])
    return "\n".join(lines)


def emit_py_json_fields(groups: dict[str, dict[str, str]]) -> str:
    lines = [PY_GENERATED_BANNER, "", "J = {"]
    for message in sorted(groups):
        lines.append(f'    "{message}": {{')
        for field in sorted(groups[message]):
            wire = groups[message][field]
            lines.append(f'        "{field}": "{wire}",')
        lines.append("    },")
    lines.extend(["}", ""])
    return "\n".join(lines)


def emit_c_config_schema(members: list[dict[str, Any]]) -> str:
    lines = [
        GENERATED_BANNER,
        "",
        "#ifndef VIVID_PRODUCER_CONFIG_SCHEMA_H",
        "#define VIVID_PRODUCER_CONFIG_SCHEMA_H",
        "",
        "#include <glib.h>",
        "",
        "typedef enum",
        "{",
        "    VIVID_CONFIG_SCHEMA_BOOL,",
        "    VIVID_CONFIG_SCHEMA_INT,",
        "    VIVID_CONFIG_SCHEMA_STRING,",
        "    VIVID_CONFIG_SCHEMA_ARRAY,",
        "    VIVID_CONFIG_SCHEMA_OBJECT,",
        "} VividConfigSchemaType;",
        "",
        "typedef struct",
        "{",
        "    const gchar* kebab_key;",
        "    const gchar* camel_key;",
        "    VividConfigSchemaType type;",
        "} VividConfigSchemaEntry;",
        "",
        "static const VividConfigSchemaEntry vivid_set_state_schema[] = {",
    ]
    for member in members:
        schema_type = member["type"]
        if schema_type not in CONFIG_SCHEMA_TYPE_C:
            raise ValueError(f"unsupported config key type: {schema_type}")
        camel = member.get("camel")
        camel_text = f"\"{camel}\"" if camel else "NULL"
        lines.append(
            f'    {{"{member["kebab"]}", {camel_text}, {CONFIG_SCHEMA_TYPE_C[schema_type]}}},'
        )
    lines.extend(
        [
            "};",
            "",
            "#endif",
            "",
        ]
    )
    return "\n".join(lines)


def emit_py_config_keys(members: list[dict[str, Any]]) -> str:
    lines = [PY_GENERATED_BANNER, ""]
    for member in members:
        token = member["kebab"].upper().replace("-", "_")
        lines.append(f'{token} = "{member["kebab"]}"')
        camel = member.get("camel")
        if camel:
            lines.append(f"{token}_CAMEL = \"{camel}\"")
        lines.append("")
    return "\n".join(lines)


DOCS_BANNER = (
    "<!-- generated by protocol_gen.py from vivid_display_v1.toml — do not edit -->"
)

REQUEST_JSON_GROUPS = {
    "HELLO": "HELLO",
    "REGISTER_OUTPUT": "REGISTER_OUTPUT",
    "UPDATE_OUTPUT": "UPDATE_OUTPUT",
    "CONSUMER_CAPS": "CONSUMER_CAPS",
    "WINDOW_STATE": "WINDOW_STATE",
    "BIND_FAILED": "BIND_FAILED",
    "UNBIND_DONE": "UNBIND_DONE",
}

EVENT_JSON_GROUPS = {
    "WELCOME": "WELCOME",
    "OUTPUT_ACCEPTED": "OUTPUT_ACCEPTED",
    "BIND_BUFFERS": "BIND_BUFFERS",
    "SET_CONFIG": "SET_CONFIG",
    "ERROR": "EVT_ERROR",
}

REQUEST_FD_COUNTS: dict[str, str] = {}

EVENT_FD_COUNTS: dict[str, str] = {
    "BIND_BUFFERS": "1..64",
    "FRAME_READY": "2",
}

CONTROL_DIRECTION: dict[str, str] = {
    "GET_STATE": "controller -> producer",
    "SET_PLAYING": "controller -> producer",
    "SET_MUTED": "controller -> producer",
    "SET_VOLUME": "controller -> producer",
    "SET_CONTENT_FIT": "controller -> producer",
    "SET_SCENE_FPS": "controller -> producer",
    "OPEN_SETTINGS": "controller -> producer",
    "SET_STATE": "controller -> producer",
}


def _wire_type_name(field_type: str) -> str:
    if field_type.endswith("[]"):
        element = field_type[:-2]
        return f"{_wire_type_name(element)}[]"
    return f"{field_type}le"


def _layouts_by_opcode(spec: dict[str, Any]) -> dict[str, str]:
    mapping: dict[str, str] = {}
    for slug, message in spec.get("messages", {}).items():
        opcode = message.get("opcode")
        if opcode:
            mapping[opcode] = slug
    return mapping


def _request_body_summary(
    name: str,
    layouts_by_opcode: dict[str, str],
    layouts: list[MessageLayout],
    json_groups: dict[str, dict[str, str]],
) -> str:
    if name in layouts_by_opcode:
        slug = layouts_by_opcode[name]
        layout = next(item for item in layouts if item.slug == slug)
        if layout.fixed_size is None:
            return f"binary, variable ({slug})"
        return f"binary, {layout.fixed_size} bytes"
    if name == "CONTROL":
        return "control header + JSON"
    if name in REQUEST_JSON_GROUPS:
        return "JSON"
    if name == "BYE":
        return "empty/ignored"
    if name in ("MEDIA_STATE", "AUDIO_SAMPLES"):
        return "JSON"
    return "JSON"


def _event_body_summary(
    name: str,
    layouts_by_opcode: dict[str, str],
    layouts: list[MessageLayout],
) -> str:
    if name in layouts_by_opcode:
        slug = layouts_by_opcode[name]
        layout = next(item for item in layouts if item.slug == slug)
        if layout.fixed_size is None:
            return f"binary, variable ({slug})"
        return f"binary, {layout.fixed_size} bytes"
    if name == "CONTROL":
        return "control header + JSON"
    if name in EVENT_JSON_GROUPS:
        return "JSON"
    if name == "AUDIO_FRAME":
        return "unused currently"
    return "JSON"


def _emit_md_table(headers: list[str], rows: list[list[str]]) -> list[str]:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return lines


def _emit_binary_layout_section(layout: MessageLayout, spec_messages: dict[str, Any]) -> list[str]:
    slug = layout.slug
    message = spec_messages[slug]
    title = slug.replace("-", " ").title()
    lines = [f"### `{slug}`", ""]
    opcode = message.get("opcode")
    if opcode:
        lines.append(f"- Opcode constant: `{opcode}`")
    since = message.get("since")
    if since is not None:
        lines.append(f"- Since protocol version: `{since}`")
    lines.append("")

    if layout.fixed_size is None:
        lines.append("Variable-length binary body.")
        lines.append("")
        for field in layout.fields:
            if field.type.endswith("[]"):
                lines.append(
                    f"- `{field.name}`: `{_wire_type_name(field.type)}`, "
                    f"count from `{field.count_field}` (max {field.max_count})"
                )
            else:
                lines.append(
                    f"- `{field.name}` @ offset {field.offset}: "
                    f"`{_wire_type_name(field.type)}`"
                )
        lines.append("")
        return lines

    rows: list[list[str]] = []
    for field in layout.fields:
        rows.append(
            [
                str(field.offset),
                str(field.size),
                f"`{_wire_type_name(field.type)}`",
                f"`{field.name}`",
            ]
        )
    lines.extend(_emit_md_table(["Offset", "Size", "Type", "Field"], rows))
    lines.append("")
    return lines


def emit_docs_reference(
    spec: dict[str, Any],
    layouts: list[MessageLayout],
    json_groups: dict[str, dict[str, str]],
    config_members: list[dict[str, Any]],
) -> str:
    protocol = spec["protocol"]
    constants = spec.get("constants", {})
    layouts_by_opcode = _layouts_by_opcode(spec)
    spec_messages = spec.get("messages", {})
    lines = [
        DOCS_BANNER,
        "",
        "# Vivid Display Protocol Reference",
        "",
        "Machine-readable tables generated from "
        "`producer/src/protocol/vivid_display_v1.toml`. "
        "Semantic prose, state machines, and invariants: `docs/protocols.md`.",
        "",
        "## Protocol identity",
        "",
        f"- Name: `{protocol['name']}`",
        f"- Current version: `{protocol['version']}`",
        f"- Minimum supported HELLO version: `{protocol['min-supported']}`",
        "",
    ]

    history = spec.get("history", [])
    if history:
        lines.extend(["## Version history", ""])
        rows = [[str(entry["version"]), entry["summary"]] for entry in history]
        lines.extend(_emit_md_table(["Version", "Summary"], rows))
        lines.append("")

    lines.extend(["## Transport constants", ""])
    transport_rows = [
        ["`CODEC_MAX_BODY_BYTES`", str(constants["CODEC_MAX_BODY_BYTES"])],
        ["`CODEC_MAX_FDS_PER_MESSAGE`", str(constants["CODEC_MAX_FDS_PER_MESSAGE"])],
        ["`FRAME_HEADER_BYTES`", str(constants["FRAME_HEADER_BYTES"])],
        ["`FRAME_READY_FD_COUNT`", str(constants["FRAME_READY_FD_COUNT"])],
        ["`DMABUF_MAX_PLANES`", str(constants["DMABUF_MAX_PLANES"])],
        ["`AUDIO_SAMPLES_BIN_MAX_COUNT`", str(constants["AUDIO_SAMPLES_BIN_MAX_COUNT"])],
    ]
    lines.extend(_emit_md_table(["Constant", "Value"], transport_rows))
    lines.append("")

    lines.extend(
        [
            "## Display transport frame header",
            "",
            "Every display socket message:",
            "",
        ]
    )
    lines.extend(
        _emit_md_table(
            ["Offset", "Size", "Type", "Field"],
            [
                ["0", "2", "`u16le`", "`opcode`"],
                ["2", "2", "`u16le`", "`total_length` (includes 4-byte header)"],
                ["4", "`total_length - 4`", "bytes", "`body`"],
            ],
        )
    )
    lines.append("")

    request_enum = spec["enums"]["request-opcode"]
    req_prefix = request_enum["prefix"]
    req_rows: list[list[str]] = []
    for member in request_enum["members"]:
        if "reserved" in member:
            req_rows.append(
                [
                    str(member["reserved"]),
                    "*(reserved)*",
                    "—",
                    "0",
                    member.get("reason", ""),
                ]
            )
            continue
        name = member["name"]
        since = member.get("since")
        notes = member.get("doc", "").strip().replace("\n", " ")
        if since is not None:
            notes = f"since v{since}. {notes}".strip()
        req_rows.append(
            [
                str(member["value"]),
                f"`{req_prefix}{name}`",
                _request_body_summary(name, layouts_by_opcode, layouts, json_groups),
                REQUEST_FD_COUNTS.get(name, "0"),
                notes,
            ]
        )
    lines.extend(["## Request opcodes (client -> producer)", ""])
    lines.extend(
        _emit_md_table(["Opcode", "Name", "Body", "FDs", "Notes"], req_rows)
    )
    lines.append("")

    event_enum = spec["enums"]["event-opcode"]
    evt_prefix = event_enum["prefix"]
    evt_rows: list[list[str]] = []
    for member in event_enum["members"]:
        if "reserved" in member:
            evt_rows.append(
                [
                    str(member["reserved"]),
                    "*(reserved)*",
                    "—",
                    "0",
                    member.get("reason", ""),
                ]
            )
            continue
        name = member["name"]
        notes = member.get("doc", "").strip().replace("\n", " ")
        since = member.get("since")
        if since is not None:
            notes = f"since v{since}. {notes}".strip()
        evt_rows.append(
            [
                str(member["value"]),
                f"`{evt_prefix}{name}`",
                _event_body_summary(name, layouts_by_opcode, layouts),
                EVENT_FD_COUNTS.get(name, "0"),
                notes,
            ]
        )
    lines.extend(["## Event opcodes (producer -> client)", ""])
    lines.extend(_emit_md_table(["Opcode", "Name", "Body", "FDs", "Notes"], evt_rows))
    lines.append("")

    control_enum = spec["enums"]["control-opcode"]
    ctl_prefix = control_enum["prefix"]
    ctl_rows: list[list[str]] = []
    for member in control_enum["members"]:
        if "reserved" in member:
            ctl_rows.append(
                [
                    str(member["reserved"]),
                    "*(reserved)*",
                    "—",
                    "—",
                    member.get("reason", ""),
                ]
            )
            continue
        name = member["name"]
        direction = CONTROL_DIRECTION.get(name, "producer -> controller")
        ctl_rows.append(
            [
                str(member["value"]),
                f"`{ctl_prefix}{name}`",
                direction,
                member.get("doc", "").strip(),
            ]
        )
    lines.extend(["## Control opcodes", ""])
    lines.extend(_emit_md_table(["Opcode", "Name", "Direction", "Notes"], ctl_rows))
    lines.append("")

    error_enum = spec["enums"]["error-code"]
    err_prefix = error_enum["prefix"]
    err_rows: list[list[str]] = []
    for member in error_enum["members"]:
        if "reserved" in member or "alias-of" in member:
            continue
        err_rows.append(
            [str(member["value"]), f"`{err_prefix}{member['name']}`", ""]
        )
    lines.extend(["## Error codes (`EVT_ERROR` JSON `code`)", ""])
    lines.extend(_emit_md_table(["Code", "Name", "Notes"], err_rows))
    lines.append("")

    segments = spec.get("errors", {}).get("segments", [])
    if segments:
        seg_rows = [
            [
                f"{segment['range'][0]}..{segment['range'][1]}",
                segment["domain"],
                "yes" if segment.get("terminal") else "no",
            ]
            for segment in segments
        ]
        lines.extend(["## Error code segments", ""])
        lines.extend(
            _emit_md_table(["Range", "Domain", "Terminal (disconnect)"], seg_rows)
        )
        lines.append("")

    bind_failed = spec.get("bind-failed-reasons", {})
    if bind_failed.get("members"):
        prefix = bind_failed.get("prefix", "")
        bf_rows = [
            [str(member["value"]), f"`{prefix}{member['name']}`", member.get("doc", "")]
            for member in bind_failed["members"]
        ]
        lines.extend(["## BIND_FAILED reason codes", ""])
        lines.extend(_emit_md_table(["Value", "Name", "Notes"], bf_rows))
        lines.append("")

    for flag_name, flag_group in spec.get("flags", {}).items():
        prefix = flag_group["prefix"]
        doc = flag_group.get("doc", "")
        flag_rows = [
            [
                str(member["value"]),
                f"`{prefix}{member['name']}`",
                member.get("doc", ""),
            ]
            for member in flag_group["members"]
        ]
        lines.extend([f"## Window flags (`{flag_name}`)", ""])
        if doc:
            lines.append(doc)
            lines.append("")
        lines.extend(_emit_md_table(["Bit", "Name", "Notes"], flag_rows))
        lines.append("")

    role_enum = spec["enums"]["client-role"]
    role_prefix = role_enum["prefix"]
    role_values: dict[str, int] = {}
    for member in role_enum["members"]:
        if "name" in member and "value" in member:
            role_values[member["name"]] = member["value"]
    role_rows: list[list[str]] = []
    for member in role_enum["members"]:
        if "reserved" in member:
            continue
        alias = member.get("alias-of")
        if alias:
            value = role_values[alias]
            role_rows.append(
                [
                    str(value),
                    f"`{role_prefix}{member['name']}`",
                    f"alias of `{role_prefix}{alias}`",
                ]
            )
            continue
        role_rows.append(
            [
                str(member["value"]),
                f"`{role_prefix}{member['name']}`",
                member.get("doc", ""),
            ]
        )
    lines.extend(["## Client roles (HELLO `role`)", ""])
    lines.extend(_emit_md_table(["Value", "Name", "Notes"], role_rows))
    lines.append("")

    for enum_key in ("button-state", "axis-source", "result"):
        enum_spec = spec["enums"][enum_key]
        prefix = enum_spec["prefix"]
        title = enum_key.replace("-", " ").title()
        enum_rows = [
            [str(member["value"]), f"`{prefix}{member['name']}`", member.get("doc", "")]
            for member in enum_spec["members"]
            if "reserved" not in member and "alias-of" not in member
        ]
        lines.extend([f"## {title}", ""])
        lines.extend(_emit_md_table(["Value", "Name", "Notes"], enum_rows))
        lines.append("")

    lines.extend(["## Binary message layouts", ""])
    for layout in layouts:
        lines.extend(_emit_binary_layout_section(layout, spec_messages))

    lines.extend(["## JSON wire field names", ""])
    for group in sorted(json_groups):
        rows = [
            [f"`{field}`", f"`{wire}`"]
            for field, wire in sorted(json_groups[group].items())
        ]
        lines.extend([f"### `{group}`", ""])
        lines.extend(_emit_md_table(["Logical id", "Wire name"], rows))
        lines.append("")

    if config_members:
        schema_rows: list[list[str]] = []
        for member in config_members:
            aliases = member.get("camel", "")
            schema_rows.append(
                [
                    f"`{member['kebab']}`",
                    f"`{aliases}`" if aliases else "",
                    member["type"],
                ]
            )
        lines.extend(["## CONTROL_SET_STATE schema keys", ""])
        lines.extend(
            _emit_md_table(["Canonical key", "Accepted alias", "Type"], schema_rows)
        )
        lines.append("")

    return "\n".join(lines)


def load_spec(path: Path) -> dict[str, Any]:
    with path.open("rb") as handle:
        return tomllib.load(handle)


def _constant_value(raw: int | str | dict[str, Any]) -> int | str:
    if isinstance(raw, dict):
        return raw["value"]
    return raw


def _resolve_enum_members(
    members: list[dict[str, Any]], prefix: str
) -> dict[str, int | str]:
    named: dict[str, int] = {}
    aliases: list[tuple[str, str]] = []
    seen_values: set[int] = set()

    for member in members:
        if "reserved" in member:
            slot = member["reserved"]
            if slot in seen_values:
                raise ValueError(f"reserved slot {slot} conflicts with existing value")
            seen_values.add(slot)
            continue
        if "alias-of" in member:
            aliases.append((member["name"], member["alias-of"]))
            continue
        name = member["name"]
        value = member["value"]
        if value in seen_values:
            raise ValueError(f"duplicate enum value {value} for {prefix}{name}")
        seen_values.add(value)
        named[name] = value

    out: dict[str, int | str] = {f"{prefix}{name}": value for name, value in named.items()}
    for alias_name, target_name in aliases:
        if target_name not in named:
            raise ValueError(f"alias {alias_name} references unknown member {target_name}")
        out[f"{prefix}{alias_name}"] = named[target_name]
    return out


def validate_spec(spec: dict[str, Any], layouts: list[MessageLayout]) -> None:
    protocol = spec["protocol"]
    max_version = protocol["version"]

    for section in spec.get("enums", {}).values():
        for member in section.get("members", []):
            since = member.get("since")
            if since is not None and since > max_version:
                raise ValueError(
                    f"since={since} exceeds protocol.version={max_version} "
                    f"for {section.get('prefix', '')}{member.get('name', '')}"
                )

    error_members = spec.get("enums", {}).get("error-code", {}).get("members", [])
    segments = spec.get("errors", {}).get("segments", [])
    for member in error_members:
        if "reserved" in member or "alias-of" in member:
            continue
        code = member["value"]
        matched = any(
            segment["range"][0] <= code <= segment["range"][1] for segment in segments
        )
        if not matched:
            raise ValueError(
                f"error code {code} ({member['name']}) falls outside declared segments"
            )

    for layout in layouts:
        if layout.fixed_size is None:
            continue
        if layout.bytes_key is None:
            raise ValueError(f"fixed-size message {layout.slug} missing bytes constant mapping")


def build_defines(spec: dict[str, Any], layouts: list[MessageLayout]) -> dict[str, int | str]:
    protocol = spec["protocol"]
    defines: dict[str, int | str] = {
        "VIVID_DISPLAY_PROTOCOL_NAME": protocol["name"],
        "VIVID_DISPLAY_PROTOCOL_VERSION": protocol["version"],
        "VIVID_DISPLAY_PROTOCOL_MIN_SUPPORTED": protocol["min-supported"],
    }

    for key, raw in spec.get("constants", {}).items():
        defines[f"VIVID_DISPLAY_{key}"] = _constant_value(raw)

    bind_failed = spec.get("bind-failed-reasons", {})
    prefix = bind_failed.get("prefix", "")
    for member in bind_failed.get("members", []):
        defines[f"{prefix}{member['name']}"] = member["value"]

    for flag_group in spec.get("flags", {}).values():
        flag_prefix = flag_group["prefix"]
        for member in flag_group["members"]:
            defines[f"{flag_prefix}{member['name']}"] = member["value"]

    for enum_spec in spec.get("enums", {}).values():
        defines.update(_resolve_enum_members(enum_spec["members"], enum_spec["prefix"]))

    for layout in layouts:
        if layout.bytes_key and layout.fixed_size is not None:
            defines[f"VIVID_DISPLAY_{layout.bytes_key}"] = layout.fixed_size

    return defines


def _format_c_scalar_define(name: str, key: str, value: int | str) -> str:
    if isinstance(value, str):
        return f'#define {name} "{value}"'
    if key in SIZE_T_CONSTANTS:
        return f"#define {name} ((size_t){value}u)"
    if key in INT_CONSTANTS:
        return f"#define {name} {value}"
    return f"#define {name} {value}u"


def _emit_c_enum(enum_spec: dict[str, Any], *, segment_comments: bool = False) -> list[str]:
    prefix = enum_spec["prefix"]
    c_name = enum_spec["c-name"]
    lines = ["typedef enum", "{"]
    emitted_segments: set[tuple[int, int]] = set()

    for member in enum_spec["members"]:
        if "reserved" in member:
            continue

        if "alias-of" in member:
            target = f"{prefix}{member['alias-of']}"
            lines.append(f"    {prefix}{member['name']} = {target},")
            continue

        value = member["value"]
        if segment_comments:
            for bounds, comment in ERROR_SEGMENT_COMMENTS.items():
                if bounds[0] <= value <= bounds[1] and bounds not in emitted_segments:
                    lines.append(f"    {comment}")
                    emitted_segments.add(bounds)
                    break

        doc = member.get("doc", "")
        if doc and "\n" in doc:
            lines.append("    /*")
            for line in doc.strip().splitlines():
                if line.strip():
                    lines.append(f"     * {line.rstrip()}")
                else:
                    lines.append("     *")
            lines.append("     */")

        suffix = ""
        if doc and "\n" not in doc:
            suffix = f" /* {doc} */"

        lines.append(f"    {prefix}{member['name']} = {value},{suffix}")

    lines.append(f"}} {c_name};")
    return lines


def emit_c_ids(spec: dict[str, Any], layouts: list[MessageLayout]) -> str:
    protocol = spec["protocol"]
    lines = [
        GENERATED_BANNER,
        "",
        "#ifndef VIVID_DISPLAY_PROTOCOL_IDS_H",
        "#define VIVID_DISPLAY_PROTOCOL_IDS_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f'#define VIVID_DISPLAY_PROTOCOL_NAME "{protocol["name"]}"',
        f'#define VIVID_DISPLAY_PROTOCOL_VERSION {protocol["version"]}u',
        f"#define VIVID_DISPLAY_PROTOCOL_MIN_SUPPORTED {protocol['min-supported']}u",
        "",
        "/*",
        " * Protocol version history (negotiatedVersion = min(client, producer)):",
    ]
    for entry in spec.get("history", []):
        summary = entry["summary"].strip()
        lines.append(f" * v{entry['version']}  {summary}")
    lines.extend([" */", ""])

    window_schema = _constant_value(spec["constants"]["WINDOW_STATE_SCHEMA_V2"])
    lines.append(f'#define VIVID_DISPLAY_WINDOW_STATE_SCHEMA_V2 "{window_schema}"')
    lines.append("")

    flag_group = spec["flags"]["window"]
    lines.append(f"/* {flag_group['doc'].split(';')[0]} */")
    for member in flag_group["members"]:
        name = f"{flag_group['prefix']}{member['name']}"
        doc = member.get("doc", "")
        suffix = f" /* {doc} */" if doc else ""
        lines.append(f"#define {name} {member['value']}u{suffix}")
    lines.append("/* bits 4..31 reserved: senders must zero them; receivers must ignore them */")
    lines.append("")

    bind_failed = spec["bind-failed-reasons"]
    bind_prefix = bind_failed["prefix"]
    bind_width = max(len(f"{bind_prefix}{member['name']}") for member in bind_failed["members"])
    for member in bind_failed["members"]:
        name = f"{bind_prefix}{member['name']}"
        lines.append(f"#define {name.ljust(bind_width)} {member['value']}u")
    lines.append("")

    for key, raw in spec["constants"].items():
        if key == "WINDOW_STATE_SCHEMA_V2":
            continue
        name = f"VIVID_DISPLAY_{key}"
        value = _constant_value(raw)
        lines.append(_format_c_scalar_define(name, key, value))

    for layout in layouts:
        if layout.bytes_key and layout.fixed_size is not None:
            key = layout.bytes_key
            name = f"VIVID_DISPLAY_{key}"
            lines.append(_format_c_scalar_define(name, key, layout.fixed_size))
    lines.append("")

    enums = spec.get("enums", {})
    for index, enum_key in enumerate(ENUM_ORDER):
        if index:
            lines.append("")
        enum_spec = enums[enum_key]
        lines.extend(
            _emit_c_enum(
                enum_spec,
                segment_comments=(enum_key == "error-code"),
            )
        )

    lines.extend(emit_c_codec_section(layouts))
    lines.extend(emit_c_metadata(spec))
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def collect_c_macro_names(spec: dict[str, Any], layouts: list[MessageLayout]) -> list[str]:
    names = [
        "VIVID_DISPLAY_PROTOCOL_NAME",
        "VIVID_DISPLAY_PROTOCOL_VERSION",
        "VIVID_DISPLAY_PROTOCOL_MIN_SUPPORTED",
        "VIVID_DISPLAY_WINDOW_STATE_SCHEMA_V2",
    ]

    flag_group = spec["flags"]["window"]
    for member in flag_group["members"]:
        names.append(f"{flag_group['prefix']}{member['name']}")

    bind_prefix = spec["bind-failed-reasons"]["prefix"]
    for member in spec["bind-failed-reasons"]["members"]:
        names.append(f"{bind_prefix}{member['name']}")

    for key in spec["constants"]:
        if key == "WINDOW_STATE_SCHEMA_V2":
            continue
        names.append(f"VIVID_DISPLAY_{key}")

    for layout in layouts:
        if layout.bytes_key and layout.fixed_size is not None:
            names.append(f"VIVID_DISPLAY_{layout.bytes_key}")

    return sorted(set(names))


def emit_kde_cpp(spec: dict[str, Any], layouts: list[MessageLayout]) -> str:
    lines = [
        GENERATED_BANNER,
        "",
        "#pragma once",
        "",
        '#include "vivid_protocol_constants.hpp"',
        "",
        "extern \"C\" {",
        '#include "vivid_display_protocol.h"',
        "}",
        "",
    ]
    for name in collect_c_macro_names(spec, layouts):
        lines.append(f"#undef {name}")
    lines.append("")
    return "\n".join(lines)


def emit_js(defines: dict[str, int | str]) -> str:
    lines = [GENERATED_BANNER, ""]
    for name in sorted(defines):
        value = defines[name]
        if isinstance(value, str):
            lines.append(f'export const {name} = "{value}";')
        else:
            lines.append(f"export const {name} = {value};")
    return "\n".join(lines) + "\n"


def emit_hpp(defines: dict[str, int | str]) -> str:
    lines = [
        GENERATED_BANNER,
        "",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace vivid::protocol {",
        "",
    ]
    for name in sorted(defines):
        value = defines[name]
        if isinstance(value, str):
            lines.append(f'inline constexpr char {name}[] = "{value}";')
        else:
            lines.append(f"inline constexpr std::uint32_t {name} = {value}u;")
    lines.extend(["", "}  // namespace vivid::protocol", ""])
    return "\n".join(lines)


def emit_py(defines: dict[str, int | str]) -> str:
    lines = [PY_GENERATED_BANNER, ""]
    for name in sorted(defines):
        value = defines[name]
        if isinstance(value, str):
            lines.append(f'{name} = "{value}"')
        else:
            lines.append(f"{name} = {value}")
    return "\n".join(lines) + "\n"


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def sync_bytes(canonical: Path, mirror: Path) -> bool:
    data = canonical.read_bytes()
    if mirror.exists() and mirror.read_bytes() == data:
        return False
    mirror.parent.mkdir(parents=True, exist_ok=True)
    mirror.write_bytes(data)
    return True


def check_bytes(canonical: Path, mirror: Path, label: str) -> bool:
    if not mirror.exists() or canonical.read_bytes() != mirror.read_bytes():
        print(f"stale {label}: {mirror}", file=sys.stderr)
        return True
    return False


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--spec", type=Path, default=SPEC)
    parser.add_argument("--c-ids-out", type=Path, default=PROTO_DIR / "vivid_display_protocol_ids.h")
    parser.add_argument(
        "--gnome-ids-out",
        type=Path,
        default=REPO_ROOT / "consumer/gnome/src/protocol/vivid_display_protocol_ids.h",
    )
    parser.add_argument("--gnome-out", type=Path, required=True)
    parser.add_argument("--gnome-codec-out", type=Path, required=True)
    parser.add_argument("--kde-out", type=Path, required=True)
    parser.add_argument("--kde-cpp-out", type=Path, required=True)
    parser.add_argument("--webui-out", type=Path, required=True)
    parser.add_argument("--webui-codec-out", type=Path, required=True)
    parser.add_argument("--gnome-meta-out", type=Path, required=True)
    parser.add_argument("--kde-meta-out", type=Path, required=True)
    parser.add_argument("--webui-meta-out", type=Path, required=True)
    parser.add_argument("--c-json-out", type=Path, required=True)
    parser.add_argument("--gnome-json-h-out", type=Path, required=True)
    parser.add_argument("--gnome-json-out", type=Path, required=True)
    parser.add_argument("--kde-json-out", type=Path, required=True)
    parser.add_argument("--webui-json-out", type=Path, required=True)
    parser.add_argument("--config-schema-out", type=Path, required=True)
    parser.add_argument("--webui-config-keys-out", type=Path, required=True)
    parser.add_argument(
        "--umbrella-canonical",
        type=Path,
        default=PROTO_DIR / "vivid_display_protocol.h",
    )
    parser.add_argument(
        "--umbrella-gnome",
        type=Path,
        default=REPO_ROOT / "consumer/gnome/src/protocol/vivid_display_protocol.h",
    )
    parser.add_argument(
        "--codec-canonical",
        type=Path,
        default=PROTO_DIR / "vivid_display_codec.c",
    )
    parser.add_argument(
        "--codec-gnome",
        type=Path,
        default=REPO_ROOT / "consumer/gnome/src/protocol/vivid_display_codec.c",
    )
    parser.add_argument(
        "--docs-reference-out",
        type=Path,
        default=REPO_ROOT / "docs/protocols-reference.md",
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    spec = load_spec(args.spec)
    layouts = parse_message_layouts(spec)
    validate_spec(spec, layouts)
    defines = build_defines(spec, layouts)
    json_groups = parse_json_field_groups(spec)
    config_members = parse_config_key_members(spec)

    c_ids = emit_c_ids(spec, layouts)
    outputs = {
        args.c_ids_out: c_ids,
        args.gnome_ids_out: c_ids,
        args.gnome_out: emit_js(defines),
        args.gnome_codec_out: emit_js_codec(layouts, defines),
        args.kde_out: emit_hpp(defines),
        args.kde_cpp_out: emit_kde_cpp(spec, layouts),
        args.webui_out: emit_py(defines),
        args.webui_codec_out: emit_py_codec(layouts),
        args.gnome_meta_out: emit_js_meta(spec),
        args.kde_meta_out: emit_hpp_meta(spec),
        args.webui_meta_out: emit_py_meta(spec),
        args.c_json_out: emit_c_json_fields(json_groups),
        args.gnome_json_h_out: emit_c_json_fields(json_groups),
        args.gnome_json_out: emit_js_json_fields(json_groups),
        args.kde_json_out: emit_hpp_json_fields(json_groups),
        args.webui_json_out: emit_py_json_fields(json_groups),
        args.config_schema_out: emit_c_config_schema(config_members),
        args.webui_config_keys_out: emit_py_config_keys(config_members),
        args.docs_reference_out: emit_docs_reference(
            spec, layouts, json_groups, config_members
        ),
    }

    stale = False
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                print(f"stale generated file: {path}", file=sys.stderr)
                stale = True
            continue
        if write_if_changed(path, content):
            print(f"updated {path}")

    if args.check:
        stale = check_bytes(args.umbrella_canonical, args.umbrella_gnome, "umbrella header") or stale
        stale = check_bytes(args.codec_canonical, args.codec_gnome, "codec.c") or stale
    else:
        if sync_bytes(args.umbrella_canonical, args.umbrella_gnome):
            print(f"updated {args.umbrella_gnome}")
        if sync_bytes(args.codec_canonical, args.codec_gnome):
            print(f"updated {args.codec_gnome}")

    if args.check and stale:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
