/* generated by protocol_gen.py from vivid_renderer_v1.toml — do not edit */

#ifndef VIVID_RENDERER_PROTOCOL_H
#define VIVID_RENDERER_PROTOCOL_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

#define VIVID_RENDERER_PROTOCOL_NAME "vivid-renderer-v1"
#define VIVID_RENDERER_PROTOCOL_MAGIC UINT32_C(0x31525656)
#define VIVID_RENDERER_PROTOCOL_VERSION 1u
#define VIVID_RENDERER_SPAWN_VERSION 1u
#define VIVID_RENDERER_HEADER_BYTES 28u
#define VIVID_RENDERER_MAX_PACKET_BYTES 262144u
#define VIVID_RENDERER_MAX_PAYLOAD_BYTES 262116u
#define VIVID_RENDERER_MAX_FDS_PER_MESSAGE 32u
#define VIVID_RENDERER_MAX_RENDERER_ID_BYTES 128u
#define VIVID_RENDERER_MAX_PROJECT_PATH_BYTES 4096u
#define VIVID_RENDERER_MAX_RENDER_NODE_BYTES 256u
#define VIVID_RENDERER_MAX_SETTINGS_JSON_BYTES 65536u
#define VIVID_RENDERER_MAX_PROPERTIES_JSON_BYTES 65536u
#define VIVID_RENDERER_MAX_MEDIA_STATE_JSON_BYTES 65536u
#define VIVID_RENDERER_MAX_STATE_JSON_BYTES 65536u
#define VIVID_RENDERER_MAX_DIAGNOSTIC_BYTES 4096u
#define VIVID_RENDERER_MAX_FORMAT_CAPS 128u
#define VIVID_RENDERER_MAX_POOL_BUFFERS 8u
#define VIVID_RENDERER_MAX_PLANES 4u
#define VIVID_RENDERER_MAX_AUDIO_SAMPLES 128u
#define VIVID_RENDERER_UUID_BYTES 16u
#define VIVID_RENDERER_LIFECYCLE_HELLO_TIMEOUT_MS 5000u
#define VIVID_RENDERER_LIFECYCLE_INIT_TIMEOUT_MS 60000u
#define VIVID_RENDERER_LIFECYCLE_QUIESCE_TIMEOUT_MS 5000u
#define VIVID_RENDERER_LIFECYCLE_SHUTDOWN_TIMEOUT_MS 10000u
#define VIVID_RENDERER_LIFECYCLE_TERM_TIMEOUT_MS 3000u
#define VIVID_RENDERER_BACKEND_READY_POLL_INTERVAL_MS 5u

#define VIVID_RENDERER_HEADER_MAGIC_OFFSET 0u
#define VIVID_RENDERER_HEADER_VERSION_OFFSET 4u
#define VIVID_RENDERER_HEADER_OPCODE_OFFSET 6u
#define VIVID_RENDERER_HEADER_PAYLOAD_LENGTH_OFFSET 8u
#define VIVID_RENDERER_HEADER_REQUEST_ID_OFFSET 12u
#define VIVID_RENDERER_HEADER_RENDERER_INSTANCE_ID_OFFSET 20u

typedef enum
{
    VIVID_RENDERER_KIND_SCENE = 1,
    VIVID_RENDERER_KIND_WEB = 2,
    VIVID_RENDERER_KIND_VIDEO = 3,
} VividRendererKind;

typedef enum
{
    VIVID_RENDERER_MEMORY_SOURCE_GPU_NATIVE = 0,
    VIVID_RENDERER_MEMORY_SOURCE_GPU_LINEAR = 1,
    VIVID_RENDERER_MEMORY_SOURCE_DMABUF_HEAP_RESERVED = 2,
} VividRendererMemorySource;

typedef enum
{
    VIVID_RENDERER_SYNC_CAP_IMPLICIT = 1,
    VIVID_RENDERER_SYNC_CAP_SYNCOBJ_BINARY = 2,
    VIVID_RENDERER_SYNC_CAP_SYNCOBJ_TIMELINE = 4,
} VividRendererSyncCap;

typedef enum
{
    VIVID_RENDERER_MEMORY_HINT_DEVICE_LOCAL = 1,
    VIVID_RENDERER_MEMORY_HINT_HOST_VISIBLE = 2,
    VIVID_RENDERER_MEMORY_HINT_SCANOUT_CAPABLE = 4,
    VIVID_RENDERER_MEMORY_HINT_PROTECTED = 8,
    VIVID_RENDERER_MEMORY_HINT_LINEAR_ONLY_RESERVED = 16,
} VividRendererMemoryHint;

typedef enum
{
    VIVID_RENDERER_COLOR_CAP_SRGB = 1,
    VIVID_RENDERER_COLOR_CAP_LINEAR = 2,
    VIVID_RENDERER_COLOR_CAP_BT601 = 4,
    VIVID_RENDERER_COLOR_CAP_BT709 = 8,
    VIVID_RENDERER_COLOR_CAP_BT2020 = 16,
    VIVID_RENDERER_COLOR_CAP_RANGE_FULL = 32,
    VIVID_RENDERER_COLOR_CAP_RANGE_LIMITED = 64,
    VIVID_RENDERER_COLOR_CAP_ALPHA_PREMULTIPLIED = 128,
    VIVID_RENDERER_COLOR_CAP_ALPHA_STRAIGHT = 256,
} VividRendererColorCap;

typedef enum
{
    VIVID_RENDERER_RELAY_MODE_SHADOW_COPY = 1,
} VividRendererRelayMode;

typedef enum
{
    VIVID_RENDERER_BUFFER_FLAG_PREMULTIPLIED = 1,
} VividRendererBufferFlag;

typedef enum
{
    VIVID_RENDERER_PLAYBACK_FLAG_PLAYING = 1,
    VIVID_RENDERER_PLAYBACK_FLAG_MUTED = 2,
} VividRendererPlaybackFlag;

typedef enum
{
    VIVID_RENDERER_STAGE_BOOT = 1,
    VIVID_RENDERER_STAGE_HANDSHAKE = 2,
    VIVID_RENDERER_STAGE_BACKEND_INIT = 3,
    VIVID_RENDERER_STAGE_NEGOTIATION = 4,
    VIVID_RENDERER_STAGE_RUNNING = 5,
    VIVID_RENDERER_STAGE_QUIESCE = 6,
    VIVID_RENDERER_STAGE_SHUTDOWN = 7,
} VividRendererLifecycleStage;

typedef enum
{
    VIVID_RENDERER_ERROR_PROTOCOL = 1,
    VIVID_RENDERER_ERROR_SPAWN_VERSION = 2,
    VIVID_RENDERER_ERROR_IDENTITY_MISMATCH = 3,
    VIVID_RENDERER_ERROR_BACKEND_INIT = 100,
    VIVID_RENDERER_ERROR_FORMAT_NEGOTIATION = 200,
    VIVID_RENDERER_ERROR_BUFFER_ALLOCATION = 201,
    VIVID_RENDERER_ERROR_FRAME_PRODUCTION = 300,
    VIVID_RENDERER_ERROR_QUIESCE = 400,
    VIVID_RENDERER_ERROR_SHUTDOWN = 500,
} VividRendererErrorCode;

typedef enum
{
    VIVID_RENDERER_DIRECTION_DAEMON_TO_WORKER = 1,
    VIVID_RENDERER_DIRECTION_WORKER_TO_DAEMON = 2,
} VividRendererMessageDirection;

typedef enum
{
    VIVID_RENDERER_REQUEST_ID_ZERO = 1,
    VIVID_RENDERER_REQUEST_ID_REQUIRED = 2,
    VIVID_RENDERER_REQUEST_ID_ANY = 3,
} VividRendererRequestIdPolicy;

typedef enum
{
    VIVID_RENDERER_MSG_INIT = 0x0001,
    VIVID_RENDERER_MSG_NEGOTIATE_BUFFERS = 0x0002,
    VIVID_RENDERER_MSG_SET_RUNTIME = 0x0003,
    VIVID_RENDERER_MSG_SET_PLAYBACK = 0x0004,
    VIVID_RENDERER_MSG_SET_MEDIA_STATE = 0x0005,
    VIVID_RENDERER_MSG_SET_AUDIO_SAMPLES = 0x0006,
    VIVID_RENDERER_MSG_POINTER_MOTION = 0x0007,
    VIVID_RENDERER_MSG_POINTER_BUTTON = 0x0008,
    VIVID_RENDERER_MSG_POINTER_AXIS = 0x0009,
    VIVID_RENDERER_MSG_QUIESCE = 0x000a,
    VIVID_RENDERER_MSG_SHUTDOWN = 0x000b,
    VIVID_RENDERER_MSG_HELLO = 0x8001,
    VIVID_RENDERER_MSG_READY = 0x8002,
    VIVID_RENDERER_MSG_FORMAT_CAPS = 0x8003,
    VIVID_RENDERER_MSG_RELEASE_TIMELINE = 0x8004,
    VIVID_RENDERER_MSG_BIND_BUFFERS = 0x8005,
    VIVID_RENDERER_MSG_FRAME_READY = 0x8006,
    VIVID_RENDERER_MSG_STATE_CHANGED = 0x8007,
    VIVID_RENDERER_MSG_BIND_FAILED = 0x8008,
    VIVID_RENDERER_MSG_ERROR = 0x8009,
    VIVID_RENDERER_MSG_QUIESCED = 0x800a,
} VividRendererOpcode;

#define VIVID_RENDERER_FORMAT_CAPABILITY_BYTES 16u
#define VIVID_RENDERER_FORMAT_CAPABILITY_FOURCC_OFFSET 0u
#define VIVID_RENDERER_FORMAT_CAPABILITY_PLANE_COUNT_OFFSET 4u
#define VIVID_RENDERER_FORMAT_CAPABILITY_MODIFIER_OFFSET 8u

#define VIVID_RENDERER_BUFFER_PLANE_BYTES 16u
#define VIVID_RENDERER_BUFFER_PLANE_STRIDE_OFFSET 0u
#define VIVID_RENDERER_BUFFER_PLANE_OFFSET_OFFSET 4u
#define VIVID_RENDERER_BUFFER_PLANE_SIZE_OFFSET 8u

#define VIVID_RENDERER_INIT_FIXED_BYTES 64u
#define VIVID_RENDERER_INIT_MAX_PAYLOAD_BYTES 135616u
#define VIVID_RENDERER_INIT_FD_COUNT_MIN 0u
#define VIVID_RENDERER_INIT_FD_COUNT_MAX 0u
#define VIVID_RENDERER_INIT_RENDERER_KIND_OFFSET 0u
#define VIVID_RENDERER_INIT_WIDTH_OFFSET 4u
#define VIVID_RENDERER_INIT_HEIGHT_OFFSET 8u
#define VIVID_RENDERER_INIT_SCALE_OFFSET 12u
#define VIVID_RENDERER_INIT_FPS_OFFSET 16u
#define VIVID_RENDERER_INIT_PLAYBACK_FLAGS_OFFSET 20u
#define VIVID_RENDERER_INIT_VOLUME_OFFSET 24u
#define VIVID_RENDERER_INIT_EXPECTED_DEVICE_UUID_OFFSET 28u
#define VIVID_RENDERER_INIT_RENDERER_ID_LENGTH_OFFSET 44u
#define VIVID_RENDERER_INIT_PROJECT_PATH_LENGTH_OFFSET 48u
#define VIVID_RENDERER_INIT_RENDER_NODE_LENGTH_OFFSET 52u
#define VIVID_RENDERER_INIT_SETTINGS_JSON_LENGTH_OFFSET 56u
#define VIVID_RENDERER_INIT_PROPERTIES_JSON_LENGTH_OFFSET 60u

#define VIVID_RENDERER_NEGOTIATE_BUFFERS_FIXED_BYTES 36u
#define VIVID_RENDERER_NEGOTIATE_BUFFERS_MAX_PAYLOAD_BYTES 36u
#define VIVID_RENDERER_NEGOTIATE_BUFFERS_FD_COUNT_MIN 0u
#define VIVID_RENDERER_NEGOTIATE_BUFFERS_FD_COUNT_MAX 0u
#define VIVID_RENDERER_NEGOTIATE_BUFFERS_FOURCC_OFFSET 0u
#define VIVID_RENDERER_NEGOTIATE_BUFFERS_WIDTH_OFFSET 4u
#define VIVID_RENDERER_NEGOTIATE_BUFFERS_HEIGHT_OFFSET 8u
#define VIVID_RENDERER_NEGOTIATE_BUFFERS_PLANE_COUNT_OFFSET 12u
#define VIVID_RENDERER_NEGOTIATE_BUFFERS_POOL_SIZE_OFFSET 16u
#define VIVID_RENDERER_NEGOTIATE_BUFFERS_MEMORY_SOURCE_OFFSET 20u
#define VIVID_RENDERER_NEGOTIATE_BUFFERS_SYNC_MODE_OFFSET 24u
#define VIVID_RENDERER_NEGOTIATE_BUFFERS_MODIFIER_OFFSET 28u

#define VIVID_RENDERER_SET_RUNTIME_FIXED_BYTES 4u
#define VIVID_RENDERER_SET_RUNTIME_MAX_PAYLOAD_BYTES 65540u
#define VIVID_RENDERER_SET_RUNTIME_FD_COUNT_MIN 0u
#define VIVID_RENDERER_SET_RUNTIME_FD_COUNT_MAX 0u
#define VIVID_RENDERER_SET_RUNTIME_SETTINGS_JSON_LENGTH_OFFSET 0u

#define VIVID_RENDERER_SET_PLAYBACK_FIXED_BYTES 12u
#define VIVID_RENDERER_SET_PLAYBACK_MAX_PAYLOAD_BYTES 12u
#define VIVID_RENDERER_SET_PLAYBACK_FD_COUNT_MIN 0u
#define VIVID_RENDERER_SET_PLAYBACK_FD_COUNT_MAX 0u
#define VIVID_RENDERER_SET_PLAYBACK_PLAYING_OFFSET 0u
#define VIVID_RENDERER_SET_PLAYBACK_MUTED_OFFSET 4u
#define VIVID_RENDERER_SET_PLAYBACK_VOLUME_OFFSET 8u

#define VIVID_RENDERER_SET_MEDIA_STATE_FIXED_BYTES 4u
#define VIVID_RENDERER_SET_MEDIA_STATE_MAX_PAYLOAD_BYTES 65540u
#define VIVID_RENDERER_SET_MEDIA_STATE_FD_COUNT_MIN 0u
#define VIVID_RENDERER_SET_MEDIA_STATE_FD_COUNT_MAX 0u
#define VIVID_RENDERER_SET_MEDIA_STATE_MEDIA_STATE_JSON_LENGTH_OFFSET 0u

#define VIVID_RENDERER_SET_AUDIO_SAMPLES_FIXED_BYTES 12u
#define VIVID_RENDERER_SET_AUDIO_SAMPLES_MAX_PAYLOAD_BYTES 524u
#define VIVID_RENDERER_SET_AUDIO_SAMPLES_FD_COUNT_MIN 0u
#define VIVID_RENDERER_SET_AUDIO_SAMPLES_FD_COUNT_MAX 0u
#define VIVID_RENDERER_SET_AUDIO_SAMPLES_COUNT_OFFSET 0u
#define VIVID_RENDERER_SET_AUDIO_SAMPLES_TIME_USEC_OFFSET 4u

#define VIVID_RENDERER_POINTER_MOTION_FIXED_BYTES 24u
#define VIVID_RENDERER_POINTER_MOTION_MAX_PAYLOAD_BYTES 24u
#define VIVID_RENDERER_POINTER_MOTION_FD_COUNT_MIN 0u
#define VIVID_RENDERER_POINTER_MOTION_FD_COUNT_MAX 0u
#define VIVID_RENDERER_POINTER_MOTION_X_OFFSET 0u
#define VIVID_RENDERER_POINTER_MOTION_Y_OFFSET 8u
#define VIVID_RENDERER_POINTER_MOTION_TIME_USEC_OFFSET 16u

#define VIVID_RENDERER_POINTER_BUTTON_FIXED_BYTES 32u
#define VIVID_RENDERER_POINTER_BUTTON_MAX_PAYLOAD_BYTES 32u
#define VIVID_RENDERER_POINTER_BUTTON_FD_COUNT_MIN 0u
#define VIVID_RENDERER_POINTER_BUTTON_FD_COUNT_MAX 0u
#define VIVID_RENDERER_POINTER_BUTTON_X_OFFSET 0u
#define VIVID_RENDERER_POINTER_BUTTON_Y_OFFSET 8u
#define VIVID_RENDERER_POINTER_BUTTON_BUTTON_OFFSET 16u
#define VIVID_RENDERER_POINTER_BUTTON_STATE_OFFSET 20u
#define VIVID_RENDERER_POINTER_BUTTON_TIME_USEC_OFFSET 24u

#define VIVID_RENDERER_POINTER_AXIS_FIXED_BYTES 44u
#define VIVID_RENDERER_POINTER_AXIS_MAX_PAYLOAD_BYTES 44u
#define VIVID_RENDERER_POINTER_AXIS_FD_COUNT_MIN 0u
#define VIVID_RENDERER_POINTER_AXIS_FD_COUNT_MAX 0u
#define VIVID_RENDERER_POINTER_AXIS_X_OFFSET 0u
#define VIVID_RENDERER_POINTER_AXIS_Y_OFFSET 8u
#define VIVID_RENDERER_POINTER_AXIS_DELTA_X_OFFSET 16u
#define VIVID_RENDERER_POINTER_AXIS_DELTA_Y_OFFSET 24u
#define VIVID_RENDERER_POINTER_AXIS_SOURCE_OFFSET 32u
#define VIVID_RENDERER_POINTER_AXIS_TIME_USEC_OFFSET 36u

#define VIVID_RENDERER_QUIESCE_FIXED_BYTES 0u
#define VIVID_RENDERER_QUIESCE_MAX_PAYLOAD_BYTES 0u
#define VIVID_RENDERER_QUIESCE_FD_COUNT_MIN 0u
#define VIVID_RENDERER_QUIESCE_FD_COUNT_MAX 0u

#define VIVID_RENDERER_SHUTDOWN_FIXED_BYTES 0u
#define VIVID_RENDERER_SHUTDOWN_MAX_PAYLOAD_BYTES 0u
#define VIVID_RENDERER_SHUTDOWN_FD_COUNT_MIN 0u
#define VIVID_RENDERER_SHUTDOWN_FD_COUNT_MAX 0u

#define VIVID_RENDERER_HELLO_FIXED_BYTES 16u
#define VIVID_RENDERER_HELLO_MAX_PAYLOAD_BYTES 144u
#define VIVID_RENDERER_HELLO_FD_COUNT_MIN 0u
#define VIVID_RENDERER_HELLO_FD_COUNT_MAX 0u
#define VIVID_RENDERER_HELLO_SPAWN_VERSION_OFFSET 0u
#define VIVID_RENDERER_HELLO_RENDERER_KIND_OFFSET 4u
#define VIVID_RENDERER_HELLO_PID_OFFSET 8u
#define VIVID_RENDERER_HELLO_RENDERER_ID_LENGTH_OFFSET 12u

#define VIVID_RENDERER_READY_FIXED_BYTES 44u
#define VIVID_RENDERER_READY_MAX_PAYLOAD_BYTES 300u
#define VIVID_RENDERER_READY_FD_COUNT_MIN 0u
#define VIVID_RENDERER_READY_FD_COUNT_MAX 0u
#define VIVID_RENDERER_READY_DEVICE_UUID_OFFSET 0u
#define VIVID_RENDERER_READY_DRIVER_UUID_OFFSET 16u
#define VIVID_RENDERER_READY_DRM_RENDER_MAJOR_OFFSET 32u
#define VIVID_RENDERER_READY_DRM_RENDER_MINOR_OFFSET 36u
#define VIVID_RENDERER_READY_RENDER_NODE_LENGTH_OFFSET 40u

#define VIVID_RENDERER_FORMAT_CAPS_FIXED_BYTES 36u
#define VIVID_RENDERER_FORMAT_CAPS_MAX_PAYLOAD_BYTES 2084u
#define VIVID_RENDERER_FORMAT_CAPS_FD_COUNT_MIN 0u
#define VIVID_RENDERER_FORMAT_CAPS_FD_COUNT_MAX 0u
#define VIVID_RENDERER_FORMAT_CAPS_MEMORY_HINTS_OFFSET 0u
#define VIVID_RENDERER_FORMAT_CAPS_SYNC_CAPS_OFFSET 4u
#define VIVID_RENDERER_FORMAT_CAPS_COLOR_CAPS_OFFSET 8u
#define VIVID_RENDERER_FORMAT_CAPS_RELAY_MODES_OFFSET 12u
#define VIVID_RENDERER_FORMAT_CAPS_EXTENT_MAX_WIDTH_OFFSET 16u
#define VIVID_RENDERER_FORMAT_CAPS_EXTENT_MAX_HEIGHT_OFFSET 20u
#define VIVID_RENDERER_FORMAT_CAPS_POOL_SIZE_MIN_OFFSET 24u
#define VIVID_RENDERER_FORMAT_CAPS_POOL_SIZE_MAX_OFFSET 28u
#define VIVID_RENDERER_FORMAT_CAPS_CAPABILITY_COUNT_OFFSET 32u

#define VIVID_RENDERER_RELEASE_TIMELINE_FIXED_BYTES 0u
#define VIVID_RENDERER_RELEASE_TIMELINE_MAX_PAYLOAD_BYTES 0u
#define VIVID_RENDERER_RELEASE_TIMELINE_FD_COUNT_MIN 1u
#define VIVID_RENDERER_RELEASE_TIMELINE_FD_COUNT_MAX 1u

#define VIVID_RENDERER_BIND_BUFFERS_FIXED_BYTES 44u
#define VIVID_RENDERER_BIND_BUFFERS_MAX_PAYLOAD_BYTES 556u
#define VIVID_RENDERER_BIND_BUFFERS_FD_COUNT_MIN 0u
#define VIVID_RENDERER_BIND_BUFFERS_FD_COUNT_MAX 32u
#define VIVID_RENDERER_BIND_BUFFERS_POOL_GENERATION_OFFSET 0u
#define VIVID_RENDERER_BIND_BUFFERS_FOURCC_OFFSET 8u
#define VIVID_RENDERER_BIND_BUFFERS_WIDTH_OFFSET 12u
#define VIVID_RENDERER_BIND_BUFFERS_HEIGHT_OFFSET 16u
#define VIVID_RENDERER_BIND_BUFFERS_BUFFER_COUNT_OFFSET 20u
#define VIVID_RENDERER_BIND_BUFFERS_PLANE_COUNT_OFFSET 24u
#define VIVID_RENDERER_BIND_BUFFERS_MEMORY_SOURCE_OFFSET 28u
#define VIVID_RENDERER_BIND_BUFFERS_FLAGS_OFFSET 32u
#define VIVID_RENDERER_BIND_BUFFERS_MODIFIER_OFFSET 36u

#define VIVID_RENDERER_FRAME_READY_FIXED_BYTES 40u
#define VIVID_RENDERER_FRAME_READY_MAX_PAYLOAD_BYTES 40u
#define VIVID_RENDERER_FRAME_READY_FD_COUNT_MIN 1u
#define VIVID_RENDERER_FRAME_READY_FD_COUNT_MAX 1u
#define VIVID_RENDERER_FRAME_READY_POOL_GENERATION_OFFSET 0u
#define VIVID_RENDERER_FRAME_READY_BUFFER_INDEX_OFFSET 8u
#define VIVID_RENDERER_FRAME_READY_FLAGS_OFFSET 12u
#define VIVID_RENDERER_FRAME_READY_SEQUENCE_OFFSET 16u
#define VIVID_RENDERER_FRAME_READY_TARGET_TIME_USEC_OFFSET 24u
#define VIVID_RENDERER_FRAME_READY_RELEASE_POINT_OFFSET 32u

#define VIVID_RENDERER_STATE_CHANGED_FIXED_BYTES 20u
#define VIVID_RENDERER_STATE_CHANGED_MAX_PAYLOAD_BYTES 65556u
#define VIVID_RENDERER_STATE_CHANGED_FD_COUNT_MIN 0u
#define VIVID_RENDERER_STATE_CHANGED_FD_COUNT_MAX 0u
#define VIVID_RENDERER_STATE_CHANGED_CLEAR_RED_OFFSET 0u
#define VIVID_RENDERER_STATE_CHANGED_CLEAR_GREEN_OFFSET 4u
#define VIVID_RENDERER_STATE_CHANGED_CLEAR_BLUE_OFFSET 8u
#define VIVID_RENDERER_STATE_CHANGED_CLEAR_ALPHA_OFFSET 12u
#define VIVID_RENDERER_STATE_CHANGED_STATE_JSON_LENGTH_OFFSET 16u

#define VIVID_RENDERER_BIND_FAILED_FIXED_BYTES 12u
#define VIVID_RENDERER_BIND_FAILED_MAX_PAYLOAD_BYTES 4108u
#define VIVID_RENDERER_BIND_FAILED_FD_COUNT_MIN 0u
#define VIVID_RENDERER_BIND_FAILED_FD_COUNT_MAX 0u
#define VIVID_RENDERER_BIND_FAILED_ERROR_CODE_OFFSET 0u
#define VIVID_RENDERER_BIND_FAILED_STAGE_OFFSET 4u
#define VIVID_RENDERER_BIND_FAILED_DIAGNOSTIC_LENGTH_OFFSET 8u

#define VIVID_RENDERER_ERROR_FIXED_BYTES 12u
#define VIVID_RENDERER_ERROR_MAX_PAYLOAD_BYTES 4108u
#define VIVID_RENDERER_ERROR_FD_COUNT_MIN 0u
#define VIVID_RENDERER_ERROR_FD_COUNT_MAX 0u
#define VIVID_RENDERER_ERROR_ERROR_CODE_OFFSET 0u
#define VIVID_RENDERER_ERROR_STAGE_OFFSET 4u
#define VIVID_RENDERER_ERROR_DIAGNOSTIC_LENGTH_OFFSET 8u

#define VIVID_RENDERER_QUIESCED_FIXED_BYTES 0u
#define VIVID_RENDERER_QUIESCED_MAX_PAYLOAD_BYTES 0u
#define VIVID_RENDERER_QUIESCED_FD_COUNT_MIN 0u
#define VIVID_RENDERER_QUIESCED_FD_COUNT_MAX 0u

typedef struct
{
    uint32_t magic;
    uint16_t version;
    uint16_t opcode;
    uint32_t payload_length;
    uint64_t request_id;
    uint64_t renderer_instance_id;
} VividRendererMessageHeader;

typedef struct
{
    uint16_t opcode;
    VividRendererMessageDirection direction;
    VividRendererRequestIdPolicy request_id_policy;
    uint32_t min_payload_bytes;
    uint32_t max_payload_bytes;
    uint32_t min_fd_count;
    uint32_t max_fd_count;
    const char* name;
    const char* reply_to;
} VividRendererMessageDescriptor;

static inline uint8_t vivid_renderer_wire_read_u8(const uint8_t* in)
{
    return in[0];
}

static inline uint16_t vivid_renderer_wire_read_u16(const uint8_t* in)
{
    return (uint16_t)in[0] | ((uint16_t)in[1] << 8);
}

static inline uint32_t vivid_renderer_wire_read_u32(const uint8_t* in)
{
    return (uint32_t)in[0] | ((uint32_t)in[1] << 8) |
           ((uint32_t)in[2] << 16) | ((uint32_t)in[3] << 24);
}

static inline uint64_t vivid_renderer_wire_read_u64(const uint8_t* in)
{
    return (uint64_t)vivid_renderer_wire_read_u32(in) |
           ((uint64_t)vivid_renderer_wire_read_u32(in + 4) << 32);
}

static inline float vivid_renderer_wire_read_f32(const uint8_t* in)
{
    const uint32_t bits = vivid_renderer_wire_read_u32(in);
    float value = 0.0f;
    memcpy(&value, &bits, sizeof(value));
    return value;
}

static inline double vivid_renderer_wire_read_f64(const uint8_t* in)
{
    const uint64_t bits = vivid_renderer_wire_read_u64(in);
    double value = 0.0;
    memcpy(&value, &bits, sizeof(value));
    return value;
}

static inline void vivid_renderer_wire_write_u16(uint8_t* out, uint16_t value)
{
    out[0] = (uint8_t)(value & 0xffu);
    out[1] = (uint8_t)((value >> 8) & 0xffu);
}

static inline void vivid_renderer_wire_write_u32(uint8_t* out, uint32_t value)
{
    out[0] = (uint8_t)(value & 0xffu);
    out[1] = (uint8_t)((value >> 8) & 0xffu);
    out[2] = (uint8_t)((value >> 16) & 0xffu);
    out[3] = (uint8_t)((value >> 24) & 0xffu);
}

static inline void vivid_renderer_wire_write_u64(uint8_t* out, uint64_t value)
{
    vivid_renderer_wire_write_u32(out, (uint32_t)value);
    vivid_renderer_wire_write_u32(out + 4, (uint32_t)(value >> 32));
}

static inline void vivid_renderer_wire_write_f32(uint8_t* out, float value)
{
    uint32_t bits = 0;
    memcpy(&bits, &value, sizeof(bits));
    vivid_renderer_wire_write_u32(out, bits);
}

static inline void vivid_renderer_wire_write_f64(uint8_t* out, double value)
{
    uint64_t bits = 0;
    memcpy(&bits, &value, sizeof(bits));
    vivid_renderer_wire_write_u64(out, bits);
}

static inline bool vivid_renderer_header_encode(
    uint8_t out[VIVID_RENDERER_HEADER_BYTES],
    const VividRendererMessageHeader* header)
{
    if (!out || !header)
        return false;
    vivid_renderer_wire_write_u32(out + VIVID_RENDERER_HEADER_MAGIC_OFFSET, header->magic);
    vivid_renderer_wire_write_u16(out + VIVID_RENDERER_HEADER_VERSION_OFFSET, header->version);
    vivid_renderer_wire_write_u16(out + VIVID_RENDERER_HEADER_OPCODE_OFFSET, header->opcode);
    vivid_renderer_wire_write_u32(out + VIVID_RENDERER_HEADER_PAYLOAD_LENGTH_OFFSET, header->payload_length);
    vivid_renderer_wire_write_u64(out + VIVID_RENDERER_HEADER_REQUEST_ID_OFFSET, header->request_id);
    vivid_renderer_wire_write_u64(out + VIVID_RENDERER_HEADER_RENDERER_INSTANCE_ID_OFFSET, header->renderer_instance_id);
    return true;
}

static inline bool vivid_renderer_header_decode(
    const uint8_t* data, size_t len, VividRendererMessageHeader* header)
{
    if (!data || !header || len != VIVID_RENDERER_HEADER_BYTES)
        return false;
    header->magic = vivid_renderer_wire_read_u32(data + VIVID_RENDERER_HEADER_MAGIC_OFFSET);
    header->version = vivid_renderer_wire_read_u16(data + VIVID_RENDERER_HEADER_VERSION_OFFSET);
    header->opcode = vivid_renderer_wire_read_u16(data + VIVID_RENDERER_HEADER_OPCODE_OFFSET);
    header->payload_length = vivid_renderer_wire_read_u32(data + VIVID_RENDERER_HEADER_PAYLOAD_LENGTH_OFFSET);
    header->request_id = vivid_renderer_wire_read_u64(data + VIVID_RENDERER_HEADER_REQUEST_ID_OFFSET);
    header->renderer_instance_id = vivid_renderer_wire_read_u64(data + VIVID_RENDERER_HEADER_RENDERER_INSTANCE_ID_OFFSET);
    return true;
}

static inline const VividRendererMessageDescriptor*
vivid_renderer_message_descriptor(uint16_t opcode)
{
    switch (opcode) {
    case VIVID_RENDERER_MSG_INIT: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_INIT,
            VIVID_RENDERER_DIRECTION_DAEMON_TO_WORKER,
            VIVID_RENDERER_REQUEST_ID_REQUIRED,
            VIVID_RENDERER_INIT_FIXED_BYTES,
            VIVID_RENDERER_INIT_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_INIT_FD_COUNT_MIN,
            VIVID_RENDERER_INIT_FD_COUNT_MAX,
            "INIT",
            NULL,
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_NEGOTIATE_BUFFERS: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_NEGOTIATE_BUFFERS,
            VIVID_RENDERER_DIRECTION_DAEMON_TO_WORKER,
            VIVID_RENDERER_REQUEST_ID_REQUIRED,
            VIVID_RENDERER_NEGOTIATE_BUFFERS_FIXED_BYTES,
            VIVID_RENDERER_NEGOTIATE_BUFFERS_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_NEGOTIATE_BUFFERS_FD_COUNT_MIN,
            VIVID_RENDERER_NEGOTIATE_BUFFERS_FD_COUNT_MAX,
            "NEGOTIATE_BUFFERS",
            NULL,
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_SET_RUNTIME: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_SET_RUNTIME,
            VIVID_RENDERER_DIRECTION_DAEMON_TO_WORKER,
            VIVID_RENDERER_REQUEST_ID_REQUIRED,
            VIVID_RENDERER_SET_RUNTIME_FIXED_BYTES,
            VIVID_RENDERER_SET_RUNTIME_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_SET_RUNTIME_FD_COUNT_MIN,
            VIVID_RENDERER_SET_RUNTIME_FD_COUNT_MAX,
            "SET_RUNTIME",
            NULL,
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_SET_PLAYBACK: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_SET_PLAYBACK,
            VIVID_RENDERER_DIRECTION_DAEMON_TO_WORKER,
            VIVID_RENDERER_REQUEST_ID_REQUIRED,
            VIVID_RENDERER_SET_PLAYBACK_FIXED_BYTES,
            VIVID_RENDERER_SET_PLAYBACK_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_SET_PLAYBACK_FD_COUNT_MIN,
            VIVID_RENDERER_SET_PLAYBACK_FD_COUNT_MAX,
            "SET_PLAYBACK",
            NULL,
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_SET_MEDIA_STATE: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_SET_MEDIA_STATE,
            VIVID_RENDERER_DIRECTION_DAEMON_TO_WORKER,
            VIVID_RENDERER_REQUEST_ID_REQUIRED,
            VIVID_RENDERER_SET_MEDIA_STATE_FIXED_BYTES,
            VIVID_RENDERER_SET_MEDIA_STATE_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_SET_MEDIA_STATE_FD_COUNT_MIN,
            VIVID_RENDERER_SET_MEDIA_STATE_FD_COUNT_MAX,
            "SET_MEDIA_STATE",
            NULL,
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_SET_AUDIO_SAMPLES: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_SET_AUDIO_SAMPLES,
            VIVID_RENDERER_DIRECTION_DAEMON_TO_WORKER,
            VIVID_RENDERER_REQUEST_ID_ZERO,
            VIVID_RENDERER_SET_AUDIO_SAMPLES_FIXED_BYTES,
            VIVID_RENDERER_SET_AUDIO_SAMPLES_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_SET_AUDIO_SAMPLES_FD_COUNT_MIN,
            VIVID_RENDERER_SET_AUDIO_SAMPLES_FD_COUNT_MAX,
            "SET_AUDIO_SAMPLES",
            NULL,
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_POINTER_MOTION: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_POINTER_MOTION,
            VIVID_RENDERER_DIRECTION_DAEMON_TO_WORKER,
            VIVID_RENDERER_REQUEST_ID_ZERO,
            VIVID_RENDERER_POINTER_MOTION_FIXED_BYTES,
            VIVID_RENDERER_POINTER_MOTION_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_POINTER_MOTION_FD_COUNT_MIN,
            VIVID_RENDERER_POINTER_MOTION_FD_COUNT_MAX,
            "POINTER_MOTION",
            NULL,
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_POINTER_BUTTON: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_POINTER_BUTTON,
            VIVID_RENDERER_DIRECTION_DAEMON_TO_WORKER,
            VIVID_RENDERER_REQUEST_ID_ZERO,
            VIVID_RENDERER_POINTER_BUTTON_FIXED_BYTES,
            VIVID_RENDERER_POINTER_BUTTON_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_POINTER_BUTTON_FD_COUNT_MIN,
            VIVID_RENDERER_POINTER_BUTTON_FD_COUNT_MAX,
            "POINTER_BUTTON",
            NULL,
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_POINTER_AXIS: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_POINTER_AXIS,
            VIVID_RENDERER_DIRECTION_DAEMON_TO_WORKER,
            VIVID_RENDERER_REQUEST_ID_ZERO,
            VIVID_RENDERER_POINTER_AXIS_FIXED_BYTES,
            VIVID_RENDERER_POINTER_AXIS_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_POINTER_AXIS_FD_COUNT_MIN,
            VIVID_RENDERER_POINTER_AXIS_FD_COUNT_MAX,
            "POINTER_AXIS",
            NULL,
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_QUIESCE: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_QUIESCE,
            VIVID_RENDERER_DIRECTION_DAEMON_TO_WORKER,
            VIVID_RENDERER_REQUEST_ID_REQUIRED,
            VIVID_RENDERER_QUIESCE_FIXED_BYTES,
            VIVID_RENDERER_QUIESCE_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_QUIESCE_FD_COUNT_MIN,
            VIVID_RENDERER_QUIESCE_FD_COUNT_MAX,
            "QUIESCE",
            NULL,
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_SHUTDOWN: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_SHUTDOWN,
            VIVID_RENDERER_DIRECTION_DAEMON_TO_WORKER,
            VIVID_RENDERER_REQUEST_ID_REQUIRED,
            VIVID_RENDERER_SHUTDOWN_FIXED_BYTES,
            VIVID_RENDERER_SHUTDOWN_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_SHUTDOWN_FD_COUNT_MIN,
            VIVID_RENDERER_SHUTDOWN_FD_COUNT_MAX,
            "SHUTDOWN",
            NULL,
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_HELLO: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_HELLO,
            VIVID_RENDERER_DIRECTION_WORKER_TO_DAEMON,
            VIVID_RENDERER_REQUEST_ID_ZERO,
            VIVID_RENDERER_HELLO_FIXED_BYTES,
            VIVID_RENDERER_HELLO_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_HELLO_FD_COUNT_MIN,
            VIVID_RENDERER_HELLO_FD_COUNT_MAX,
            "HELLO",
            NULL,
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_READY: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_READY,
            VIVID_RENDERER_DIRECTION_WORKER_TO_DAEMON,
            VIVID_RENDERER_REQUEST_ID_REQUIRED,
            VIVID_RENDERER_READY_FIXED_BYTES,
            VIVID_RENDERER_READY_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_READY_FD_COUNT_MIN,
            VIVID_RENDERER_READY_FD_COUNT_MAX,
            "READY",
            "INIT",
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_FORMAT_CAPS: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_FORMAT_CAPS,
            VIVID_RENDERER_DIRECTION_WORKER_TO_DAEMON,
            VIVID_RENDERER_REQUEST_ID_REQUIRED,
            VIVID_RENDERER_FORMAT_CAPS_FIXED_BYTES,
            VIVID_RENDERER_FORMAT_CAPS_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_FORMAT_CAPS_FD_COUNT_MIN,
            VIVID_RENDERER_FORMAT_CAPS_FD_COUNT_MAX,
            "FORMAT_CAPS",
            "INIT",
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_RELEASE_TIMELINE: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_RELEASE_TIMELINE,
            VIVID_RENDERER_DIRECTION_WORKER_TO_DAEMON,
            VIVID_RENDERER_REQUEST_ID_REQUIRED,
            VIVID_RENDERER_RELEASE_TIMELINE_FIXED_BYTES,
            VIVID_RENDERER_RELEASE_TIMELINE_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_RELEASE_TIMELINE_FD_COUNT_MIN,
            VIVID_RENDERER_RELEASE_TIMELINE_FD_COUNT_MAX,
            "RELEASE_TIMELINE",
            "INIT",
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_BIND_BUFFERS: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_BIND_BUFFERS,
            VIVID_RENDERER_DIRECTION_WORKER_TO_DAEMON,
            VIVID_RENDERER_REQUEST_ID_REQUIRED,
            VIVID_RENDERER_BIND_BUFFERS_FIXED_BYTES,
            VIVID_RENDERER_BIND_BUFFERS_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_BIND_BUFFERS_FD_COUNT_MIN,
            VIVID_RENDERER_BIND_BUFFERS_FD_COUNT_MAX,
            "BIND_BUFFERS",
            "NEGOTIATE_BUFFERS",
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_FRAME_READY: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_FRAME_READY,
            VIVID_RENDERER_DIRECTION_WORKER_TO_DAEMON,
            VIVID_RENDERER_REQUEST_ID_ZERO,
            VIVID_RENDERER_FRAME_READY_FIXED_BYTES,
            VIVID_RENDERER_FRAME_READY_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_FRAME_READY_FD_COUNT_MIN,
            VIVID_RENDERER_FRAME_READY_FD_COUNT_MAX,
            "FRAME_READY",
            NULL,
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_STATE_CHANGED: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_STATE_CHANGED,
            VIVID_RENDERER_DIRECTION_WORKER_TO_DAEMON,
            VIVID_RENDERER_REQUEST_ID_ANY,
            VIVID_RENDERER_STATE_CHANGED_FIXED_BYTES,
            VIVID_RENDERER_STATE_CHANGED_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_STATE_CHANGED_FD_COUNT_MIN,
            VIVID_RENDERER_STATE_CHANGED_FD_COUNT_MAX,
            "STATE_CHANGED",
            NULL,
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_BIND_FAILED: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_BIND_FAILED,
            VIVID_RENDERER_DIRECTION_WORKER_TO_DAEMON,
            VIVID_RENDERER_REQUEST_ID_REQUIRED,
            VIVID_RENDERER_BIND_FAILED_FIXED_BYTES,
            VIVID_RENDERER_BIND_FAILED_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_BIND_FAILED_FD_COUNT_MIN,
            VIVID_RENDERER_BIND_FAILED_FD_COUNT_MAX,
            "BIND_FAILED",
            "NEGOTIATE_BUFFERS",
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_ERROR: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_ERROR,
            VIVID_RENDERER_DIRECTION_WORKER_TO_DAEMON,
            VIVID_RENDERER_REQUEST_ID_ANY,
            VIVID_RENDERER_ERROR_FIXED_BYTES,
            VIVID_RENDERER_ERROR_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_ERROR_FD_COUNT_MIN,
            VIVID_RENDERER_ERROR_FD_COUNT_MAX,
            "ERROR",
            NULL,
        };
        return &descriptor;
    }
    case VIVID_RENDERER_MSG_QUIESCED: {
        static const VividRendererMessageDescriptor descriptor = {
            VIVID_RENDERER_MSG_QUIESCED,
            VIVID_RENDERER_DIRECTION_WORKER_TO_DAEMON,
            VIVID_RENDERER_REQUEST_ID_REQUIRED,
            VIVID_RENDERER_QUIESCED_FIXED_BYTES,
            VIVID_RENDERER_QUIESCED_MAX_PAYLOAD_BYTES,
            VIVID_RENDERER_QUIESCED_FD_COUNT_MIN,
            VIVID_RENDERER_QUIESCED_FD_COUNT_MAX,
            "QUIESCED",
            "QUIESCE",
        };
        return &descriptor;
    }
    default:
        return NULL;
    }
}

/*
 * Variable payload lengths are derived only from generated offsets and
 * limits. The transport calls this before any backend sees a packet, so
 * malformed lengths cannot make renderer-specific parsers walk past the
 * received SOCK_SEQPACKET record.
 */
static inline bool vivid_renderer_payload_length_valid(
    uint16_t opcode, const uint8_t* payload, size_t payload_len)
{
    if ((!payload && payload_len != 0u) || payload_len > VIVID_RENDERER_MAX_PAYLOAD_BYTES)
        return false;
    switch (opcode) {
    case VIVID_RENDERER_MSG_INIT: {
        if (payload_len < VIVID_RENDERER_INIT_FIXED_BYTES)
            return false;
        size_t expected = VIVID_RENDERER_INIT_FIXED_BYTES;
        size_t count_renderer_id = 1u;
        const size_t component_renderer_id_length_renderer_id = (size_t)vivid_renderer_wire_read_u32(payload + 44u);
        if (component_renderer_id_length_renderer_id != 0u &&
            count_renderer_id > 128u / component_renderer_id_length_renderer_id)
            return false;
        count_renderer_id *= component_renderer_id_length_renderer_id;
        if (count_renderer_id < 1u || count_renderer_id > 128u)
            return false;
        if (count_renderer_id > (SIZE_MAX - expected) / 1u)
            return false;
        expected += count_renderer_id * 1u;
        size_t count_project_path = 1u;
        const size_t component_project_path_length_project_path = (size_t)vivid_renderer_wire_read_u32(payload + 48u);
        if (component_project_path_length_project_path != 0u &&
            count_project_path > 4096u / component_project_path_length_project_path)
            return false;
        count_project_path *= component_project_path_length_project_path;
        if (count_project_path < 1u || count_project_path > 4096u)
            return false;
        if (count_project_path > (SIZE_MAX - expected) / 1u)
            return false;
        expected += count_project_path * 1u;
        size_t count_render_node = 1u;
        const size_t component_render_node_length_render_node = (size_t)vivid_renderer_wire_read_u32(payload + 52u);
        if (component_render_node_length_render_node != 0u &&
            count_render_node > 256u / component_render_node_length_render_node)
            return false;
        count_render_node *= component_render_node_length_render_node;
        if (count_render_node < 1u || count_render_node > 256u)
            return false;
        if (count_render_node > (SIZE_MAX - expected) / 1u)
            return false;
        expected += count_render_node * 1u;
        size_t count_settings_json = 1u;
        const size_t component_settings_json_length_settings_json = (size_t)vivid_renderer_wire_read_u32(payload + 56u);
        if (component_settings_json_length_settings_json != 0u &&
            count_settings_json > 65536u / component_settings_json_length_settings_json)
            return false;
        count_settings_json *= component_settings_json_length_settings_json;
        if (count_settings_json > 65536u)
            return false;
        if (count_settings_json > (SIZE_MAX - expected) / 1u)
            return false;
        expected += count_settings_json * 1u;
        size_t count_properties_json = 1u;
        const size_t component_properties_json_length_properties_json = (size_t)vivid_renderer_wire_read_u32(payload + 60u);
        if (component_properties_json_length_properties_json != 0u &&
            count_properties_json > 65536u / component_properties_json_length_properties_json)
            return false;
        count_properties_json *= component_properties_json_length_properties_json;
        if (count_properties_json > 65536u)
            return false;
        if (count_properties_json > (SIZE_MAX - expected) / 1u)
            return false;
        expected += count_properties_json * 1u;
        return expected == payload_len;
    }
    case VIVID_RENDERER_MSG_NEGOTIATE_BUFFERS:
        return payload_len == VIVID_RENDERER_NEGOTIATE_BUFFERS_FIXED_BYTES;
    case VIVID_RENDERER_MSG_SET_RUNTIME: {
        if (payload_len < VIVID_RENDERER_SET_RUNTIME_FIXED_BYTES)
            return false;
        size_t expected = VIVID_RENDERER_SET_RUNTIME_FIXED_BYTES;
        size_t count_settings_json = 1u;
        const size_t component_settings_json_length_settings_json = (size_t)vivid_renderer_wire_read_u32(payload + 0u);
        if (component_settings_json_length_settings_json != 0u &&
            count_settings_json > 65536u / component_settings_json_length_settings_json)
            return false;
        count_settings_json *= component_settings_json_length_settings_json;
        if (count_settings_json > 65536u)
            return false;
        if (count_settings_json > (SIZE_MAX - expected) / 1u)
            return false;
        expected += count_settings_json * 1u;
        return expected == payload_len;
    }
    case VIVID_RENDERER_MSG_SET_PLAYBACK:
        return payload_len == VIVID_RENDERER_SET_PLAYBACK_FIXED_BYTES;
    case VIVID_RENDERER_MSG_SET_MEDIA_STATE: {
        if (payload_len < VIVID_RENDERER_SET_MEDIA_STATE_FIXED_BYTES)
            return false;
        size_t expected = VIVID_RENDERER_SET_MEDIA_STATE_FIXED_BYTES;
        size_t count_media_state_json = 1u;
        const size_t component_media_state_json_length_media_state_json = (size_t)vivid_renderer_wire_read_u32(payload + 0u);
        if (component_media_state_json_length_media_state_json != 0u &&
            count_media_state_json > 65536u / component_media_state_json_length_media_state_json)
            return false;
        count_media_state_json *= component_media_state_json_length_media_state_json;
        if (count_media_state_json > 65536u)
            return false;
        if (count_media_state_json > (SIZE_MAX - expected) / 1u)
            return false;
        expected += count_media_state_json * 1u;
        return expected == payload_len;
    }
    case VIVID_RENDERER_MSG_SET_AUDIO_SAMPLES: {
        if (payload_len < VIVID_RENDERER_SET_AUDIO_SAMPLES_FIXED_BYTES)
            return false;
        size_t expected = VIVID_RENDERER_SET_AUDIO_SAMPLES_FIXED_BYTES;
        size_t count_samples = 1u;
        const size_t component_count_samples = (size_t)vivid_renderer_wire_read_u32(payload + 0u);
        if (component_count_samples != 0u &&
            count_samples > 128u / component_count_samples)
            return false;
        count_samples *= component_count_samples;
        if (count_samples < 1u || count_samples > 128u)
            return false;
        if (count_samples > (SIZE_MAX - expected) / 4u)
            return false;
        expected += count_samples * 4u;
        return expected == payload_len;
    }
    case VIVID_RENDERER_MSG_POINTER_MOTION:
        return payload_len == VIVID_RENDERER_POINTER_MOTION_FIXED_BYTES;
    case VIVID_RENDERER_MSG_POINTER_BUTTON:
        return payload_len == VIVID_RENDERER_POINTER_BUTTON_FIXED_BYTES;
    case VIVID_RENDERER_MSG_POINTER_AXIS:
        return payload_len == VIVID_RENDERER_POINTER_AXIS_FIXED_BYTES;
    case VIVID_RENDERER_MSG_QUIESCE:
        return payload_len == VIVID_RENDERER_QUIESCE_FIXED_BYTES;
    case VIVID_RENDERER_MSG_SHUTDOWN:
        return payload_len == VIVID_RENDERER_SHUTDOWN_FIXED_BYTES;
    case VIVID_RENDERER_MSG_HELLO: {
        if (payload_len < VIVID_RENDERER_HELLO_FIXED_BYTES)
            return false;
        size_t expected = VIVID_RENDERER_HELLO_FIXED_BYTES;
        size_t count_renderer_id = 1u;
        const size_t component_renderer_id_length_renderer_id = (size_t)vivid_renderer_wire_read_u32(payload + 12u);
        if (component_renderer_id_length_renderer_id != 0u &&
            count_renderer_id > 128u / component_renderer_id_length_renderer_id)
            return false;
        count_renderer_id *= component_renderer_id_length_renderer_id;
        if (count_renderer_id < 1u || count_renderer_id > 128u)
            return false;
        if (count_renderer_id > (SIZE_MAX - expected) / 1u)
            return false;
        expected += count_renderer_id * 1u;
        return expected == payload_len;
    }
    case VIVID_RENDERER_MSG_READY: {
        if (payload_len < VIVID_RENDERER_READY_FIXED_BYTES)
            return false;
        size_t expected = VIVID_RENDERER_READY_FIXED_BYTES;
        size_t count_render_node = 1u;
        const size_t component_render_node_length_render_node = (size_t)vivid_renderer_wire_read_u32(payload + 40u);
        if (component_render_node_length_render_node != 0u &&
            count_render_node > 256u / component_render_node_length_render_node)
            return false;
        count_render_node *= component_render_node_length_render_node;
        if (count_render_node < 1u || count_render_node > 256u)
            return false;
        if (count_render_node > (SIZE_MAX - expected) / 1u)
            return false;
        expected += count_render_node * 1u;
        return expected == payload_len;
    }
    case VIVID_RENDERER_MSG_FORMAT_CAPS: {
        if (payload_len < VIVID_RENDERER_FORMAT_CAPS_FIXED_BYTES)
            return false;
        size_t expected = VIVID_RENDERER_FORMAT_CAPS_FIXED_BYTES;
        size_t count_capabilities = 1u;
        const size_t component_capability_count_capabilities = (size_t)vivid_renderer_wire_read_u32(payload + 32u);
        if (component_capability_count_capabilities != 0u &&
            count_capabilities > 128u / component_capability_count_capabilities)
            return false;
        count_capabilities *= component_capability_count_capabilities;
        if (count_capabilities < 1u || count_capabilities > 128u)
            return false;
        if (count_capabilities > (SIZE_MAX - expected) / 16u)
            return false;
        expected += count_capabilities * 16u;
        return expected == payload_len;
    }
    case VIVID_RENDERER_MSG_RELEASE_TIMELINE:
        return payload_len == VIVID_RENDERER_RELEASE_TIMELINE_FIXED_BYTES;
    case VIVID_RENDERER_MSG_BIND_BUFFERS: {
        if (payload_len < VIVID_RENDERER_BIND_BUFFERS_FIXED_BYTES)
            return false;
        size_t expected = VIVID_RENDERER_BIND_BUFFERS_FIXED_BYTES;
        size_t count_planes = 1u;
        const size_t component_buffer_count_planes = (size_t)vivid_renderer_wire_read_u32(payload + 20u);
        if (component_buffer_count_planes != 0u &&
            count_planes > 32u / component_buffer_count_planes)
            return false;
        count_planes *= component_buffer_count_planes;
        const size_t component_plane_count_planes = (size_t)vivid_renderer_wire_read_u32(payload + 24u);
        if (component_plane_count_planes != 0u &&
            count_planes > 32u / component_plane_count_planes)
            return false;
        count_planes *= component_plane_count_planes;
        if (count_planes < 1u || count_planes > 32u)
            return false;
        if (count_planes > (SIZE_MAX - expected) / 16u)
            return false;
        expected += count_planes * 16u;
        return expected == payload_len;
    }
    case VIVID_RENDERER_MSG_FRAME_READY:
        return payload_len == VIVID_RENDERER_FRAME_READY_FIXED_BYTES;
    case VIVID_RENDERER_MSG_STATE_CHANGED: {
        if (payload_len < VIVID_RENDERER_STATE_CHANGED_FIXED_BYTES)
            return false;
        size_t expected = VIVID_RENDERER_STATE_CHANGED_FIXED_BYTES;
        size_t count_state_json = 1u;
        const size_t component_state_json_length_state_json = (size_t)vivid_renderer_wire_read_u32(payload + 16u);
        if (component_state_json_length_state_json != 0u &&
            count_state_json > 65536u / component_state_json_length_state_json)
            return false;
        count_state_json *= component_state_json_length_state_json;
        if (count_state_json > 65536u)
            return false;
        if (count_state_json > (SIZE_MAX - expected) / 1u)
            return false;
        expected += count_state_json * 1u;
        return expected == payload_len;
    }
    case VIVID_RENDERER_MSG_BIND_FAILED: {
        if (payload_len < VIVID_RENDERER_BIND_FAILED_FIXED_BYTES)
            return false;
        size_t expected = VIVID_RENDERER_BIND_FAILED_FIXED_BYTES;
        size_t count_diagnostic = 1u;
        const size_t component_diagnostic_length_diagnostic = (size_t)vivid_renderer_wire_read_u32(payload + 8u);
        if (component_diagnostic_length_diagnostic != 0u &&
            count_diagnostic > 4096u / component_diagnostic_length_diagnostic)
            return false;
        count_diagnostic *= component_diagnostic_length_diagnostic;
        if (count_diagnostic > 4096u)
            return false;
        if (count_diagnostic > (SIZE_MAX - expected) / 1u)
            return false;
        expected += count_diagnostic * 1u;
        return expected == payload_len;
    }
    case VIVID_RENDERER_MSG_ERROR: {
        if (payload_len < VIVID_RENDERER_ERROR_FIXED_BYTES)
            return false;
        size_t expected = VIVID_RENDERER_ERROR_FIXED_BYTES;
        size_t count_diagnostic = 1u;
        const size_t component_diagnostic_length_diagnostic = (size_t)vivid_renderer_wire_read_u32(payload + 8u);
        if (component_diagnostic_length_diagnostic != 0u &&
            count_diagnostic > 4096u / component_diagnostic_length_diagnostic)
            return false;
        count_diagnostic *= component_diagnostic_length_diagnostic;
        if (count_diagnostic > 4096u)
            return false;
        if (count_diagnostic > (SIZE_MAX - expected) / 1u)
            return false;
        expected += count_diagnostic * 1u;
        return expected == payload_len;
    }
    case VIVID_RENDERER_MSG_QUIESCED:
        return payload_len == VIVID_RENDERER_QUIESCED_FIXED_BYTES;
    default:
        return false;
    }
}

/*
 * SCM_RIGHTS cardinality is part of the wire contract. BIND_BUFFERS is
 * the only dynamic case: one moved descriptor is required for every
 * serialized buffer/plane tuple. This check runs while all received FDs
 * still have a single temporary owner, allowing the caller to close the
 * whole set atomically on any mismatch.
 */
static inline bool vivid_renderer_fd_count_valid(
    uint16_t opcode, const uint8_t* payload, size_t payload_len, size_t n_fds)
{
    if (!vivid_renderer_payload_length_valid(opcode, payload, payload_len) ||
        n_fds > VIVID_RENDERER_MAX_FDS_PER_MESSAGE)
        return false;
    switch (opcode) {
    case VIVID_RENDERER_MSG_INIT:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_NEGOTIATE_BUFFERS:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_SET_RUNTIME:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_SET_PLAYBACK:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_SET_MEDIA_STATE:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_SET_AUDIO_SAMPLES:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_POINTER_MOTION:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_POINTER_BUTTON:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_POINTER_AXIS:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_QUIESCE:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_SHUTDOWN:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_HELLO:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_READY:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_FORMAT_CAPS:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_RELEASE_TIMELINE:
        return n_fds == 1u;
    case VIVID_RENDERER_MSG_BIND_BUFFERS: {
        size_t expected = 1u;
        const size_t buffer_count = (size_t)vivid_renderer_wire_read_u32(payload + 20u);
        if (buffer_count != 0u && expected > 32u / buffer_count)
            return false;
        expected *= buffer_count;
        const size_t plane_count = (size_t)vivid_renderer_wire_read_u32(payload + 24u);
        if (plane_count != 0u && expected > 32u / plane_count)
            return false;
        expected *= plane_count;
        return expected <= 32u && n_fds == expected;
    }
    case VIVID_RENDERER_MSG_FRAME_READY:
        return n_fds == 1u;
    case VIVID_RENDERER_MSG_STATE_CHANGED:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_BIND_FAILED:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_ERROR:
        return n_fds == 0u;
    case VIVID_RENDERER_MSG_QUIESCED:
        return n_fds == 0u;
    default:
        return false;
    }
}

static inline bool vivid_renderer_header_contract_valid(
    const VividRendererMessageHeader* header,
    uint64_t expected_instance_id,
    VividRendererMessageDirection expected_direction)
{
    if (!header || header->magic != VIVID_RENDERER_PROTOCOL_MAGIC ||
        header->version != VIVID_RENDERER_PROTOCOL_VERSION ||
        header->renderer_instance_id == 0u ||
        header->renderer_instance_id != expected_instance_id ||
        header->payload_length > VIVID_RENDERER_MAX_PAYLOAD_BYTES)
        return false;
    const VividRendererMessageDescriptor* descriptor =
        vivid_renderer_message_descriptor(header->opcode);
    if (!descriptor || descriptor->direction != expected_direction)
        return false;
    if (descriptor->request_id_policy == VIVID_RENDERER_REQUEST_ID_ZERO)
        return header->request_id == 0u;
    if (descriptor->request_id_policy == VIVID_RENDERER_REQUEST_ID_REQUIRED)
        return header->request_id != 0u;
    return true;
}

#endif
