#!/bin/sh

# Central path configuration for consumer build and packaging scripts.
# The scripts below intentionally read directory settings from this file so
# the GNOME extension can be built in a relocated workspace without patching
# every command that touches .build, DESTDIR, or the dist output.

: "${ROOT_DIR:?ROOT_DIR must be set before sourcing tools/consumer_gnome/build_env.sh}"

VIVID_CONSUMER_ROOT_DIR="${VIVID_CONSUMER_ROOT_DIR:-${ROOT_DIR}}"
VIVID_CONSUMER_BUILD_ROOT="${VIVID_CONSUMER_BUILD_ROOT:-${VIVID_CONSUMER_ROOT_DIR}/.build}"
VIVID_CONSUMER_BUILD_DIR="${VIVID_CONSUMER_BUILD_DIR:-${VIVID_CONSUMER_BUILD_ROOT}}"
VIVID_CONSUMER_PACKAGE_BUILD_DIR="${VIVID_CONSUMER_PACKAGE_BUILD_DIR:-${VIVID_CONSUMER_BUILD_ROOT}/consumer}"
VIVID_CONSUMER_DESTDIR_ROOT="${VIVID_CONSUMER_DESTDIR_ROOT:-${VIVID_CONSUMER_BUILD_ROOT}/consumer-root}"
VIVID_CONSUMER_DIST_DIR="${VIVID_CONSUMER_DIST_DIR:-${VIVID_CONSUMER_BUILD_ROOT}/dist}"
VIVID_CONSUMER_PACKAGE_BASENAME="${VIVID_CONSUMER_PACKAGE_BASENAME:-vivid-consumer-gnome}"
VIVID_CONSUMER_PACKAGE_ABI="${VIVID_CONSUMER_PACKAGE_ABI:-$(uname -m)}"
VIVID_CONSUMER_PACKAGE_VERSION="${VIVID_CONSUMER_PACKAGE_VERSION:-1.0.0}"

case "${VIVID_CONSUMER_PACKAGE_VERSION}" in
    ""|*[!0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz._+~-]*)
        echo "Invalid VIVID_CONSUMER_PACKAGE_VERSION=${VIVID_CONSUMER_PACKAGE_VERSION}; expected only 0-9, A-Z, a-z, '.', '_', '+', '~', or '-'." >&2
        exit 1
        ;;
esac

VIVID_CONSUMER_PACKAGE_VERSION_MAJOR="${VIVID_CONSUMER_PACKAGE_VERSION%%.*}"
case "${VIVID_CONSUMER_PACKAGE_VERSION_MAJOR}" in
    ""|*[!0123456789]*)
        echo "Invalid VIVID_CONSUMER_PACKAGE_VERSION=${VIVID_CONSUMER_PACKAGE_VERSION}; expected a numeric major version before the first '.'." >&2
        exit 1
        ;;
esac

VIVID_CONSUMER_INSTALL_PREFIX="${VIVID_CONSUMER_INSTALL_PREFIX:-${HOME:-/tmp}/.local}"
VIVID_CONSUMER_PACKAGE_PREFIX="${VIVID_CONSUMER_PACKAGE_PREFIX:-/usr}"
VIVID_CONSUMER_PACKAGE_DATADIR="${VIVID_CONSUMER_PACKAGE_DATADIR:-share}"

VIVID_CONSUMER_EXTENSION_UUID="${VIVID_CONSUMER_EXTENSION_UUID:-vivid-consumer-gnome@rikka.local}"
VIVID_CONSUMER_SCHEMA_ID="${VIVID_CONSUMER_SCHEMA_ID:-dev.rikka.vivid.consumer.gnome}"
VIVID_CONSUMER_EXTENSION_NAME="${VIVID_CONSUMER_EXTENSION_NAME:-Vivid Consumer}"
VIVID_CONSUMER_EXTENSION_DESCRIPTION="${VIVID_CONSUMER_EXTENSION_DESCRIPTION:-GNOME Shell display consumer for display-v1 producers}"
VIVID_CONSUMER_EXTENSION_AUTHOR="${VIVID_CONSUMER_EXTENSION_AUTHOR:-rikka}"
VIVID_CONSUMER_EXTENSION_URL="${VIVID_CONSUMER_EXTENSION_URL:-https://github.com/waywallen/waywallen-display}"
VIVID_CONSUMER_EXTENSION_LOG_PREFIX="${VIVID_CONSUMER_EXTENSION_LOG_PREFIX:-Vivid Consumer:}"

VIVID_CONSUMER_GNOME_SHELL_JOURNAL="${VIVID_CONSUMER_GNOME_SHELL_JOURNAL:-/usr/bin/gnome-shell}"
