#!/bin/sh

# Central path configuration for producer build and run scripts.
# Keep directory defaults in one place so local, direct-run, and Flatpak builds
# can be relocated with environment variables instead of editing script bodies.

: "${ROOT_DIR:?ROOT_DIR must be set before sourcing tools/producer/build_env.sh}"

VIVID_PRODUCER_ROOT_DIR="${VIVID_PRODUCER_ROOT_DIR:-${ROOT_DIR}}"
VIVID_BUILD_ROOT="${VIVID_BUILD_ROOT:-${VIVID_PRODUCER_ROOT_DIR}/.build}"

. "${VIVID_PRODUCER_ROOT_DIR}/../tools/build_arch.sh"
. "${VIVID_PRODUCER_ROOT_DIR}/packaging/flatpak/cef-sources.sh"

VIVID_BUILD_ARCH="$(vivid_normalize_build_arch "${VIVID_BUILD_ARCH:-$(uname -m)}")"

case "${VIVID_BUILD_ARCH}" in
    x86_64)
        VIVID_CEF_PLATFORM=linux64
        VIVID_CEF_ARCHIVE_SHA1="${VIVID_CEF_LINUX64_SHA1}"
        ;;
    aarch64)
        VIVID_CEF_PLATFORM=linuxarm64
        VIVID_CEF_ARCHIVE_SHA1="${VIVID_CEF_LINUXARM64_SHA1}"
        ;;
esac

VIVID_CEF_ARCHIVE_BASENAME="cef_binary_${VIVID_CEF_VERSION}_${VIVID_CEF_PLATFORM}_minimal.tar.bz2"
VIVID_CEF_ARCHIVE_URL="${VIVID_CEF_DOWNLOAD_BASE_URL}/${VIVID_CEF_ARCHIVE_BASENAME}"

VIVID_PRODUCER_SRC_DIR="${VIVID_PRODUCER_SRC_DIR:-${VIVID_PRODUCER_ROOT_DIR}/src}"
VIVID_PRODUCER_DAEMON_DIR="${VIVID_PRODUCER_DAEMON_DIR:-${VIVID_PRODUCER_SRC_DIR}/daemon}"
VIVID_PRODUCER_PROTOCOL_DIR="${VIVID_PRODUCER_PROTOCOL_DIR:-${VIVID_PRODUCER_SRC_DIR}/protocol}"
VIVID_PRODUCER_GRAPHICS_DIR="${VIVID_PRODUCER_GRAPHICS_DIR:-${VIVID_PRODUCER_SRC_DIR}/graphics}"
VIVID_PRODUCER_RENDERER_API_DIR="${VIVID_PRODUCER_RENDERER_API_DIR:-${VIVID_PRODUCER_SRC_DIR}/renderer_api}"
VIVID_PRODUCER_RENDERERS_DIR="${VIVID_PRODUCER_RENDERERS_DIR:-${VIVID_PRODUCER_SRC_DIR}/renderers}"
VIVID_SCENE_SOURCE_DIR="${VIVID_SCENE_SOURCE_DIR:-${VIVID_PRODUCER_RENDERERS_DIR}/scene}"
VIVID_VIDEO_SOURCE_DIR="${VIVID_VIDEO_SOURCE_DIR:-${VIVID_PRODUCER_RENDERERS_DIR}/video}"
VIVID_WEB_SOURCE_DIR="${VIVID_WEB_SOURCE_DIR:-${VIVID_PRODUCER_RENDERERS_DIR}/web}"
VIVID_WEBUI_SOURCE_DIR="${VIVID_WEBUI_SOURCE_DIR:-${VIVID_PRODUCER_SRC_DIR}/webui}"
VIVID_GBM_USAGE_SHIM_SOURCE="${VIVID_GBM_USAGE_SHIM_SOURCE:-${VIVID_WEB_SOURCE_DIR}/vivid_web_gbm_usage_shim.c}"

VIVID_SCENE_TARGET="${VIVID_SCENE_TARGET:-vivid-scene-renderer}"
VIVID_VIDEO_TARGET="${VIVID_VIDEO_TARGET:-vivid-video-renderer}"
VIVID_WEB_TARGET="${VIVID_WEB_TARGET:-vivid-web-renderer}"
VIVID_WEB_HELPER_TARGET="${VIVID_WEB_HELPER_TARGET:-vivid-web-helper}"
VIVID_SCENE_EXECUTABLE_NAME="${VIVID_SCENE_EXECUTABLE_NAME:-vivid-scene-renderer}"
VIVID_VIDEO_EXECUTABLE_NAME="${VIVID_VIDEO_EXECUTABLE_NAME:-vivid-video-renderer}"
VIVID_WEB_EXECUTABLE_NAME="${VIVID_WEB_EXECUTABLE_NAME:-vivid-web-renderer}"
VIVID_SCENE_MANIFEST_NAME="${VIVID_SCENE_MANIFEST_NAME:-vivid-scene.renderer.json}"
VIVID_VIDEO_MANIFEST_NAME="${VIVID_VIDEO_MANIFEST_NAME:-vivid-video.renderer.json}"
VIVID_WEB_MANIFEST_NAME="${VIVID_WEB_MANIFEST_NAME:-vivid-web.renderer.json}"
VIVID_DXCOMPILER_LIBRARY_NAME="${VIVID_DXCOMPILER_LIBRARY_NAME:-libdxcompiler.so}"
VIVID_CMAKE_BUILD_TYPE="${VIVID_CMAKE_BUILD_TYPE:-RelWithDebInfo}"

VIVID_RUNTIME_DIR="${VIVID_RUNTIME_DIR:-${XDG_RUNTIME_DIR:-/tmp}}"
VIVID_DEFAULT_DISPLAY_SOCKET="${VIVID_DEFAULT_DISPLAY_SOCKET:-${VIVID_RUNTIME_DIR}/vivid/display-v1.sock}"
VIVID_PRODUCER_APP_ID="${VIVID_PRODUCER_APP_ID:-io.github.ayasa520.Vivid}"
VIVID_PRODUCER_COMMAND_NAME="${VIVID_PRODUCER_COMMAND_NAME:-vivid-producer}"
VIVID_PRODUCER_LAUNCHER_NAME="${VIVID_PRODUCER_LAUNCHER_NAME:-vivid}"
VIVID_FLATPAK_APP_VERSION="${VIVID_FLATPAK_APP_VERSION:-1.0.0}"
VIVID_FLATPAK_RELEASE_DATE="${VIVID_FLATPAK_RELEASE_DATE:-2026-06-18}"
VIVID_DIRECT_RUN_CONFIG_DIR="${VIVID_DIRECT_RUN_CONFIG_DIR:-${HOME:-/tmp}/.var/app/${VIVID_PRODUCER_APP_ID}/config/vivid-producer}"
VIVID_DIRECT_RUN_CONFIG_FILE="${VIVID_DIRECT_RUN_CONFIG_FILE:-${VIVID_DIRECT_RUN_CONFIG_DIR}/config-v1.json}"

VIVID_DIRECT_RUN_BUILD_DIR="${VIVID_DIRECT_RUN_BUILD_DIR:-${VIVID_BUILD_ROOT}/direct-run}"
VIVID_DIRECT_RUN_DAEMON_BUILD_DIR="${VIVID_DIRECT_RUN_DAEMON_BUILD_DIR:-${VIVID_DIRECT_RUN_BUILD_DIR}/daemon-build}"
VIVID_DIRECT_RUN_SCENE_BUILD_DIR="${VIVID_DIRECT_RUN_SCENE_BUILD_DIR:-${VIVID_DIRECT_RUN_BUILD_DIR}/scene-build}"
VIVID_DIRECT_RUN_VIDEO_BUILD_DIR="${VIVID_DIRECT_RUN_VIDEO_BUILD_DIR:-${VIVID_DIRECT_RUN_BUILD_DIR}/video-build}"
VIVID_DIRECT_RUN_WEB_BUILD_DIR="${VIVID_DIRECT_RUN_WEB_BUILD_DIR:-${VIVID_DIRECT_RUN_BUILD_DIR}/web-build}"
VIVID_DIRECT_RUN_PRODUCER_BIN="${VIVID_DIRECT_RUN_PRODUCER_BIN:-${VIVID_DIRECT_RUN_BUILD_DIR}/vivid-producer-dev}"
VIVID_DIRECT_RUN_GBM_SHIM_BUILD_DIR="${VIVID_DIRECT_RUN_GBM_SHIM_BUILD_DIR:-${VIVID_DIRECT_RUN_BUILD_DIR}/gbm-usage-shim}"
VIVID_DIRECT_RUN_GBM_USAGE_SHIM="${VIVID_DIRECT_RUN_GBM_USAGE_SHIM:-${VIVID_DIRECT_RUN_GBM_SHIM_BUILD_DIR}/libvivid-gbm-usage-shim.so}"
VIVID_DIRECT_RUN_RENDERER_ROOT="${VIVID_DIRECT_RUN_RENDERER_ROOT:-${VIVID_DIRECT_RUN_BUILD_DIR}/renderer-registry-v1}"
VIVID_DIRECT_RUN_SCENE_DIR="${VIVID_DIRECT_RUN_SCENE_DIR:-${VIVID_DIRECT_RUN_RENDERER_ROOT}/scene}"
VIVID_DIRECT_RUN_VIDEO_DIR="${VIVID_DIRECT_RUN_VIDEO_DIR:-${VIVID_DIRECT_RUN_RENDERER_ROOT}/video}"
VIVID_DIRECT_RUN_WEB_DIR="${VIVID_DIRECT_RUN_WEB_DIR:-${VIVID_DIRECT_RUN_RENDERER_ROOT}/web}"
VIVID_DIRECT_RUN_SCENE_EXECUTABLE="${VIVID_DIRECT_RUN_SCENE_EXECUTABLE:-${VIVID_DIRECT_RUN_SCENE_DIR}/${VIVID_SCENE_EXECUTABLE_NAME}}"
VIVID_DIRECT_RUN_VIDEO_EXECUTABLE="${VIVID_DIRECT_RUN_VIDEO_EXECUTABLE:-${VIVID_DIRECT_RUN_VIDEO_DIR}/${VIVID_VIDEO_EXECUTABLE_NAME}}"
VIVID_DIRECT_RUN_WEB_EXECUTABLE="${VIVID_DIRECT_RUN_WEB_EXECUTABLE:-${VIVID_DIRECT_RUN_WEB_DIR}/${VIVID_WEB_EXECUTABLE_NAME}}"
VIVID_DIRECT_RUN_SCENE_MANIFEST="${VIVID_DIRECT_RUN_SCENE_MANIFEST:-${VIVID_DIRECT_RUN_RENDERER_ROOT}/${VIVID_SCENE_MANIFEST_NAME}}"
VIVID_DIRECT_RUN_VIDEO_MANIFEST="${VIVID_DIRECT_RUN_VIDEO_MANIFEST:-${VIVID_DIRECT_RUN_RENDERER_ROOT}/${VIVID_VIDEO_MANIFEST_NAME}}"
VIVID_DIRECT_RUN_WEB_MANIFEST="${VIVID_DIRECT_RUN_WEB_MANIFEST:-${VIVID_DIRECT_RUN_RENDERER_ROOT}/${VIVID_WEB_MANIFEST_NAME}}"
VIVID_DIRECT_RUN_SCENE_BUILD_EXECUTABLE="${VIVID_DIRECT_RUN_SCENE_BUILD_EXECUTABLE:-${VIVID_DIRECT_RUN_SCENE_BUILD_DIR}/out/${VIVID_SCENE_EXECUTABLE_NAME}}"
VIVID_DIRECT_RUN_VIDEO_BUILD_EXECUTABLE="${VIVID_DIRECT_RUN_VIDEO_BUILD_EXECUTABLE:-${VIVID_DIRECT_RUN_VIDEO_BUILD_DIR}/out/${VIVID_VIDEO_EXECUTABLE_NAME}}"
VIVID_DIRECT_RUN_DXCOMPILER_LIBRARY="${VIVID_DIRECT_RUN_DXCOMPILER_LIBRARY:-${VIVID_DIRECT_RUN_SCENE_BUILD_DIR}/wallpaper-scene-renderer/dxc-stage/lib/${VIVID_DXCOMPILER_LIBRARY_NAME}}"
# The web backend's out/ directory collocates the worker with the complete CEF
# runtime and the helper executable.
VIVID_DIRECT_RUN_WEB_OUT_DIR="${VIVID_DIRECT_RUN_WEB_OUT_DIR:-${VIVID_DIRECT_RUN_WEB_BUILD_DIR}/worker-out}"

# CEF binary distribution: the archive lives under packaging/flatpak/sources.
# Its upstream filename includes both the exact CEF revision and target
# platform, which prevents an archive downloaded for one architecture from
# being reused by another architecture's build.
VIVID_CEF_ARCHIVE="${VIVID_CEF_ARCHIVE:-${VIVID_PRODUCER_ROOT_DIR}/packaging/flatpak/sources/${VIVID_CEF_ARCHIVE_BASENAME}}"
VIVID_DIRECT_RUN_CEF_DIR="${VIVID_DIRECT_RUN_CEF_DIR:-${VIVID_DIRECT_RUN_BUILD_DIR}/cef}"

VIVID_FLATPAK_MANIFEST="${VIVID_FLATPAK_MANIFEST:-${VIVID_PRODUCER_ROOT_DIR}/packaging/flatpak/io.github.ayasa520.Vivid.yml}"
VIVID_FLATPAK_SOURCES_DIR="${VIVID_FLATPAK_SOURCES_DIR:-${VIVID_PRODUCER_ROOT_DIR}/packaging/flatpak/sources}"
VIVID_FLATPAK_GENERATED_MANIFEST="${VIVID_FLATPAK_GENERATED_MANIFEST:-${VIVID_BUILD_ROOT}/flatpak-manifest/${VIVID_PRODUCER_APP_ID}.yml}"
VIVID_FLATPAK_SOURCE_LOCK="${VIVID_FLATPAK_SOURCE_LOCK:-${VIVID_BUILD_ROOT}/flatpak-manifest/${VIVID_PRODUCER_APP_ID}.source.env}"
VIVID_FLATPAK_GIT_URL="${VIVID_FLATPAK_GIT_URL:-https://github.com/ayasa520/Vivid.git}"
VIVID_FLATPAK_GIT_BRANCH="${VIVID_FLATPAK_GIT_BRANCH:-main}"
VIVID_FLATPAK_DOWNLOAD_DIR="${VIVID_FLATPAK_DOWNLOAD_DIR:-${VIVID_BUILD_ROOT}/flatpak-download}"
VIVID_FLATPAK_BUILD_DIR="${VIVID_FLATPAK_BUILD_DIR:-${VIVID_BUILD_ROOT}/flatpak/vivid-producer}"
VIVID_FLATPAK_REPO_DIR="${VIVID_FLATPAK_REPO_DIR:-${VIVID_BUILD_ROOT}/flatpak-repo/vivid-producer}"
VIVID_FLATPAK_BUNDLE_BRANCH="${VIVID_FLATPAK_BUNDLE_BRANCH:-master}"
VIVID_FLATPAK_BUNDLE="${VIVID_FLATPAK_BUNDLE:-${VIVID_BUILD_ROOT}/${VIVID_PRODUCER_APP_ID}-${VIVID_FLATPAK_APP_VERSION}-${VIVID_BUILD_ARCH}.flatpak}"
VIVID_FLATPAK_STATE_DIR="${VIVID_FLATPAK_STATE_DIR:-${VIVID_BUILD_ROOT}/flatpak-builder-state}"
VIVID_FLATPAK_NATIVE_CACHE_DIR="${VIVID_FLATPAK_NATIVE_CACHE_DIR:-${VIVID_BUILD_ROOT}/flatpak-native-cache}"
VIVID_FLATPAK_NATIVE_BUILD_ROOT="${VIVID_FLATPAK_NATIVE_BUILD_ROOT:-${VIVID_FLATPAK_NATIVE_CACHE_DIR}/native-build}"
VIVID_FLATPAK_RUN_DIR="${VIVID_FLATPAK_RUN_DIR:-${VIVID_BUILD_ROOT}/flatpak-run/vivid-producer}"
VIVID_FLATPAK_RENDERER_BUILD_ROOT="${VIVID_FLATPAK_RENDERER_BUILD_ROOT:-${VIVID_BUILD_ROOT}/flatpak-renderer-build}"
VIVID_FLATPAK_DAEMON_BUILD_DIR="${VIVID_FLATPAK_DAEMON_BUILD_DIR:-${VIVID_FLATPAK_RENDERER_BUILD_ROOT}/daemon}"
VIVID_FLATPAK_SCENE_BUILD_DIR="${VIVID_FLATPAK_SCENE_BUILD_DIR:-${VIVID_FLATPAK_RENDERER_BUILD_ROOT}/scene}"
VIVID_FLATPAK_VIDEO_BUILD_DIR="${VIVID_FLATPAK_VIDEO_BUILD_DIR:-${VIVID_FLATPAK_RENDERER_BUILD_ROOT}/video}"
VIVID_FLATPAK_WEB_BUILD_DIR="${VIVID_FLATPAK_WEB_BUILD_DIR:-${VIVID_FLATPAK_RENDERER_BUILD_ROOT}/web}"
VIVID_FLATPAK_CEF_ROOT="${VIVID_FLATPAK_CEF_ROOT:-${VIVID_PRODUCER_ROOT_DIR}/packaging/flatpak/cef}"
VIVID_FLATPAK_GBM_SHIM_BUILD_DIR="${VIVID_FLATPAK_GBM_SHIM_BUILD_DIR:-${VIVID_FLATPAK_RENDERER_BUILD_ROOT}/gbm-usage-shim}"
VIVID_FLATPAK_GBM_USAGE_SHIM="${VIVID_FLATPAK_GBM_USAGE_SHIM:-${VIVID_FLATPAK_GBM_SHIM_BUILD_DIR}/libvivid-gbm-usage-shim.so}"
VIVID_FLATPAK_SCENE_EXECUTABLE="${VIVID_FLATPAK_SCENE_EXECUTABLE:-${VIVID_FLATPAK_SCENE_BUILD_DIR}/out/${VIVID_SCENE_EXECUTABLE_NAME}}"
VIVID_FLATPAK_VIDEO_EXECUTABLE="${VIVID_FLATPAK_VIDEO_EXECUTABLE:-${VIVID_FLATPAK_VIDEO_BUILD_DIR}/out/${VIVID_VIDEO_EXECUTABLE_NAME}}"
VIVID_FLATPAK_WEB_OUT_DIR="${VIVID_FLATPAK_WEB_OUT_DIR:-${VIVID_FLATPAK_WEB_BUILD_DIR}/worker-out}"
VIVID_FLATPAK_DXCOMPILER_LIBRARY="${VIVID_FLATPAK_DXCOMPILER_LIBRARY:-${VIVID_FLATPAK_SCENE_BUILD_DIR}/wallpaper-scene-renderer/dxc-stage/lib/${VIVID_DXCOMPILER_LIBRARY_NAME}}"

VIVID_FLATPAK_RUN_CONFIG_DIR="${VIVID_FLATPAK_RUN_CONFIG_DIR:-${VIVID_FLATPAK_RUN_DIR}/config}"
VIVID_FLATPAK_RUN_CACHE_DIR="${VIVID_FLATPAK_RUN_CACHE_DIR:-${VIVID_FLATPAK_RUN_DIR}/cache}"
VIVID_FLATPAK_RUN_DATA_DIR="${VIVID_FLATPAK_RUN_DATA_DIR:-${VIVID_FLATPAK_RUN_DIR}/data}"
VIVID_FLATPAK_RUN_STATE_DIR="${VIVID_FLATPAK_RUN_STATE_DIR:-${VIVID_FLATPAK_RUN_DIR}/state}"
VIVID_FLATPAK_CONFIG_MOUNT="${VIVID_FLATPAK_CONFIG_MOUNT:-/run/vivid-producer-config}"
VIVID_FLATPAK_CACHE_MOUNT="${VIVID_FLATPAK_CACHE_MOUNT:-/run/vivid-producer-cache}"
VIVID_FLATPAK_DATA_MOUNT="${VIVID_FLATPAK_DATA_MOUNT:-/run/vivid-producer-data}"
VIVID_FLATPAK_STATE_MOUNT="${VIVID_FLATPAK_STATE_MOUNT:-/run/vivid-producer-state}"

VIVID_INSTALL_PREFIX="${VIVID_INSTALL_PREFIX:-/app}"
VIVID_INSTALL_BIN_DIR="${VIVID_INSTALL_BIN_DIR:-${VIVID_INSTALL_PREFIX}/bin}"
VIVID_INSTALL_LIB_DIR="${VIVID_INSTALL_LIB_DIR:-${VIVID_INSTALL_PREFIX}/lib}"
VIVID_INSTALL_LIB64_DIR="${VIVID_INSTALL_LIB64_DIR:-${VIVID_INSTALL_PREFIX}/lib64}"
VIVID_INSTALL_RENDERER_ROOT="${VIVID_INSTALL_RENDERER_ROOT:-${VIVID_INSTALL_LIB_DIR}/vivid-renderers}"
VIVID_INSTALL_SCENE_RENDERER_DIR="${VIVID_INSTALL_SCENE_RENDERER_DIR:-${VIVID_INSTALL_RENDERER_ROOT}/scene}"
VIVID_INSTALL_VIDEO_RENDERER_DIR="${VIVID_INSTALL_VIDEO_RENDERER_DIR:-${VIVID_INSTALL_RENDERER_ROOT}/video}"
VIVID_INSTALL_WEB_RENDERER_DIR="${VIVID_INSTALL_WEB_RENDERER_DIR:-${VIVID_INSTALL_RENDERER_ROOT}/web}"
VIVID_INSTALL_GBM_USAGE_SHIM="${VIVID_INSTALL_GBM_USAGE_SHIM:-${VIVID_INSTALL_WEB_RENDERER_DIR}/libvivid-gbm-usage-shim.so}"
VIVID_INSTALL_SHARE_DIR="${VIVID_INSTALL_SHARE_DIR:-${VIVID_INSTALL_PREFIX}/share}"
VIVID_INSTALL_WEBUI_DIR="${VIVID_INSTALL_WEBUI_DIR:-${VIVID_INSTALL_SHARE_DIR}/vivid-producer/webui}"
VIVID_INSTALL_APPLICATIONS_DIR="${VIVID_INSTALL_APPLICATIONS_DIR:-${VIVID_INSTALL_SHARE_DIR}/applications}"
VIVID_INSTALL_METAINFO_DIR="${VIVID_INSTALL_METAINFO_DIR:-${VIVID_INSTALL_SHARE_DIR}/metainfo}"
VIVID_INSTALL_ICON_DIR="${VIVID_INSTALL_ICON_DIR:-${VIVID_INSTALL_SHARE_DIR}/icons/hicolor/scalable/apps}"

VIVID_FLATPAK_GI_TYPELIB_PATH="${VIVID_FLATPAK_GI_TYPELIB_PATH:-${VIVID_INSTALL_LIB_DIR}/girepository-1.0}"
VIVID_FLATPAK_LD_LIBRARY_PATH="${VIVID_FLATPAK_LD_LIBRARY_PATH:-${VIVID_INSTALL_LIB_DIR}:${VIVID_INSTALL_LIB64_DIR}}"
