/* generated by protocol_gen.py from vivid_display_v1.toml — do not edit */

#ifndef VIVID_PRODUCER_CONFIG_SCHEMA_H
#define VIVID_PRODUCER_CONFIG_SCHEMA_H

#include <glib.h>

typedef enum
{
    VIVID_CONFIG_SCHEMA_BOOL,
    VIVID_CONFIG_SCHEMA_INT,
    VIVID_CONFIG_SCHEMA_STRING,
    VIVID_CONFIG_SCHEMA_ARRAY,
    VIVID_CONFIG_SCHEMA_OBJECT,
} VividConfigSchemaType;

typedef struct
{
    const gchar* kebab_key;
    const gchar* camel_key;
    VividConfigSchemaType type;
} VividConfigSchemaEntry;

static const VividConfigSchemaEntry vivid_set_state_schema[] = {
    {"reset-defaults", "resetDefaults", VIVID_CONFIG_SCHEMA_BOOL},
    {"mute", NULL, VIVID_CONFIG_SCHEMA_BOOL},
    {"volume", NULL, VIVID_CONFIG_SCHEMA_INT},
    {"change-wallpaper", "changeWallpaper", VIVID_CONFIG_SCHEMA_BOOL},
    {"change-wallpaper-directory-path", "changeWallpaperDirectoryPath", VIVID_CONFIG_SCHEMA_STRING},
    {"change-wallpaper-interval", "changeWallpaperInterval", VIVID_CONFIG_SCHEMA_INT},
    {"change-wallpaper-mode", "changeWallpaperMode", VIVID_CONFIG_SCHEMA_INT},
    {"playback-on-focus", "playbackOnFocus", VIVID_CONFIG_SCHEMA_INT},
    {"playback-on-maximize-or-fullscreen", "playbackOnMaximizeOrFullscreen", VIVID_CONFIG_SCHEMA_INT},
    {"playback-on-audio", "playbackOnAudio", VIVID_CONFIG_SCHEMA_INT},
    {"playback-on-battery", "playbackOnBattery", VIVID_CONFIG_SCHEMA_INT},
    {"application-rules", "applicationRules", VIVID_CONFIG_SCHEMA_ARRAY},
    {"debug-mode", "debugMode", VIVID_CONFIG_SCHEMA_BOOL},
    {"render-device", "renderDevice", VIVID_CONFIG_SCHEMA_STRING},
    {"content-fit", "contentFit", VIVID_CONFIG_SCHEMA_INT},
    {"scene-fps", "sceneFps", VIVID_CONFIG_SCHEMA_INT},
    {"startup-delay", "startupDelay", VIVID_CONFIG_SCHEMA_INT},
    {"show-panel-menu", "showPanelMenu", VIVID_CONFIG_SCHEMA_BOOL},
    {"project-browser-filter-state", "projectBrowserFilterState", VIVID_CONFIG_SCHEMA_STRING},
    {"project-browser-sort-key", "projectBrowserSortKey", VIVID_CONFIG_SCHEMA_STRING},
    {"multi-display-mode", "multiDisplayMode", VIVID_CONFIG_SCHEMA_STRING},
    {"primary-display-key", "primaryDisplayKey", VIVID_CONFIG_SCHEMA_STRING},
    {"current-config-display-key", "currentConfigDisplayKey", VIVID_CONFIG_SCHEMA_STRING},
    {"per-output-projects", "perOutputProjects", VIVID_CONFIG_SCHEMA_OBJECT},
};

#endif
