// generated by protocol_gen.py from vivid_display_v1.toml — do not edit

import {
    VIVID_DISPLAY_CONTROL_HEADER_BYTES,
    VIVID_DISPLAY_FRAME_READY_BODY_BYTES,
    VIVID_DISPLAY_POINTER_AXIS_BODY_BYTES,
    VIVID_DISPLAY_POINTER_BUTTON_BODY_BYTES,
    VIVID_DISPLAY_POINTER_MOTION_BODY_BYTES,
    VIVID_DISPLAY_UNBIND_BODY_BYTES,
    VIVID_DISPLAY_AUDIO_SAMPLES_BIN_MAX_COUNT,
} from './protocol-constants.js';

export function encodeControlHeader(opcode, flags, json_length) {
    const body = new Uint8Array(VIVID_DISPLAY_CONTROL_HEADER_BYTES);
    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);
    view.setUint16(0, opcode, true);
    view.setUint16(2, flags, true);
    view.setUint32(4, json_length, true);
    return body;
}

export function decodeControlHeader(body) {
    if (body.length !== VIVID_DISPLAY_CONTROL_HEADER_BYTES)
        throw new Error(`invalid CONTROL-HEADER body length ${body.length}`);
    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);
    return {
        opcode: view.getUint16(0, true),
        flags: view.getUint16(2, true),
        jsonLength: view.getUint32(4, true),
    };
}

export function encodePointerMotion(output_id, x, y, time_usec) {
    const body = new Uint8Array(VIVID_DISPLAY_POINTER_MOTION_BODY_BYTES);
    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);
    view.setUint32(0, output_id, true);
    view.setFloat64(4, x, true);
    view.setFloat64(12, y, true);
    view.setBigUint64(20, BigInt(time_usec), true);
    return body;
}

export function decodePointerMotion(body) {
    if (body.length !== VIVID_DISPLAY_POINTER_MOTION_BODY_BYTES)
        throw new Error(`invalid POINTER-MOTION body length ${body.length}`);
    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);
    return {
        outputId: view.getUint32(0, true),
        x: view.getFloat64(4, true),
        y: view.getFloat64(12, true),
        timeUsec: Number(view.getBigUint64(20, true)),
    };
}

export function encodePointerButton(output_id, x, y, button, state, time_usec) {
    const body = new Uint8Array(VIVID_DISPLAY_POINTER_BUTTON_BODY_BYTES);
    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);
    view.setUint32(0, output_id, true);
    view.setFloat64(4, x, true);
    view.setFloat64(12, y, true);
    view.setUint32(20, button, true);
    view.setUint32(24, state, true);
    view.setBigUint64(28, BigInt(time_usec), true);
    return body;
}

export function decodePointerButton(body) {
    if (body.length !== VIVID_DISPLAY_POINTER_BUTTON_BODY_BYTES)
        throw new Error(`invalid POINTER-BUTTON body length ${body.length}`);
    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);
    return {
        outputId: view.getUint32(0, true),
        x: view.getFloat64(4, true),
        y: view.getFloat64(12, true),
        button: view.getUint32(20, true),
        state: view.getUint32(24, true),
        timeUsec: Number(view.getBigUint64(28, true)),
    };
}

export function encodePointerAxis(output_id, x, y, delta_x, delta_y, source, time_usec) {
    const body = new Uint8Array(VIVID_DISPLAY_POINTER_AXIS_BODY_BYTES);
    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);
    view.setUint32(0, output_id, true);
    view.setFloat64(4, x, true);
    view.setFloat64(12, y, true);
    view.setFloat64(20, delta_x, true);
    view.setFloat64(28, delta_y, true);
    view.setUint32(36, source, true);
    view.setBigUint64(40, BigInt(time_usec), true);
    return body;
}

export function decodePointerAxis(body) {
    if (body.length !== VIVID_DISPLAY_POINTER_AXIS_BODY_BYTES)
        throw new Error(`invalid POINTER-AXIS body length ${body.length}`);
    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);
    return {
        outputId: view.getUint32(0, true),
        x: view.getFloat64(4, true),
        y: view.getFloat64(12, true),
        deltaX: view.getFloat64(20, true),
        deltaY: view.getFloat64(28, true),
        source: view.getUint32(36, true),
        timeUsec: Number(view.getBigUint64(40, true)),
    };
}

export function encodeFrameReady(output_id, generation, buffer_index, sequence, target_time_usec, flags) {
    const body = new Uint8Array(VIVID_DISPLAY_FRAME_READY_BODY_BYTES);
    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);
    view.setUint32(0, output_id, true);
    view.setBigUint64(4, BigInt(generation), true);
    view.setUint32(12, buffer_index, true);
    view.setBigUint64(16, BigInt(sequence), true);
    view.setBigUint64(24, BigInt(target_time_usec), true);
    view.setUint32(32, flags, true);
    return body;
}

export function decodeFrameReady(body) {
    if (body.length !== VIVID_DISPLAY_FRAME_READY_BODY_BYTES)
        throw new Error(`invalid FRAME-READY body length ${body.length}`);
    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);
    return {
        outputId: view.getUint32(0, true),
        generation: Number(view.getBigUint64(4, true)),
        bufferIndex: view.getUint32(12, true),
        sequence: Number(view.getBigUint64(16, true)),
        targetTimeUsec: Number(view.getBigUint64(24, true)),
        flags: view.getUint32(32, true),
    };
}

export function encodeUnbind(output_id, generation) {
    const body = new Uint8Array(VIVID_DISPLAY_UNBIND_BODY_BYTES);
    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);
    view.setUint32(0, output_id, true);
    view.setBigUint64(4, BigInt(generation), true);
    return body;
}

export function decodeUnbind(body) {
    if (body.length !== VIVID_DISPLAY_UNBIND_BODY_BYTES)
        throw new Error(`invalid UNBIND body length ${body.length}`);
    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);
    return {
        outputId: view.getUint32(0, true),
        generation: Number(view.getBigUint64(4, true)),
    };
}

export function encodeAudioSamplesBin(count, timeUsec, samples) {
    const body = new Uint8Array(12 + count * 4);
    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);
    view.setUint32(0, count, true);
    view.setBigUint64(4, BigInt(timeUsec), true);
    for (let index = 0; index < count; index++)
        view.setFloat32(12 + index * 4, samples[index], true);
    return body;
}

export function decodeAudioSamplesBin(body) {
    const view = new DataView(body.buffer, body.byteOffset, body.byteLength);
    const count = view.getUint32(0, true);
    const timeUsec = Number(view.getBigUint64(4, true));
    const samples = new Array(count);
    for (let index = 0; index < count; index++)
        samples[index] = view.getFloat32(12 + index * 4, true);
    return { count, timeUsec, samples };
}
