#!/bin/sh

# Path configuration for the catch-all layer-shell consumer.
# Mirrors gnome/kde: generated files stay under this consumer's .build tree.

: "${ROOT_DIR:?ROOT_DIR must be set before sourcing tools/consumer_layer_shell/build_env.sh}"

VIVID_LAYER_SHELL_ROOT_DIR="${VIVID_LAYER_SHELL_ROOT_DIR:-${ROOT_DIR}}"
. "${VIVID_LAYER_SHELL_ROOT_DIR}/../../tools/build_arch.sh"
VIVID_BUILD_ARCH="$(vivid_normalize_build_arch "${VIVID_BUILD_ARCH:-$(uname -m)}")"

VIVID_LAYER_SHELL_BUILD_ROOT="${VIVID_LAYER_SHELL_BUILD_ROOT:-${VIVID_LAYER_SHELL_ROOT_DIR}/.build}"
VIVID_LAYER_SHELL_BUILD_DIR="${VIVID_LAYER_SHELL_BUILD_DIR:-${VIVID_LAYER_SHELL_BUILD_ROOT}/build}"
VIVID_LAYER_SHELL_PACKAGE_VERSION="${VIVID_LAYER_SHELL_PACKAGE_VERSION:-${VIVID_CONSUMER_PACKAGE_VERSION:-1.0.0}}"
VIVID_LAYER_SHELL_PACKAGE_ABI="${VIVID_LAYER_SHELL_PACKAGE_ABI:-${VIVID_BUILD_ARCH}}"
VIVID_LAYER_SHELL_RELEASE_ROOT="${VIVID_LAYER_SHELL_RELEASE_ROOT:-${VIVID_LAYER_SHELL_BUILD_ROOT}/release-${VIVID_BUILD_ARCH}}"
VIVID_LAYER_SHELL_RELEASE_DEPS_DIR="${VIVID_LAYER_SHELL_RELEASE_DEPS_DIR:-${VIVID_LAYER_SHELL_RELEASE_ROOT}/deps}"
VIVID_LAYER_SHELL_RELEASE_PREFIX="${VIVID_LAYER_SHELL_RELEASE_PREFIX:-${VIVID_LAYER_SHELL_RELEASE_ROOT}/prefix}"
VIVID_LAYER_SHELL_RELEASE_BUILD_DIR="${VIVID_LAYER_SHELL_RELEASE_BUILD_DIR:-${VIVID_LAYER_SHELL_RELEASE_ROOT}/build}"
VIVID_LAYER_SHELL_DIST_DIR="${VIVID_LAYER_SHELL_DIST_DIR:-${VIVID_LAYER_SHELL_BUILD_ROOT}/dist}"
VIVID_LAYER_SHELL_RELEASE_ARTIFACT="${VIVID_LAYER_SHELL_RELEASE_ARTIFACT:-${VIVID_LAYER_SHELL_DIST_DIR}/vivid-layer-shell-consumer-${VIVID_LAYER_SHELL_PACKAGE_VERSION}-${VIVID_LAYER_SHELL_PACKAGE_ABI}}"

case "${VIVID_LAYER_SHELL_PACKAGE_VERSION}" in
    ""|*[!0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz._+~-]*)
        echo "Invalid VIVID_LAYER_SHELL_PACKAGE_VERSION=${VIVID_LAYER_SHELL_PACKAGE_VERSION}; expected a package-safe version." >&2
        exit 1
        ;;
esac
